var searchData=
[
  ['jar_0',['Package the native lib as a jar',['../d7/d1e/tutorial_clojure_dev_intro.html#autotoc_md883',1,'']]],
  ['jars_1',['Locally install the jars',['../d7/d1e/tutorial_clojure_dev_intro.html#autotoc_md884',1,'']]],
  ['java_2',['java',['../db/df6/tutorial_erosion_dilatation.html#autotoc_md550',1,'The dilation function (Java)'],['../db/df6/tutorial_erosion_dilatation.html#autotoc_md549',1,'The erosion method (Java)'],['../db/df6/tutorial_erosion_dilatation.html#autotoc_md548',1,'Updating the image (Java)']]],
  ['java_20and_20scala_3',['SBT project for Java and Scala',['../d9/d52/tutorial_java_dev_intro.html#autotoc_md945',1,'']]],
  ['java_20android_4',['Java &amp; Android',['../df/d65/tutorial_table_of_content_introduction.html#autotoc_md1004',1,'']]],
  ['java_20code_20with_20opencv_20and_20mkl_20dependency_5',['Running Java code with OpenCV and MKL dependency',['../d1/d0a/tutorial_java_eclipse.html#autotoc_md985',1,'']]],
  ['java_20development_6',['Introduction to Java Development',['../d9/d52/tutorial_java_dev_intro.html',1,'tutorial_table_of_content_introduction']]],
  ['java_20project_7',['Testing the configuration on a new Java project',['../d1/d0a/tutorial_java_eclipse.html#autotoc_md984',1,'']]],
  ['java_20sample_20with_20ant_8',['Java sample with Ant',['../d9/d52/tutorial_java_dev_intro.html#autotoc_md944',1,'']]],
  ['java_20specific_20libs_20as_20local_20repository_9',['Install the java specific libs as local repository',['../d7/d1e/tutorial_clojure_dev_intro.html#autotoc_md881',1,'']]],
  ['java_20tutorial_20sample_20in_20the_20repl_10',['Mimic the OpenCV Java Tutorial Sample in the REPL',['../d7/d1e/tutorial_clojure_dev_intro.html#autotoc_md887',1,'']]],
  ['java_20with_20eclipse_11',['Using OpenCV Java with Eclipse',['../d1/d0a/tutorial_java_eclipse.html',1,'tutorial_table_of_content_introduction']]],
  ['java_5fdev_5fintro_2emarkdown_12',['java_dev_intro.markdown',['../d0/d80/java__dev__intro_8markdown.html',1,'']]],
  ['java_5feclipse_2emarkdown_13',['java_eclipse.markdown',['../d0/d9c/java__eclipse_8markdown.html',1,'']]],
  ['javascript_20programmer_14',['OpenCV.js: OpenCV for the JavaScript programmer',['../df/d0a/tutorial_js_intro.html#autotoc_md1784',1,'']]],
  ['jetson_20l4t_15',['Configuring Jetson L4T',['../d6/d15/tutorial_building_tegra_cuda.html#autotoc_md873',1,'']]],
  ['jetson_20l4t_20configuration_16',['Jetson L4T Configuration',['../d6/d15/tutorial_building_tegra_cuda.html#autotoc_md863',1,'']]],
  ['jetson_20tk1_17',['Jetson TK1',['../d6/d15/tutorial_building_tegra_cuda.html#autotoc_md864',1,'']]],
  ['jetson_20tx1_18',['Jetson TX1',['../d6/d15/tutorial_building_tegra_cuda.html#autotoc_md865',1,'']]],
  ['jflushstream_19',['jflushStream',['../d7/d13/classcv_1_1AVIWriteContainer.html#ad727ab9c530b7f85bf5cf455d5ea95c9',1,'cv::AVIWriteContainer']]],
  ['join_20',['join',['../d0/de2/structcv_1_1datasets_1_1join.html',1,'cv::datasets::join'],['../dc/dfa/namespacecv_1_1utils_1_1fs.html#abd0ef8c83e77e143081b83a953492c7a',1,'cv::utils::fs::join()']]],
  ['jointbilateralfilter_21',['jointBilateralFilter',['../da/d17/group__ximgproc__filters.html#ga80b9b58fb85dd069691b709285ab985c',1,'cv::ximgproc']]],
  ['jpeg_22',['JPEG',['../d0/d61/group__cudacodec.html#gga71943a1181287609b5d649f53ce6c146a766712d578e6a32b7def99fb0e17ae4c',1,'cv::cudacodec']]],
  ['jpeg_20or_20ycc_23',['RGB &lt;-&gt; YCrCb JPEG (or YCC)',['../de/d25/imgproc_color_conversions.html#autotoc_md141',1,'']]],
  ['jpeg_20tiff_20webp_20support_24',['PNG, JPEG, TIFF, WEBP support',['../db/d05/tutorial_config_reference.html#autotoc_md900',1,'']]],
  ['jputstream_25',['jputStream',['../d7/d13/classcv_1_1AVIWriteContainer.html#a036e1bdfec50b0ad0113a1e3decbe0f1',1,'cv::AVIWriteContainer']]],
  ['jputstreamshort_26',['jputStreamShort',['../d7/d13/classcv_1_1AVIWriteContainer.html#a46b2c58f0c6a4af5c9af2351c2be34fd',1,'cv::AVIWriteContainer']]],
  ['js_27',['js',['../d4/da1/tutorial_js_setup.html',1,'Build OpenCV.js'],['../df/def/tutorial_js_meanshift.html#autotoc_md1835',1,'Camshift in OpenCV.js'],['../d0/d43/tutorial_js_table_of_contents_contours.html',1,'Contours in OpenCV.js'],['../db/d7f/tutorial_js_lucas_kanade.html#autotoc_md1828',1,'Dense Optical Flow in OpenCV.js'],['../d5/dc0/tutorial_js_table_of_contents_histograms.html',1,'Histograms in OpenCV.js'],['../db/db3/tutorial_js_table_of_contents_transforms.html',1,'Image Transforms in OpenCV.js'],['../df/d24/tutorial_js_image_display.html#autotoc_md1601',1,'In OpenCV.js'],['../d0/d84/tutorial_js_usage.html#autotoc_md1816',1,'Include OpenCV.js'],['../df/df7/tutorial_js_table_of_contents_setup.html',1,'Introduction to OpenCV.js'],['../db/d7f/tutorial_js_lucas_kanade.html#autotoc_md1826',1,'Lucas-Kanade Optical Flow in OpenCV.js'],['../df/def/tutorial_js_meanshift.html#autotoc_md1832',1,'Meanshift in OpenCV.js'],['../d0/d84/tutorial_js_usage.html#autotoc_md1817',1,'Use OpenCV.js'],['../d4/da1/tutorial_js_setup.html#autotoc_md1811',1,'Using Node.js.'],['../d0/d84/tutorial_js_usage.html',1,'Using OpenCV.js']]],
  ['js_20and_20tutorials_28',['Introduction to OpenCV.js and Tutorials',['../df/d0a/tutorial_js_intro.html',1,'tutorial_js_table_of_contents_setup']]],
  ['js_20from_20source_29',['Building OpenCV.js from Source',['../d4/da1/tutorial_js_setup.html#autotoc_md1807',1,'']]],
  ['js_20in_20node_20js_30',['Using OpenCV.js In Node.js',['../dc/de6/tutorial_js_nodejs.html',1,'tutorial_js_table_of_contents_setup']]],
  ['js_20tests_31',['Running OpenCV.js Tests',['../d4/da1/tutorial_js_setup.html#autotoc_md1808',1,'']]],
  ['js_20tutorials_32',['js tutorials',['../d5/d10/tutorial_js_root.html',1,'OpenCV.js Tutorials'],['../df/d0a/tutorial_js_intro.html#autotoc_md1785',1,'OpenCV.js Tutorials']]],
  ['js_20with_20docker_33',['Building OpenCV.js with Docker',['../d4/da1/tutorial_js_setup.html#autotoc_md1812',1,'']]],
  ['js_3a_20opencv_20for_20the_20javascript_20programmer_34',['OpenCV.js: OpenCV for the JavaScript programmer',['../df/d0a/tutorial_js_intro.html#autotoc_md1784',1,'']]],
  ['js_5fbasic_5fops_2emarkdown_35',['js_basic_ops.markdown',['../da/d5f/js__basic__ops_8markdown.html',1,'']]],
  ['js_5fbg_5fsubtraction_2emarkdown_36',['js_bg_subtraction.markdown',['../d9/d54/js__bg__subtraction_8markdown.html',1,'']]],
  ['js_5fcanny_2emarkdown_37',['js_canny.markdown',['../d5/da5/js__canny_8markdown.html',1,'']]],
  ['js_5fcolorspaces_2emarkdown_38',['js_colorspaces.markdown',['../da/d3b/js__colorspaces_8markdown.html',1,'']]],
  ['js_5fcontour_5ffeatures_2emarkdown_39',['js_contour_features.markdown',['../dc/d73/js__contour__features_8markdown.html',1,'']]],
  ['js_5fcontour_5fproperties_2emarkdown_40',['js_contour_properties.markdown',['../d2/da4/js__contour__properties_8markdown.html',1,'']]],
  ['js_5fcontours_5fbegin_2emarkdown_41',['js_contours_begin.markdown',['../d3/d40/js__contours__begin_8markdown.html',1,'']]],
  ['js_5fcontours_5fhierarchy_2emarkdown_42',['js_contours_hierarchy.markdown',['../db/dc1/js__contours__hierarchy_8markdown.html',1,'']]],
  ['js_5fcontours_5fmore_5ffunctions_2emarkdown_43',['js_contours_more_functions.markdown',['../da/d53/js__contours__more__functions_8markdown.html',1,'']]],
  ['js_5fface_5fdetection_2emarkdown_44',['js_face_detection.markdown',['../dd/d6a/js__face__detection_8markdown.html',1,'']]],
  ['js_5fface_5fdetection_5fcamera_2emarkdown_45',['js_face_detection_camera.markdown',['../d9/dc3/js__face__detection__camera_8markdown.html',1,'']]],
  ['js_5ffiltering_2emarkdown_46',['js_filtering.markdown',['../d8/d93/js__filtering_8markdown.html',1,'']]],
  ['js_5ffourier_5ftransform_2emarkdown_47',['js_fourier_transform.markdown',['../df/d99/js__fourier__transform_8markdown.html',1,'']]],
  ['js_5fgeometric_5ftransformations_2emarkdown_48',['js_geometric_transformations.markdown',['../d3/d3b/js__geometric__transformations_8markdown.html',1,'']]],
  ['js_5fgrabcut_2emarkdown_49',['js_grabcut.markdown',['../d2/ddc/js__grabcut_8markdown.html',1,'']]],
  ['js_5fgradients_2emarkdown_50',['js_gradients.markdown',['../d8/d7c/js__gradients_8markdown.html',1,'']]],
  ['js_5fhistogram_5fbackprojection_2emarkdown_51',['js_histogram_backprojection.markdown',['../da/d92/js__histogram__backprojection_8markdown.html',1,'']]],
  ['js_5fhistogram_5fbegins_2emarkdown_52',['js_histogram_begins.markdown',['../d8/d45/js__histogram__begins_8markdown.html',1,'']]],
  ['js_5fhistogram_5fequalization_2emarkdown_53',['js_histogram_equalization.markdown',['../dc/dbf/js__histogram__equalization_8markdown.html',1,'']]],
  ['js_5fhoughcircles_2emarkdown_54',['js_houghcircles.markdown',['../d1/d4b/js__houghcircles_8markdown.html',1,'']]],
  ['js_5fhoughlines_2emarkdown_55',['js_houghlines.markdown',['../d0/df9/js__houghlines_8markdown.html',1,'']]],
  ['js_5fimage_5farithmetics_2emarkdown_56',['js_image_arithmetics.markdown',['../d1/d93/js__some__data__structures_2js__image__arithmetics_8markdown.html',1,'(Global Namespace)'],['../de/df1/js__image__arithmetics_2js__image__arithmetics_8markdown.html',1,'(Global Namespace)']]],
  ['js_5fimage_5fclassification_2emarkdown_57',['js_image_classification.markdown',['../d1/d75/js__image__classification_8markdown.html',1,'']]],
  ['js_5fimage_5fclassification_5fwith_5fcamera_2emarkdown_58',['js_image_classification_with_camera.markdown',['../d1/d31/js__image__classification__with__camera_8markdown.html',1,'']]],
  ['js_5fimage_5fdisplay_2emarkdown_59',['js_image_display.markdown',['../d6/d6a/js__image__display_8markdown.html',1,'']]],
  ['js_5fimgproc_5fcamera_2emarkdown_60',['js_imgproc_camera.markdown',['../d7/db4/js__imgproc__camera_8markdown.html',1,'']]],
  ['js_5fintelligent_5fscissors_2emarkdown_61',['js_intelligent_scissors.markdown',['../dd/daa/js__intelligent__scissors_8markdown.html',1,'']]],
  ['js_5fintro_2emarkdown_62',['js_intro.markdown',['../d6/d50/js__intro_8markdown.html',1,'']]],
  ['js_5flucas_5fkanade_2emarkdown_63',['js_lucas_kanade.markdown',['../dd/d67/js__lucas__kanade_8markdown.html',1,'']]],
  ['js_5fmeanshift_2emarkdown_64',['js_meanshift.markdown',['../d8/d53/js__meanshift_8markdown.html',1,'']]],
  ['js_5fmorphological_5fops_2emarkdown_65',['js_morphological_ops.markdown',['../db/dc8/js__morphological__ops_8markdown.html',1,'']]],
  ['js_5fnodejs_2emarkdown_66',['js_nodejs.markdown',['../d9/d61/js__nodejs_8markdown.html',1,'']]],
  ['js_5fobject_5fdetection_2emarkdown_67',['js_object_detection.markdown',['../d1/de1/js__object__detection_8markdown.html',1,'']]],
  ['js_5fobject_5fdetection_5fwith_5fcamera_2emarkdown_68',['js_object_detection_with_camera.markdown',['../d8/df6/js__object__detection__with__camera_8markdown.html',1,'']]],
  ['js_5fpose_5festimation_2emarkdown_69',['js_pose_estimation.markdown',['../dc/d72/js__pose__estimation_8markdown.html',1,'']]],
  ['js_5fpyramids_2emarkdown_70',['js_pyramids.markdown',['../db/dee/js__pyramids_8markdown.html',1,'']]],
  ['js_5fsemantic_5fsegmentation_2emarkdown_71',['js_semantic_segmentation.markdown',['../dd/d8f/js__semantic__segmentation_8markdown.html',1,'']]],
  ['js_5fsetup_2emarkdown_72',['js_setup.markdown',['../d1/df5/js__setup_8markdown.html',1,'']]],
  ['js_5fstyle_5ftransfer_2emarkdown_73',['js_style_transfer.markdown',['../d3/d0c/js__style__transfer_8markdown.html',1,'']]],
  ['js_5ftable_5fof_5fcontents_5fcontours_2emarkdown_74',['js_table_of_contents_contours.markdown',['../d5/dee/js__table__of__contents__contours_8markdown.html',1,'']]],
  ['js_5ftable_5fof_5fcontents_5fcore_2emarkdown_75',['js_table_of_contents_core.markdown',['../d2/dac/js__table__of__contents__core_8markdown.html',1,'']]],
  ['js_5ftable_5fof_5fcontents_5fdnn_2emarkdown_76',['js_table_of_contents_dnn.markdown',['../d6/d14/js__table__of__contents__dnn_8markdown.html',1,'']]],
  ['js_5ftable_5fof_5fcontents_5fgui_2emarkdown_77',['js_table_of_contents_gui.markdown',['../d3/dea/js__table__of__contents__gui_8markdown.html',1,'']]],
  ['js_5ftable_5fof_5fcontents_5fhistograms_2emarkdown_78',['js_table_of_contents_histograms.markdown',['../d3/d12/js__table__of__contents__histograms_8markdown.html',1,'']]],
  ['js_5ftable_5fof_5fcontents_5fimgproc_2emarkdown_79',['js_table_of_contents_imgproc.markdown',['../de/d34/js__table__of__contents__imgproc_8markdown.html',1,'']]],
  ['js_5ftable_5fof_5fcontents_5fobjdetect_2emarkdown_80',['js_table_of_contents_objdetect.markdown',['../d5/d35/js__table__of__contents__objdetect_8markdown.html',1,'']]],
  ['js_5ftable_5fof_5fcontents_5fsetup_2emarkdown_81',['js_table_of_contents_setup.markdown',['../d7/d0a/js__table__of__contents__setup_8markdown.html',1,'']]],
  ['js_5ftable_5fof_5fcontents_5ftransforms_2emarkdown_82',['js_table_of_contents_transforms.markdown',['../d9/ddb/js__table__of__contents__transforms_8markdown.html',1,'']]],
  ['js_5ftable_5fof_5fcontents_5fvideo_2emarkdown_83',['js_table_of_contents_video.markdown',['../df/d34/js__table__of__contents__video_8markdown.html',1,'']]],
  ['js_5ftemplate_5fmatching_2emarkdown_84',['js_template_matching.markdown',['../d3/d94/js__template__matching_8markdown.html',1,'']]],
  ['js_5fthresholding_2emarkdown_85',['js_thresholding.markdown',['../d1/dbe/js__thresholding_8markdown.html',1,'']]],
  ['js_5ftrackbar_2emarkdown_86',['js_trackbar.markdown',['../d6/d28/js__trackbar_8markdown.html',1,'']]],
  ['js_5ftutorials_2emarkdown_87',['js_tutorials.markdown',['../dc/d49/js__tutorials_8markdown.html',1,'']]],
  ['js_5fusage_2emarkdown_88',['js_usage.markdown',['../d3/d0f/js__usage_8markdown.html',1,'']]],
  ['js_5fvideo_5fdisplay_2emarkdown_89',['js_video_display.markdown',['../de/d0f/js__video__display_8markdown.html',1,'']]],
  ['js_5fwatershed_2emarkdown_90',['js_watershed.markdown',['../d4/d13/js__watershed_8markdown.html',1,'']]],
  ['json_20file_20storages_91',['XML/YAML/JSON file storages.',['../d4/da4/group__core__xml.html#xml_storage',1,'']]],
  ['julia_92',['Julia',['../d8/da4/tutorial_julia.html#autotoc_md1964',1,'']]],
  ['julia_20bindings_20for_20opencv_93',['Julia bindings for OpenCV',['../d7/d44/group__julia.html',1,'']]],
  ['julia_20opencv_20binding_94',['Introduction to Julia OpenCV Binding',['../d8/da4/tutorial_julia.html',1,'tutorial_contrib_root']]],
  ['julia_2ehpp_95',['julia.hpp',['../d8/d00/julia_8hpp.html',1,'']]],
  ['julia_2emarkdown_96',['julia.markdown',['../d5/d69/julia_8markdown.html',1,'']]],
  ['just_20happened_97',['What just happened?',['../dc/de6/tutorial_js_nodejs.html#autotoc_md1790',1,'']]]
];
