var searchData=
[
  ['3_209_201_0',['3 9 1',['../d3/d52/tutorial_windows_install.html#tutorial_windows_gitbash_build',1,'Installation by Using git-bash (version&gt;=2.14.1) and cmake (version &gt;=3.9.1)'],['../db/d4c/tutorial_install_tesseract.html',1,'Tesseract (master) installation by using git-bash (version&gt;=2.14.1) and cmake (version &gt;=3.9.1)']]],
  ['3_20_3a_202d_20histograms_1',['Histograms - 3 : 2D Histograms',['../dd/d0d/tutorial_py_2d_histogram.html',1,'tutorial_py_table_of_contents_histograms']]],
  ['3_20_3a_20histogram_20backprojection_2',['Histogram - 3 : Histogram Backprojection',['../dd/d4d/tutorial_js_histogram_backprojection.html',1,'tutorial_js_table_of_contents_histograms']]],
  ['3_20_3a_20opencv_20sample_20style_3',['Method 3 : OpenCV sample style !!',['../dd/d0d/tutorial_py_2d_histogram.html#autotoc_md1398',1,'']]],
  ['3_20build_20and_20archive_20opencv_20libraries_20and_20headers_4',['Step 3. Build and archive OpenCV libraries and headers',['../d3/dd9/tutorial_crosscompile_with_multiarch.html#autotoc_md936',1,'']]],
  ['3_20color_20quantization_5',['3. Color Quantization',['../d1/d5c/tutorial_py_kmeans_opencv.html#autotoc_md1483',1,'']]],
  ['3_20contour_20perimeter_6',['3 contour perimeter',['../dd/d49/tutorial_py_contour_features.html#autotoc_md1313',1,'3. Contour Perimeter'],['../dc/dcf/tutorial_js_contour_features.html#autotoc_md1624',1,'3. Contour Perimeter']]],
  ['3_20match_20shapes_7',['3 match shapes',['../d8/d1c/tutorial_js_contours_more_functions.html#autotoc_md1670',1,'3. Match Shapes'],['../d5/d45/tutorial_py_contours_more_functions.html#autotoc_md1357',1,'3. Match Shapes']]],
  ['3_20median_20blurring_8',['3 median blurring',['../d4/d13/tutorial_py_filtering.html#autotoc_md1365',1,'3. Median Blurring'],['../dd/d6a/tutorial_js_filtering.html#autotoc_md1680',1,'3. Median Blurring']]],
  ['3_20opening_9',['3 opening',['../d9/d61/tutorial_py_morphological_ops.html#autotoc_md1438',1,'3. Opening'],['../d4/d76/tutorial_js_morphological_ops.html#autotoc_md1739',1,'3. Opening']]],
  ['3_20orientation_20assignment_10',['3. Orientation Assignment',['../da/df5/tutorial_py_sift_intro.html#autotoc_md1263',1,'']]],
  ['3_20retr_5fccomp_11',['3 retr_ccomp',['../da/d0a/tutorial_js_contours_hierarchy.html#autotoc_md1663',1,'3. RETR_CCOMP'],['../d9/d8b/tutorial_py_contours_hierarchy.html#autotoc_md1349',1,'3. RETR_CCOMP']]],
  ['3_20solidity_12',['3 solidity',['../da/dc1/tutorial_js_contour_properties.html#autotoc_md1645',1,'3. Solidity'],['../d1/d32/tutorial_py_contour_properties.html#autotoc_md1327',1,'3. Solidity']]],
  ['3_20tonemap_20hdr_20image_13',['3. Tonemap HDR image',['../d2/df0/tutorial_py_hdr.html#autotoc_md1517',1,'']]],
  ['3_20update_20dpkg_20settings_14',['Step 3. Update dpkg settings',['../d3/dd9/tutorial_crosscompile_with_multiarch.html#autotoc_md931',1,'']]],
  ['30_2dimplementation_2emarkdown_15',['30-implementation.markdown',['../db/d5a/30-implementation_8markdown.html',1,'']]],
  ['3_3a_20build_16',['Step 3: Build',['../d0/d3d/tutorial_general_install.html#tutorial_general_install_sources_3',1,'']]],
  ['3_3a_20homography_20from_20the_20camera_20displacement_17',['Demo 3: Homography from the camera displacement',['../d9/dab/tutorial_homography.html#tutorial_homography_Demo3',1,'']]],
  ['3_3a_20install_18',['(optional) Step 3: Install',['../d0/d3d/tutorial_general_install.html#tutorial_general_install_sources_4',1,'']]],
  ['3d_20cameras_19',['Using Orbbec Astra 3D cameras',['../d4/d65/tutorial_orbbec_astra.html',1,'tutorial_table_of_content_app']]],
  ['3d_20features_20',['Surface Matching Algorithm Through 3D Features',['../d9/d25/group__surface__matching.html#autotoc_md96',1,'']]],
  ['3d_20histogram_21',['Creating a 3D histogram',['../d1/d1d/tutorial_histo3D.html',1,'tutorial_table_of_content_viz']]],
  ['3d_20object_20tracking_22',['silhouette based 3D object tracking',['../d4/dc4/group__rapid.html',1,'']]],
  ['3d_20reconstruction_23',['3d reconstruction',['../d9/d0c/group__calib3d.html',1,'Camera Calibration and 3D Reconstruction'],['../d9/db7/tutorial_py_table_of_contents_calib3d.html',1,'Camera Calibration and 3D Reconstruction'],['../d3/ddc/group__ccalib.html',1,'Custom Calibration Pattern for 3D reconstruction']]],
  ['3d_20reconstruction_20calib3d_20module_24',['Camera calibration and 3D reconstruction (calib3d module)',['../d6/d55/tutorial_table_of_content_calib3d.html',1,'tutorial_root']]],
  ['3d_20visualiser_25',['OGRE 3D Visualiser',['../d2/d17/group__ovis.html',1,'']]],
  ['3d_20visualizer_26',['3D Visualizer',['../d1/d19/group__viz.html',1,'']]],
  ['3rd_20party_20drivers_20or_20cameras_27',['Use 3rd party drivers or cameras',['../d0/da7/videoio_overview.html#autotoc_md151',1,'']]],
  ['3x_20scaling_20factor_28',['3x scaling factor',['../dc/d69/tutorial_dnn_superres_benchmark.html#autotoc_md1892',1,'3x scaling factor'],['../dc/d69/tutorial_dnn_superres_benchmark.html#autotoc_md1896',1,'3x scaling factor']]]
];
