var searchData=
[
  ['naryeltwiselayer_0',['NaryEltwiseLayer',['../d1/de0/classcv_1_1dnn_1_1NaryEltwiseLayer.html',1,'cv::dnn']]],
  ['narymatiterator_1',['NAryMatIterator',['../d5/dd2/classcv_1_1NAryMatIterator.html',1,'cv']]],
  ['ncvbroxopticalflowdescriptor_2',['NCVBroxOpticalFlowDescriptor',['../db/d7a/structNCVBroxOpticalFlowDescriptor.html',1,'']]],
  ['ncvmatrix_3',['NCVMatrix',['../de/d26/classNCVMatrix.html',1,'']]],
  ['ncvmatrixalloc_4',['NCVMatrixAlloc',['../d7/d3a/classNCVMatrixAlloc.html',1,'']]],
  ['ncvmatrixreuse_5',['NCVMatrixReuse',['../df/d82/classNCVMatrixReuse.html',1,'']]],
  ['ncvmemnativeallocator_6',['NCVMemNativeAllocator',['../dc/d18/classNCVMemNativeAllocator.html',1,'']]],
  ['ncvmemptr_7',['NCVMemPtr',['../d6/d86/structNCVMemPtr.html',1,'']]],
  ['ncvmemsegment_8',['NCVMemSegment',['../d2/d12/structNCVMemSegment.html',1,'']]],
  ['ncvmemstackallocator_9',['NCVMemStackAllocator',['../db/d74/classNCVMemStackAllocator.html',1,'']]],
  ['ncvpoint2d32s_10',['NcvPoint2D32s',['../d5/d93/structNcvPoint2D32s.html',1,'']]],
  ['ncvpoint2d32u_11',['NcvPoint2D32u',['../dc/d16/structNcvPoint2D32u.html',1,'']]],
  ['ncvrect32s_12',['NcvRect32s',['../d3/dfe/structNcvRect32s.html',1,'']]],
  ['ncvrect32u_13',['NcvRect32u',['../d0/d62/structNcvRect32u.html',1,'']]],
  ['ncvrect8u_14',['NcvRect8u',['../da/d3f/structNcvRect8u.html',1,'']]],
  ['ncvsize32s_15',['NcvSize32s',['../d7/dda/structNcvSize32s.html',1,'']]],
  ['ncvsize32u_16',['NcvSize32u',['../d8/dde/structNcvSize32u.html',1,'']]],
  ['ncvvector_17',['NCVVector',['../dc/d73/classNCVVector.html',1,'']]],
  ['ncvvectoralloc_18',['NCVVectorAlloc',['../d8/da0/classNCVVectorAlloc.html',1,'']]],
  ['ncvvectorreuse_19',['NCVVectorReuse',['../da/d61/classNCVVectorReuse.html',1,'']]],
  ['nearestinterptr_20',['NearestInterPtr',['../d0/df5/structcv_1_1cudev_1_1NearestInterPtr.html',1,'cv::cudev']]],
  ['nearestinterptrsz_21',['NearestInterPtrSz',['../df/dd0/structcv_1_1cudev_1_1NearestInterPtrSz.html',1,'cv::cudev']]],
  ['negate_22',['negate',['../d9/d77/structcv_1_1cudev_1_1negate.html',1,'cv::cudev']]],
  ['net_23',['Net',['../db/d30/classcv_1_1dnn_1_1Net.html',1,'cv::dnn']]],
  ['no_24',['no',['../db/d13/structcv_1_1cudev_1_1IsBinaryFunction_1_1No.html',1,'cv::cudev::IsBinaryFunction&lt; F &gt;::No'],['../dc/d5a/structcv_1_1cudev_1_1IsUnaryFunction_1_1No.html',1,'cv::cudev::IsUnaryFunction&lt; F &gt;::No']]],
  ['nobundleadjuster_25',['NoBundleAdjuster',['../db/dd4/classcv_1_1detail_1_1NoBundleAdjuster.html',1,'cv::detail']]],
  ['node_26',['node',['../d4/d7d/classcv_1_1ml_1_1DTrees_1_1Node.html',1,'cv::ml::DTrees::Node'],['../d3/de3/classcv_1_1Node.html',1,'cv::Node&lt; OBJECT &gt;'],['../d2/d7d/structcv_1_1optflow_1_1GPCTree_1_1Node.html',1,'cv::optflow::GPCTree::Node'],['../d9/de0/structcv_1_1SparseMat_1_1Node.html',1,'cv::SparseMat::Node']]],
  ['nodedata_27',['NodeData',['../d7/dc2/classcv_1_1instr_1_1NodeData.html',1,'cv::instr']]],
  ['nodedatatls_28',['NodeDataTls',['../da/df1/structcv_1_1instr_1_1NodeDataTls.html',1,'cv::instr']]],
  ['noexposurecompensator_29',['NoExposureCompensator',['../d2/dc1/classcv_1_1detail_1_1NoExposureCompensator.html',1,'cv::detail']]],
  ['normalbayesclassifier_30',['NormalBayesClassifier',['../d4/d8e/classcv_1_1ml_1_1NormalBayesClassifier.html',1,'cv::ml']]],
  ['normalizebboxlayer_31',['NormalizeBBoxLayer',['../dc/df8/classcv_1_1dnn_1_1NormalizeBBoxLayer.html',1,'cv::dnn']]],
  ['normhamming_32',['NormHamming',['../d5/d7b/structcv_1_1cudev_1_1NormHamming.html',1,'cv::cudev']]],
  ['normhistogramcostextractor_33',['NormHistogramCostExtractor',['../df/d65/classcv_1_1NormHistogramCostExtractor.html',1,'cv']]],
  ['norml1_34',['NormL1',['../d7/df8/structcv_1_1cudev_1_1NormL1.html',1,'cv::cudev']]],
  ['norml1_3c_20float_20_3e_35',['NormL1&lt; float &gt;',['../d5/d1e/structcv_1_1cudev_1_1NormL1_3_01float_01_4.html',1,'cv::cudev']]],
  ['norml2_36',['NormL2',['../dc/da6/structcv_1_1cudev_1_1NormL2.html',1,'cv::cudev']]],
  ['noseamfinder_37',['NoSeamFinder',['../d3/da9/classcv_1_1detail_1_1NoSeamFinder.html',1,'cv::detail']]],
  ['not_5fequal_5fto_38',['not_equal_to',['../df/d9f/structcv_1_1cudev_1_1not__equal__to.html',1,'cv::cudev']]],
  ['notag_39',['NoTag',['../db/d4e/structcv_1_1detail_1_1NoTag.html',1,'cv::detail']]],
  ['notimplemented_40',['NotImplemented',['../df/de8/structcv_1_1gapi_1_1s11n_1_1detail_1_1NotImplemented.html',1,'cv::gapi::s11n::detail']]],
  ['notlayer_41',['NotLayer',['../d0/dd0/classcv_1_1dnn_1_1NotLayer.html',1,'cv::dnn']]],
  ['nppstinterpolationstate_42',['NppStInterpolationState',['../da/da9/structNppStInterpolationState.html',1,'']]],
  ['nsobject_43',['NSObject',['../d4/d19/classNSObject.html',1,'']]],
  ['nsobject_2dp_44',['NSObject-p',['../d9/d15/classNSObject-p.html',1,'']]],
  ['nsobjectnsobject_2dp_45',['NSObjectNSObject-p',['../d5/d25/classNSObjectNSObject-p.html',1,'']]],
  ['nulldeblurer_46',['NullDeblurer',['../dc/d86/classcv_1_1videostab_1_1NullDeblurer.html',1,'cv::videostab']]],
  ['nullframesource_47',['NullFrameSource',['../dd/d5b/classcv_1_1videostab_1_1NullFrameSource.html',1,'cv::videostab']]],
  ['nullinpainter_48',['NullInpainter',['../d4/d1d/classcv_1_1videostab_1_1NullInpainter.html',1,'cv::videostab']]],
  ['nulllog_49',['NullLog',['../d6/d78/classcv_1_1videostab_1_1NullLog.html',1,'cv::videostab']]],
  ['nulloutlierrejector_50',['NullOutlierRejector',['../d3/de9/classcv_1_1videostab_1_1NullOutlierRejector.html',1,'cv::videostab']]],
  ['nulltype_51',['NullType',['../d5/d71/structcv_1_1cudev_1_1NullType.html',1,'cv::cudev']]],
  ['nullwobblesuppressor_52',['NullWobbleSuppressor',['../d0/da4/classcv_1_1videostab_1_1NullWobbleSuppressor.html',1,'cv::videostab']]],
  ['numeric_5flimits_53',['numeric_limits',['../db/dc8/structcv_1_1cudev_1_1numeric__limits.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20bool_20_3e_54',['numeric_limits&lt; bool &gt;',['../da/d81/structcv_1_1cudev_1_1numeric__limits_3_01bool_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20double_20_3e_55',['numeric_limits&lt; double &gt;',['../d2/d80/structcv_1_1cudev_1_1numeric__limits_3_01double_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20float_20_3e_56',['numeric_limits&lt; float &gt;',['../db/d88/structcv_1_1cudev_1_1numeric__limits_3_01float_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20schar_20_3e_57',['numeric_limits&lt; schar &gt;',['../da/d4e/structcv_1_1cudev_1_1numeric__limits_3_01schar_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20short_20_3e_58',['numeric_limits&lt; short &gt;',['../d1/d8b/structcv_1_1cudev_1_1numeric__limits_3_01short_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20uchar_20_3e_59',['numeric_limits&lt; uchar &gt;',['../d3/dc7/structcv_1_1cudev_1_1numeric__limits_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20uint_20_3e_60',['numeric_limits&lt; uint &gt;',['../dd/d89/structcv_1_1cudev_1_1numeric__limits_3_01uint_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20ushort_20_3e_61',['numeric_limits&lt; ushort &gt;',['../df/d47/structcv_1_1cudev_1_1numeric__limits_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['nvidiahwopticalflow_62',['NvidiaHWOpticalFlow',['../d5/d26/classcv_1_1cuda_1_1NvidiaHWOpticalFlow.html',1,'cv::cuda']]],
  ['nvidiaopticalflow_5f1_5f0_63',['NvidiaOpticalFlow_1_0',['../dc/d9d/classcv_1_1cuda_1_1NvidiaOpticalFlow__1__0.html',1,'cv::cuda']]],
  ['nvidiaopticalflow_5f2_5f0_64',['NvidiaOpticalFlow_2_0',['../db/d70/classcv_1_1cuda_1_1NvidiaOpticalFlow__2__0.html',1,'cv::cuda']]]
];
