var searchData=
[
  ['cache_0',['cache',['../da/da5/structcv_1_1gapi_1_1fluid_1_1View_1_1Cache.html',1,'cv::gapi::fluid::View::Cache'],['../dc/dd8/structcv_1_1gapi_1_1fluid_1_1Buffer_1_1Cache.html',1,'cv::gapi::fluid::Buffer::Cache']]],
  ['calibratecrf_1',['CalibrateCRF',['../dd/de3/classcv_1_1CalibrateCRF.html',1,'cv']]],
  ['calibratedebevec_2',['CalibrateDebevec',['../da/d27/classcv_1_1CalibrateDebevec.html',1,'cv']]],
  ['calibraterobertson_3',['CalibrateRobertson',['../d3/d30/classcv_1_1CalibrateRobertson.html',1,'cv']]],
  ['call_5fand_5fpostprocess_4',['call_and_postprocess',['../d5/def/structcv_1_1detail_1_1OCLCallHelper_3_01Impl_00_01std_1_1tuple_3_01Ins_8_8_8_01_4_00_01std_1_1tua67cc2fc13da93c8cd58afcdf4d9cddf.html',1,'cv::detail::OCLCallHelper&lt; Impl, std::tuple&lt; Ins... &gt;, std::tuple&lt; Outs... &gt; &gt;::call_and_postprocess&lt; Inputs &gt;'],['../d6/d6e/structcv_1_1detail_1_1OCVStCallHelper_3_01Impl_00_01std_1_1tuple_3_01Ins_8_8_8_01_4_00_01std_1_13d2a3f9fe53c503f6ff24e00be30d613.html',1,'cv::detail::OCVStCallHelper&lt; Impl, std::tuple&lt; Ins... &gt;, std::tuple&lt; Outs... &gt; &gt;::call_and_postprocess&lt; Inputs &gt;'],['../df/de6/structcv_1_1detail_1_1OCVCallHelper_3_01Impl_00_01std_1_1tuple_3_01Ins_8_8_8_01_4_00_01std_1_1tu8bfb77c34485398698447f60ee067830.html',1,'cv::detail::OCVCallHelper&lt; Impl, std::tuple&lt; Ins... &gt;, std::tuple&lt; Outs... &gt; &gt;::call_and_postprocess&lt; Inputs &gt;']]],
  ['callback_5',['callback',['../d8/d9f/classcv_1_1LMSolver_1_1Callback.html',1,'cv::LMSolver::Callback'],['../d0/d4f/classcv_1_1text_1_1ERFilter_1_1Callback.html',1,'cv::text::ERFilter::Callback']]],
  ['callbackproxy_6',['CallbackProxy',['../d1/d63/classcv_1_1parallel_1_1tbb_1_1ParallelForBackend_1_1CallbackProxy.html',1,'cv::parallel::tbb::ParallelForBackend']]],
  ['callcustomgetborder_7',['callCustomGetBorder',['../dc/df0/structcv_1_1detail_1_1callCustomGetBorder.html',1,'cv::detail']]],
  ['callcustomgetborder_3c_20false_2c_20impl_20_3e_8',['callCustomGetBorder&lt; false, Impl &gt;',['../d6/dea/structcv_1_1detail_1_1callCustomGetBorder_3_01false_00_01Impl_01_4.html',1,'cv::detail']]],
  ['callcustomgetborder_3c_20true_2c_20impl_20_3e_9',['callCustomGetBorder&lt; true, Impl &gt;',['../d0/df2/structcv_1_1detail_1_1callCustomGetBorder_3_01true_00_01Impl_01_4.html',1,'cv::detail']]],
  ['callmetadata_10',['CallMetaData',['../d4/dd9/structcvv_1_1impl_1_1CallMetaData.html',1,'cvv::impl']]],
  ['camera_11',['Camera',['../dc/d3a/classcv_1_1viz_1_1Camera.html',1,'cv::viz']]],
  ['cameraparam_12',['cameraParam',['../d3/d99/structcv_1_1datasets_1_1cameraParam.html',1,'cv::datasets']]],
  ['cameraparams_13',['CameraParams',['../d4/d0a/structcv_1_1detail_1_1CameraParams.html',1,'cv::detail']]],
  ['camerapos_14',['cameraPos',['../d1/d64/structcv_1_1datasets_1_1cameraPos.html',1,'cv::datasets']]],
  ['candidate_15',['Candidate',['../df/da3/structcv_1_1linemod_1_1QuantizedPyramid_1_1Candidate.html',1,'cv::linemod::QuantizedPyramid']]],
  ['cannyedgedetector_16',['CannyEdgeDetector',['../d0/d43/classcv_1_1cuda_1_1CannyEdgeDetector.html',1,'cv::cuda']]],
  ['cascadeclassifier_17',['cascadeclassifier',['../d1/de5/classcv_1_1CascadeClassifier.html',1,'cv::CascadeClassifier'],['../d9/d80/classcv_1_1cuda_1_1CascadeClassifier.html',1,'cv::cuda::CascadeClassifier']]],
  ['cchecker_18',['CChecker',['../db/d3e/classcv_1_1mcc_1_1CChecker.html',1,'cv::mcc']]],
  ['ccheckerdetector_19',['CCheckerDetector',['../d9/d53/classcv_1_1mcc_1_1CCheckerDetector.html',1,'cv::mcc']]],
  ['ccheckerdraw_20',['CCheckerDraw',['../d2/dee/classcv_1_1mcc_1_1CCheckerDraw.html',1,'cv::mcc']]],
  ['ceillayer_21',['CeilLayer',['../d3/dd0/classcv_1_1dnn_1_1CeilLayer.html',1,'cv::dnn']]],
  ['celulayer_22',['CeluLayer',['../db/d28/classcv_1_1dnn_1_1CeluLayer.html',1,'cv::dnn']]],
  ['cfgparam_23',['CfgParam',['../d4/d70/structcv_1_1gapi_1_1wip_1_1onevpl_1_1CfgParam.html',1,'cv::gapi::wip::onevpl']]],
  ['channelscompensator_24',['ChannelsCompensator',['../d4/ddd/classcv_1_1detail_1_1ChannelsCompensator.html',1,'cv::detail']]],
  ['channelsprelulayer_25',['ChannelsPReLULayer',['../d7/de9/classcv_1_1dnn_1_1ChannelsPReLULayer.html',1,'cv::dnn']]],
  ['charucoboard_26',['CharucoBoard',['../d0/d3c/classcv_1_1aruco_1_1CharucoBoard.html',1,'cv::aruco']]],
  ['charucodetector_27',['CharucoDetector',['../d9/df5/classcv_1_1aruco_1_1CharucoDetector.html',1,'cv::aruco']]],
  ['charucoparameters_28',['CharucoParameters',['../df/d01/structcv_1_1aruco_1_1CharucoParameters.html',1,'cv::aruco']]],
  ['check_29',['check',['../dd/d16/classcv_1_1detail_1_1has__custom__wrap_1_1check.html',1,'cv::detail::has_custom_wrap']]],
  ['chihistogramcostextractor_30',['ChiHistogramCostExtractor',['../dd/d43/classcv_1_1ChiHistogramCostExtractor.html',1,'cv']]],
  ['circle_31',['Circle',['../d8/d07/structcv_1_1gapi_1_1wip_1_1draw_1_1Circle.html',1,'cv::gapi::wip::draw']]],
  ['circlesgridfinderparameters_32',['CirclesGridFinderParameters',['../d2/dd1/structcv_1_1CirclesGridFinderParameters.html',1,'cv']]],
  ['clahe_33',['clahe',['../db/d79/classcv_1_1cuda_1_1CLAHE.html',1,'cv::cuda::CLAHE'],['../d6/db6/classcv_1_1CLAHE.html',1,'cv::CLAHE']]],
  ['classificationmodel_34',['ClassificationModel',['../d0/dd5/classcv_1_1dnn_1_1ClassificationModel.html',1,'cv::dnn']]],
  ['classifiercallback_35',['classifiercallback',['../de/d2d/classcv_1_1text_1_1OCRBeamSearchDecoder_1_1ClassifierCallback.html',1,'cv::text::OCRBeamSearchDecoder::ClassifierCallback'],['../db/dc0/classcv_1_1text_1_1OCRHMMDecoder_1_1ClassifierCallback.html',1,'cv::text::OCRHMMDecoder::ClassifierCallback']]],
  ['classifierthreshold_36',['classifierthreshold',['../d7/d6f/classcv_1_1detail_1_1tracking_1_1online__boosting_1_1ClassifierThreshold.html',1,'cv::detail::ClassifierThreshold'],['../d7/d6f/classcv_1_1detail_1_1tracking_1_1online__boosting_1_1ClassifierThreshold.html',1,'cv::detail::tracking::ClassifierThreshold'],['../d7/d6f/classcv_1_1detail_1_1tracking_1_1online__boosting_1_1ClassifierThreshold.html',1,'cv::detail::tracking::online_boosting::ClassifierThreshold']]],
  ['color_37',['Color',['../d4/dba/classcv_1_1viz_1_1Color.html',1,'cv::viz']]],
  ['coloraverageinpainter_38',['ColorAverageInpainter',['../d1/dc6/classcv_1_1videostab_1_1ColorAverageInpainter.html',1,'cv::videostab']]],
  ['colorcamera_39',['ColorCamera',['../de/ddc/classcv_1_1gapi_1_1oak_1_1ColorCamera.html',1,'cv::gapi::oak']]],
  ['colorcameraparams_40',['ColorCameraParams',['../d4/d95/structcv_1_1gapi_1_1oak_1_1ColorCameraParams.html',1,'cv::gapi::oak']]],
  ['colorcorrectionmodel_41',['ColorCorrectionModel',['../df/d38/classcv_1_1ccm_1_1ColorCorrectionModel.html',1,'cv::ccm']]],
  ['coloredkinfu_42',['ColoredKinFu',['../d5/d61/classcv_1_1colored__kinfu_1_1ColoredKinFu.html',1,'cv::colored_kinfu']]],
  ['colorgradient_43',['ColorGradient',['../dc/d64/classcv_1_1linemod_1_1ColorGradient.html',1,'cv::linemod']]],
  ['colorinpainter_44',['ColorInpainter',['../d3/d2b/classcv_1_1videostab_1_1ColorInpainter.html',1,'cv::videostab']]],
  ['colormomenthash_45',['ColorMomentHash',['../df/d52/classcv_1_1img__hash_1_1ColorMomentHash.html',1,'cv::img_hash']]],
  ['commandlineparser_46',['CommandLineParser',['../d0/d2e/classcv_1_1CommandLineParser.html',1,'cv']]],
  ['commonareainterptr_47',['CommonAreaInterPtr',['../d8/d3d/structcv_1_1cudev_1_1CommonAreaInterPtr.html',1,'cv::cudev']]],
  ['commonareainterptrsz_48',['CommonAreaInterPtrSz',['../db/d1c/structcv_1_1cudev_1_1CommonAreaInterPtrSz.html',1,'cv::cudev']]],
  ['comparelayer_49',['CompareLayer',['../df/d72/classcv_1_1dnn_1_1CompareLayer.html',1,'cv::dnn']]],
  ['compileargtag_50',['CompileArgTag',['../dd/d3d/structcv_1_1detail_1_1CompileArgTag.html',1,'cv::detail']]],
  ['compileargtag_3c_20cv_3a_3agapi_3a_3acalib3d_3a_3acpu_3a_3astereoinitparam_20_3e_51',['CompileArgTag&lt; cv::gapi::calib3d::cpu::StereoInitParam &gt;',['../d8/dab/structcv_1_1detail_1_1CompileArgTag_3_01cv_1_1gapi_1_1calib3d_1_1cpu_1_1StereoInitParam_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20cv_3a_3agapi_3a_3agnetpackage_20_3e_52',['CompileArgTag&lt; cv::gapi::GNetPackage &gt;',['../dc/dbf/structcv_1_1detail_1_1CompileArgTag_3_01cv_1_1gapi_1_1GNetPackage_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20cv_3a_3agapi_3a_3aot_3a_3aobjecttrackerparams_20_3e_53',['CompileArgTag&lt; cv::gapi::ot::ObjectTrackerParams &gt;',['../d8/d7e/structcv_1_1detail_1_1CompileArgTag_3_01cv_1_1gapi_1_1ot_1_1ObjectTrackerParams_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20cv_3a_3agapi_3a_3aplaidml_3a_3aconfig_20_3e_54',['CompileArgTag&lt; cv::gapi::plaidml::config &gt;',['../da/d3c/structcv_1_1detail_1_1CompileArgTag_3_01cv_1_1gapi_1_1plaidml_1_1config_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20cv_3a_3agapi_3a_3astreaming_3a_3aqueue_5fcapacity_20_3e_55',['CompileArgTag&lt; cv::gapi::streaming::queue_capacity &gt;',['../de/d54/structcv_1_1detail_1_1CompileArgTag_3_01cv_1_1gapi_1_1streaming_1_1queue__capacity_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20cv_3a_3agapi_3a_3ause_5fonly_20_3e_56',['CompileArgTag&lt; cv::gapi::use_only &gt;',['../df/d53/structcv_1_1detail_1_1CompileArgTag_3_01cv_1_1gapi_1_1use__only_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20cv_3a_3agapi_3a_3avideo_3a_3abackgroundsubtractorparams_20_3e_57',['CompileArgTag&lt; cv::gapi::video::BackgroundSubtractorParams &gt;',['../d6/d7e/structcv_1_1detail_1_1CompileArgTag_3_01cv_1_1gapi_1_1video_1_1BackgroundSubtractorParams_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20cv_3a_3agapi_3a_3awip_3a_3adraw_3a_3afreetype_5ffont_20_3e_58',['CompileArgTag&lt; cv::gapi::wip::draw::freetype_font &gt;',['../d8/da3/structcv_1_1detail_1_1CompileArgTag_3_01cv_1_1gapi_1_1wip_1_1draw_1_1freetype__font_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20cv_3a_3agapi_3a_3awip_3a_3aov_3a_3abenchmark_5fmode_20_3e_59',['CompileArgTag&lt; cv::gapi::wip::ov::benchmark_mode &gt;',['../d5/db1/structcv_1_1detail_1_1CompileArgTag_3_01cv_1_1gapi_1_1wip_1_1ov_1_1benchmark__mode_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20cv_3a_3agkernelpackage_20_3e_60',['CompileArgTag&lt; cv::GKernelPackage &gt;',['../de/d89/structcv_1_1detail_1_1CompileArgTag_3_01cv_1_1GKernelPackage_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20cv_3a_3agraph_5fdump_5fpath_20_3e_61',['CompileArgTag&lt; cv::graph_dump_path &gt;',['../d3/d64/structcv_1_1detail_1_1CompileArgTag_3_01cv_1_1graph__dump__path_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20cv_3a_3ause_5fthreaded_5fexecutor_20_3e_62',['CompileArgTag&lt; cv::use_threaded_executor &gt;',['../de/dad/structcv_1_1detail_1_1CompileArgTag_3_01cv_1_1use__threaded__executor_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20gapi_3a_3aoak_3a_3acolorcameraparams_20_3e_63',['CompileArgTag&lt; gapi::oak::ColorCameraParams &gt;',['../d0/d47/structcv_1_1detail_1_1CompileArgTag_3_01gapi_1_1oak_1_1ColorCameraParams_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20gapi_3a_3aoak_3a_3aencoderconfig_20_3e_64',['CompileArgTag&lt; gapi::oak::EncoderConfig &gt;',['../d0/d0e/structcv_1_1detail_1_1CompileArgTag_3_01gapi_1_1oak_1_1EncoderConfig_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20gapi_3a_3astreaming_3a_3async_5fpolicy_20_3e_65',['CompileArgTag&lt; gapi::streaming::sync_policy &gt;',['../da/d8d/structcv_1_1detail_1_1CompileArgTag_3_01gapi_1_1streaming_1_1sync__policy_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20gfluidoutputrois_20_3e_66',['CompileArgTag&lt; GFluidOutputRois &gt;',['../d7/d5e/structcv_1_1detail_1_1CompileArgTag_3_01GFluidOutputRois_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20gfluidparallelfor_20_3e_67',['CompileArgTag&lt; GFluidParallelFor &gt;',['../de/d5f/structcv_1_1detail_1_1CompileArgTag_3_01GFluidParallelFor_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20gfluidparalleloutputrois_20_3e_68',['CompileArgTag&lt; GFluidParallelOutputRois &gt;',['../d5/dc7/structcv_1_1detail_1_1CompileArgTag_3_01GFluidParallelOutputRois_01_4.html',1,'cv::detail']]],
  ['compiledmodel_69',['CompiledModel',['../d5/def/structcv_1_1gapi_1_1ov_1_1detail_1_1ParamDesc_1_1CompiledModel.html',1,'cv::gapi::ov::detail::ParamDesc']]],
  ['complex_70',['Complex',['../da/df6/classcv_1_1Complex.html',1,'cv']]],
  ['compressedrectilinearportraitprojector_71',['CompressedRectilinearPortraitProjector',['../d0/ded/structcv_1_1detail_1_1CompressedRectilinearPortraitProjector.html',1,'cv::detail']]],
  ['compressedrectilinearportraitwarper_72',['compressedrectilinearportraitwarper',['../de/d9a/classcv_1_1CompressedRectilinearPortraitWarper.html',1,'cv::CompressedRectilinearPortraitWarper'],['../dd/dc8/classcv_1_1detail_1_1CompressedRectilinearPortraitWarper.html',1,'cv::detail::CompressedRectilinearPortraitWarper']]],
  ['compressedrectilinearprojector_73',['CompressedRectilinearProjector',['../db/dbb/structcv_1_1detail_1_1CompressedRectilinearProjector.html',1,'cv::detail']]],
  ['compressedrectilinearwarper_74',['compressedrectilinearwarper',['../dd/dbe/classcv_1_1detail_1_1CompressedRectilinearWarper.html',1,'cv::detail::CompressedRectilinearWarper'],['../d0/dd5/classcv_1_1CompressedRectilinearWarper.html',1,'cv::CompressedRectilinearWarper']]],
  ['concatlayer_75',['ConcatLayer',['../da/d5c/classcv_1_1dnn_1_1ConcatLayer.html',1,'cv::dnn']]],
  ['config_76',['config',['../d0/ded/structcv_1_1face_1_1FacemarkAAM_1_1Config.html',1,'cv::face::FacemarkAAM::Config'],['../de/d39/structcv_1_1gapi_1_1plaidml_1_1config.html',1,'cv::gapi::plaidml::config']]],
  ['conjgradsolver_77',['ConjGradSolver',['../d0/d21/classcv_1_1ConjGradSolver.html',1,'cv']]],
  ['consistentmosaicinpainter_78',['ConsistentMosaicInpainter',['../d9/dba/classcv_1_1videostab_1_1ConsistentMosaicInpainter.html',1,'cv::videostab']]],
  ['constantptr_79',['ConstantPtr',['../d5/db7/structcv_1_1cudev_1_1ConstantPtr.html',1,'cv::cudev']]],
  ['constantptrsz_80',['ConstantPtrSz',['../d2/df7/structcv_1_1cudev_1_1ConstantPtrSz.html',1,'cv::cudev']]],
  ['constlayer_81',['ConstLayer',['../de/dff/classcv_1_1dnn_1_1ConstLayer.html',1,'cv::dnn']]],
  ['contains_5fshape_5ffield_82',['contains_shape_field',['../dd/dbc/structcv_1_1detail_1_1contains__shape__field.html',1,'cv::detail']]],
  ['contains_5fshape_5ffield_3c_20taggedtypecandidate_2c_20void_5ft_3c_20decltype_28taggedtypecandidate_3a_3ashape_29_3e_20_3e_83',['contains_shape_field&lt; TaggedTypeCandidate, void_t&lt; decltype(TaggedTypeCandidate::shape)&gt; &gt;',['../d7/de9/structcv_1_1detail_1_1contains__shape__field_3_01TaggedTypeCandidate_00_01void__t_3_01decltype_096f2ad3af4e5ab1f02059720b7ba9eda.html',1,'cv::detail']]],
  ['contains_5fshape_5ffield_3c_20type_20_3e_84',['contains_shape_field&lt; Type &gt;',['../dd/dbc/structcv_1_1detail_1_1contains__shape__field.html',1,'cv::detail']]],
  ['context_85',['context',['../d1/d45/classcv_1_1ocl_1_1Context.html',1,'cv::ocl::Context'],['../dc/d38/structcv_1_1gapi_1_1wip_1_1onevpl_1_1Context.html',1,'cv::gapi::wip::onevpl::Context']]],
  ['contourfitting_86',['ContourFitting',['../d5/d72/classcv_1_1ximgproc_1_1ContourFitting.html',1,'cv::ximgproc']]],
  ['converttuple_87',['ConvertTuple',['../d9/d6a/structcv_1_1cudev_1_1ConvertTuple.html',1,'cv::cudev']]],
  ['convolution_88',['Convolution',['../d4/d25/classcv_1_1cuda_1_1Convolution.html',1,'cv::cuda']]],
  ['convolutionlayer_89',['ConvolutionLayer',['../d5/dcf/classcv_1_1dnn_1_1ConvolutionLayer.html',1,'cv::dnn']]],
  ['convolutionlayerint8_90',['ConvolutionLayerInt8',['../db/d97/classcv_1_1dnn_1_1ConvolutionLayerInt8.html',1,'cv::dnn']]],
  ['copy_5fthrough_5fmove_5ft_91',['copy_through_move_t',['../db/df6/structcv_1_1util_1_1copy__through__move__t.html',1,'cv::util']]],
  ['coreml_92',['CoreML',['../d2/da7/structcv_1_1gapi_1_1onnx_1_1ep_1_1CoreML.html',1,'cv::gapi::onnx::ep']]],
  ['cornernesscriteria_93',['CornernessCriteria',['../dd/d63/classcv_1_1cuda_1_1CornernessCriteria.html',1,'cv::cuda']]],
  ['cornersdetector_94',['CornersDetector',['../de/d95/classcv_1_1cuda_1_1CornersDetector.html',1,'cv::cuda']]],
  ['correlationlayer_95',['CorrelationLayer',['../d4/d8a/classcv_1_1dnn_1_1CorrelationLayer.html',1,'cv::dnn']]],
  ['cos_5ffunc_96',['cos_func',['../d6/dfb/structcv_1_1cudev_1_1cos__func.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20double_20_3e_97',['cos_func&lt; double &gt;',['../db/d23/structcv_1_1cudev_1_1cos__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20float_20_3e_98',['cos_func&lt; float &gt;',['../dd/d7a/structcv_1_1cudev_1_1cos__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20schar_20_3e_99',['cos_func&lt; schar &gt;',['../dc/d25/structcv_1_1cudev_1_1cos__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20short_20_3e_100',['cos_func&lt; short &gt;',['../d7/d03/structcv_1_1cudev_1_1cos__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20uchar_20_3e_101',['cos_func&lt; uchar &gt;',['../dd/d3d/structcv_1_1cudev_1_1cos__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20uint_20_3e_102',['cos_func&lt; uint &gt;',['../da/dc1/structcv_1_1cudev_1_1cos__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20ushort_20_3e_103',['cos_func&lt; ushort &gt;',['../df/d35/structcv_1_1cudev_1_1cos__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['cosdistance_104',['CosDistance',['../da/dd4/classcv_1_1detail_1_1tracking_1_1tbm_1_1CosDistance.html',1,'cv::detail::tracking::tbm']]],
  ['cosh_5ffunc_105',['cosh_func',['../dc/d8a/structcv_1_1cudev_1_1cosh__func.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20double_20_3e_106',['cosh_func&lt; double &gt;',['../d5/d3a/structcv_1_1cudev_1_1cosh__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20float_20_3e_107',['cosh_func&lt; float &gt;',['../db/d8d/structcv_1_1cudev_1_1cosh__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20schar_20_3e_108',['cosh_func&lt; schar &gt;',['../df/dd8/structcv_1_1cudev_1_1cosh__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20short_20_3e_109',['cosh_func&lt; short &gt;',['../dc/d8a/structcv_1_1cudev_1_1cosh__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20uchar_20_3e_110',['cosh_func&lt; uchar &gt;',['../de/d73/structcv_1_1cudev_1_1cosh__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20uint_20_3e_111',['cosh_func&lt; uint &gt;',['../d5/ddd/structcv_1_1cudev_1_1cosh__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20ushort_20_3e_112',['cosh_func&lt; ushort &gt;',['../d2/dd3/structcv_1_1cudev_1_1cosh__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['coshlayer_113',['CoshLayer',['../d2/d1a/classcv_1_1dnn_1_1CoshLayer.html',1,'cv::dnn']]],
  ['coslayer_114',['CosLayer',['../de/dd8/classcv_1_1dnn_1_1CosLayer.html',1,'cv::dnn']]],
  ['countnonzeroexprbody_115',['CountNonZeroExprBody',['../dd/d49/structcv_1_1cudev_1_1CountNonZeroExprBody.html',1,'cv::cudev']]],
  ['cparams_116',['CParams',['../d8/dd8/structcv_1_1face_1_1CParams.html',1,'cv::face']]],
  ['cropandresizelayer_117',['CropAndResizeLayer',['../d8/d53/classcv_1_1dnn_1_1CropAndResizeLayer.html',1,'cv::dnn']]],
  ['croplayer_118',['CropLayer',['../d7/d86/classcv_1_1dnn_1_1CropLayer.html',1,'cv::dnn']]],
  ['ct_5fassert_5ffailure_119',['CT_ASSERT_FAILURE',['../da/d73/structNcvCTprep_1_1CT__ASSERT__FAILURE.html',1,'NcvCTprep']]],
  ['ct_5fassert_5ffailure_3c_20true_20_3e_120',['CT_ASSERT_FAILURE&lt; true &gt;',['../dc/dcf/structNcvCTprep_1_1CT__ASSERT__FAILURE_3_01true_01_4.html',1,'NcvCTprep']]],
  ['cubicinterptr_121',['CubicInterPtr',['../d3/def/structcv_1_1cudev_1_1CubicInterPtr.html',1,'cv::cudev']]],
  ['cubicinterptrsz_122',['CubicInterPtrSz',['../d2/d00/structcv_1_1cudev_1_1CubicInterPtrSz.html',1,'cv::cudev']]],
  ['cuda_123',['CUDA',['../d3/dc7/structcv_1_1gapi_1_1onnx_1_1ep_1_1CUDA.html',1,'cv::gapi::onnx::ep']]],
  ['cumsumlayer_124',['CumSumLayer',['../d1/dd1/classcv_1_1dnn_1_1CumSumLayer.html',1,'cv::dnn']]],
  ['custompattern_125',['CustomPattern',['../d3/d3e/classcv_1_1ccalib_1_1CustomPattern.html',1,'cv::ccalib']]],
  ['cv16suf_126',['Cv16suf',['../dd/d0f/unionCv16suf.html',1,'']]],
  ['cv32suf_127',['Cv32suf',['../d9/df3/unionCv32suf.html',1,'']]],
  ['cv64suf_128',['Cv64suf',['../de/d55/unionCv64suf.html',1,'']]],
  ['cv_5fcamera_5fintrinsics_5fpinhole_5f32f_129',['cv_camera_intrinsics_pinhole_32f',['../d6/d4d/structcv__camera__intrinsics__pinhole__32f.html',1,'']]],
  ['cv_5fcamera_5fintrinsics_5fpinhole_5f64f_130',['cv_camera_intrinsics_pinhole_64f',['../d0/d32/structcv__camera__intrinsics__pinhole__64f.html',1,'']]],
  ['cvabstractcamera_131',['CvAbstractCamera',['../d0/de8/interfaceCvAbstractCamera.html',1,'']]],
  ['cvfeatureevaluator_132',['cvfeatureevaluator',['../dd/dc8/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvFeatureEvaluator.html',1,'cv::detail::tracking::contrib_feature::CvFeatureEvaluator'],['../dd/dc8/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvFeatureEvaluator.html',1,'cv::detail::CvFeatureEvaluator'],['../dd/dc8/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvFeatureEvaluator.html',1,'cv::detail::tracking::CvFeatureEvaluator']]],
  ['cvfeatureparams_133',['cvfeatureparams',['../d4/da7/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvFeatureParams.html',1,'cv::detail::CvFeatureParams'],['../d4/da7/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvFeatureParams.html',1,'cv::detail::tracking::contrib_feature::CvFeatureParams'],['../d4/da7/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvFeatureParams.html',1,'cv::detail::tracking::CvFeatureParams']]],
  ['cvhaarevaluator_134',['cvhaarevaluator',['../d5/d89/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvHaarEvaluator.html',1,'cv::detail::CvHaarEvaluator'],['../d5/d89/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvHaarEvaluator.html',1,'cv::detail::tracking::contrib_feature::CvHaarEvaluator'],['../d5/d89/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvHaarEvaluator.html',1,'cv::detail::tracking::CvHaarEvaluator']]],
  ['cvhaarfeatureparams_135',['cvhaarfeatureparams',['../dd/d27/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvHaarFeatureParams.html',1,'cv::detail::CvHaarFeatureParams'],['../dd/d27/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvHaarFeatureParams.html',1,'cv::detail::tracking::contrib_feature::CvHaarFeatureParams'],['../dd/d27/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvHaarFeatureParams.html',1,'cv::detail::tracking::CvHaarFeatureParams']]],
  ['cvhaldft_136',['cvhalDFT',['../de/d27/structcvhalDFT.html',1,'']]],
  ['cvhalfilter2d_137',['cvhalFilter2D',['../d2/da8/structcvhalFilter2D.html',1,'']]],
  ['cvhalkeypoint_138',['cvhalKeyPoint',['../d9/daa/structcvhalKeyPoint.html',1,'']]],
  ['cvhogevaluator_139',['cvhogevaluator',['../df/ddb/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvHOGEvaluator.html',1,'cv::detail::CvHOGEvaluator'],['../df/ddb/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvHOGEvaluator.html',1,'cv::detail::tracking::contrib_feature::CvHOGEvaluator'],['../df/ddb/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvHOGEvaluator.html',1,'cv::detail::tracking::CvHOGEvaluator']]],
  ['cvhogfeatureparams_140',['cvhogfeatureparams',['../d5/d81/structcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvHOGFeatureParams.html',1,'cv::detail::CvHOGFeatureParams'],['../d5/d81/structcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvHOGFeatureParams.html',1,'cv::detail::tracking::contrib_feature::CvHOGFeatureParams'],['../d5/d81/structcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvHOGFeatureParams.html',1,'cv::detail::tracking::CvHOGFeatureParams']]],
  ['cvlbpevaluator_141',['cvlbpevaluator',['../d0/d65/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvLBPEvaluator.html',1,'cv::detail::tracking::CvLBPEvaluator'],['../d0/d65/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvLBPEvaluator.html',1,'cv::detail::CvLBPEvaluator'],['../d0/d65/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvLBPEvaluator.html',1,'cv::detail::tracking::contrib_feature::CvLBPEvaluator']]],
  ['cvlbpfeatureparams_142',['cvlbpfeatureparams',['../d7/dbf/structcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvLBPFeatureParams.html',1,'cv::detail::CvLBPFeatureParams'],['../d7/dbf/structcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvLBPFeatureParams.html',1,'cv::detail::tracking::contrib_feature::CvLBPFeatureParams'],['../d7/dbf/structcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvLBPFeatureParams.html',1,'cv::detail::tracking::CvLBPFeatureParams']]],
  ['cvparams_143',['cvparams',['../de/d2a/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvParams.html',1,'cv::detail::CvParams'],['../de/d2a/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvParams.html',1,'cv::detail::tracking::contrib_feature::CvParams'],['../de/d2a/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvParams.html',1,'cv::detail::tracking::CvParams']]],
  ['cvphotocamera_144',['CvPhotoCamera',['../d4/d1d/interfaceCvPhotoCamera.html',1,'']]],
  ['cvphotocameradelegate_2dp_145',['CvPhotoCameraDelegate-p',['../d9/d97/protocolCvPhotoCameraDelegate-p.html',1,'']]],
  ['cvtype_146',['CvType',['../d1/def/structcv_1_1flann_1_1CvType.html',1,'cv::flann']]],
  ['cvtype_3c_20char_20_3e_147',['CvType&lt; char &gt;',['../dc/d89/structcv_1_1flann_1_1CvType_3_01char_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20double_20_3e_148',['CvType&lt; double &gt;',['../dc/d69/structcv_1_1flann_1_1CvType_3_01double_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20float_20_3e_149',['CvType&lt; float &gt;',['../dc/dd6/structcv_1_1flann_1_1CvType_3_01float_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20short_20_3e_150',['CvType&lt; short &gt;',['../d2/def/structcv_1_1flann_1_1CvType_3_01short_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20unsigned_20char_20_3e_151',['CvType&lt; unsigned char &gt;',['../d7/da5/structcv_1_1flann_1_1CvType_3_01unsigned_01char_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20unsigned_20short_20_3e_152',['CvType&lt; unsigned short &gt;',['../d9/d57/structcv_1_1flann_1_1CvType_3_01unsigned_01short_01_4.html',1,'cv::flann']]],
  ['cvvideocamera_153',['CvVideoCamera',['../db/da9/interfaceCvVideoCamera.html',1,'']]],
  ['cvvideocameradelegate_2dp_154',['CvVideoCameraDelegate-p',['../db/dbd/protocolCvVideoCameraDelegate-p.html',1,'']]],
  ['cylindricalportraitprojector_155',['CylindricalPortraitProjector',['../df/d3f/structcv_1_1detail_1_1CylindricalPortraitProjector.html',1,'cv::detail']]],
  ['cylindricalportraitwarper_156',['CylindricalPortraitWarper',['../dd/d19/classcv_1_1detail_1_1CylindricalPortraitWarper.html',1,'cv::detail']]],
  ['cylindricalprojector_157',['CylindricalProjector',['../dd/d96/structcv_1_1detail_1_1CylindricalProjector.html',1,'cv::detail']]],
  ['cylindricalwarper_158',['cylindricalwarper',['../d7/df6/classcv_1_1CylindricalWarper.html',1,'cv::CylindricalWarper'],['../d3/dd6/classcv_1_1detail_1_1CylindricalWarper.html',1,'cv::detail::CylindricalWarper']]],
  ['cylindricalwarpergpu_159',['CylindricalWarperGpu',['../d9/dbd/classcv_1_1detail_1_1CylindricalWarperGpu.html',1,'cv::detail']]]
];
