var searchData=
[
  ['oak_2ehpp_0',['oak.hpp',['../de/d62/oak_8hpp.html',1,'']]],
  ['oak_5fdevices_2emarkdown_1',['oak_devices.markdown',['../d0/d98/oak__devices_8markdown.html',1,'']]],
  ['objdetect_2ehpp_2',['objdetect.hpp',['../d7/df0/objdetect_2objdetect_8hpp.html',1,'(Global Namespace)'],['../d8/da3/objdetect_8hpp.html',1,'(Global Namespace)']]],
  ['object_5ffactory_2eh_3',['object_factory.h',['../de/d9f/object__factory_8h.html',1,'']]],
  ['ocl_2ehpp_4',['ocl.hpp',['../da/d74/ocl_8hpp.html',1,'']]],
  ['ocl_5fdefs_2ehpp_5',['ocl_defs.hpp',['../d1/d08/ocl__defs_8hpp.html',1,'']]],
  ['ocl_5fgenbase_2ehpp_6',['ocl_genbase.hpp',['../d1/d1f/ocl__genbase_8hpp.html',1,'']]],
  ['ocr_2ehpp_7',['ocr.hpp',['../db/d5e/ocr_8hpp.html',1,'']]],
  ['oil_5fpainting_5feffect_2emarkdown_8',['oil_painting_effect.markdown',['../d4/d7d/oil__painting__effect_8markdown.html',1,'']]],
  ['oilpainting_2ehpp_9',['oilpainting.hpp',['../dc/d56/oilpainting_8hpp.html',1,'']]],
  ['omnidir_2ehpp_10',['omnidir.hpp',['../db/d62/omnidir_8hpp.html',1,'']]],
  ['omnidir_5ftutorial_2emarkdown_11',['omnidir_tutorial.markdown',['../dc/d3a/omnidir__tutorial_8markdown.html',1,'']]],
  ['onlineboosting_2ehpp_12',['onlineBoosting.hpp',['../d9/dd7/onlineBoosting_8hpp.html',1,'']]],
  ['onnx_2ehpp_13',['onnx.hpp',['../d6/d71/onnx_8hpp.html',1,'']]],
  ['opencl_5finfo_2ehpp_14',['opencl_info.hpp',['../d6/d54/opencl__info_8hpp.html',1,'']]],
  ['opencl_5fsvm_2ehpp_15',['opencl_svm.hpp',['../df/d48/opencl__svm_8hpp.html',1,'']]],
  ['opencv_5fincludes_2ehpp_16',['opencv_includes.hpp',['../dc/d17/opencv__includes_8hpp.html',1,'']]],
  ['opengl_2ehpp_17',['opengl.hpp',['../d4/db0/opengl_8hpp.html',1,'']]],
  ['opening_5fclosing_5fhats_2emarkdown_18',['opening_closing_hats.markdown',['../dd/d42/opening__closing__hats_8markdown.html',1,'']]],
  ['operations_2ehpp_19',['operations.hpp',['../d6/d00/operations_8hpp.html',1,'']]],
  ['operators_2ehpp_20',['operators.hpp',['../dd/dcd/operators_8hpp.html',1,'']]],
  ['optflow_2ehpp_21',['optflow.hpp',['../de/d67/optflow_8hpp.html',1,'']]],
  ['optical_5fflow_2ehpp_22',['optical_flow.hpp',['../dd/d49/videostab_2include_2opencv2_2videostab_2optical__flow_8hpp.html',1,'(Global Namespace)'],['../d2/dc3/superres_2include_2opencv2_2superres_2optical__flow_8hpp.html',1,'(Global Namespace)']]],
  ['optical_5fflow_2emarkdown_23',['optical_flow.markdown',['../db/d50/optical__flow_8markdown.html',1,'']]],
  ['optim_2ehpp_24',['optim.hpp',['../d3/d46/optim_8hpp.html',1,'']]],
  ['optional_2ehpp_25',['optional.hpp',['../db/dd5/optional_8hpp.html',1,'']]],
  ['or_5fimagenet_2ehpp_26',['or_imagenet.hpp',['../d2/d38/or__imagenet_8hpp.html',1,'']]],
  ['or_5fmnist_2ehpp_27',['or_mnist.hpp',['../dc/d44/or__mnist_8hpp.html',1,'']]],
  ['or_5fpascal_2ehpp_28',['or_pascal.hpp',['../d0/d57/or__pascal_8hpp.html',1,'']]],
  ['or_5fsun_2ehpp_29',['or_sun.hpp',['../d4/dc0/or__sun_8hpp.html',1,'']]],
  ['orbbec_5fastra_2emarkdown_30',['orbbec_astra.markdown',['../da/ddd/orbbec__astra_8markdown.html',1,'']]],
  ['ot_2ehpp_31',['ot.hpp',['../d1/dca/cpu_2ot_8hpp.html',1,'(Global Namespace)'],['../d4/d80/ot_8hpp.html',1,'(Global Namespace)']]],
  ['out_5fof_5ffocus_5fdeblur_5ffilter_2emarkdown_32',['out_of_focus_deblur_filter.markdown',['../d4/d4d/out__of__focus__deblur__filter_8markdown.html',1,'']]],
  ['outlier_5frejection_2ehpp_33',['outlier_rejection.hpp',['../da/d94/outlier__rejection_8hpp.html',1,'']]],
  ['ov_2ehpp_34',['ov.hpp',['../da/d96/ov_8hpp.html',1,'']]],
  ['ovis_2ehpp_35',['ovis.hpp',['../d6/d50/ovis_8hpp.html',1,'']]],
  ['ovx_2ehpp_36',['ovx.hpp',['../dd/ded/ovx_8hpp.html',1,'']]],
  ['ovx_5fdefs_2ehpp_37',['ovx_defs.hpp',['../de/d03/ovx__defs_8hpp.html',1,'']]]
];
