var searchData=
[
  ['back_5fprojection_2emarkdown_0',['back_projection.markdown',['../d5/dbb/back__projection_8markdown.html',1,'']]],
  ['background_5fsegm_2ehpp_1',['background_segm.hpp',['../db/d73/background__segm_8hpp.html',1,'']]],
  ['background_5fsubtraction_2emarkdown_2',['background_subtraction.markdown',['../d1/d6d/background__subtraction_8markdown.html',1,'']]],
  ['barcode_2ehpp_3',['barcode.hpp',['../d5/de9/barcode_8hpp.html',1,'']]],
  ['barcode_5fdetect_5fand_5fdecode_2emarkdown_4',['barcode_detect_and_decode.markdown',['../d5/d0c/barcode__detect__and__decode_8markdown.html',1,'']]],
  ['base_2ehpp_5',['base.hpp',['../d7/d29/gapi_2include_2opencv2_2gapi_2s11n_2base_8hpp.html',1,'(Global Namespace)'],['../df/dc3/core_2include_2opencv2_2core_2base_8hpp.html',1,'(Global Namespace)']]],
  ['basic_5fchart_5fdetection_2emarkdown_6',['basic_chart_detection.markdown',['../db/dc1/basic__chart__detection_8markdown.html',1,'']]],
  ['basic_5fgeometric_5fdrawing_2emarkdown_7',['basic_geometric_drawing.markdown',['../d8/d61/basic__geometric__drawing_8markdown.html',1,'']]],
  ['basic_5flinear_5ftransform_2emarkdown_8',['basic_linear_transform.markdown',['../dc/d16/basic__linear__transform_8markdown.html',1,'']]],
  ['bgsegm_2ehpp_9',['bgsegm.hpp',['../d2/dce/bgsegm_8hpp.html',1,'']]],
  ['bgsegm_5fbg_5fsubtraction_2emarkdown_10',['bgsegm_bg_subtraction.markdown',['../d3/ddf/bgsegm__bg__subtraction_8markdown.html',1,'']]],
  ['bif_2ehpp_11',['bif.hpp',['../d3/db4/bif_8hpp.html',1,'']]],
  ['binary_5ffunc_2ehpp_12',['binary_func.hpp',['../d3/d3c/binary__func_8hpp.html',1,'']]],
  ['binary_5fop_2ehpp_13',['binary_op.hpp',['../d7/d8d/binary__op_8hpp.html',1,'']]],
  ['bindings_2ehpp_14',['bindings.hpp',['../d9/d50/bindings_8hpp.html',1,'']]],
  ['bindings_5fie_2ehpp_15',['bindings_ie.hpp',['../d5/d51/bindings__ie_8hpp.html',1,'']]],
  ['bindings_5fonnx_2ehpp_16',['bindings_onnx.hpp',['../d0/d47/bindings__onnx_8hpp.html',1,'']]],
  ['bindings_5fov_2ehpp_17',['bindings_ov.hpp',['../d8/d97/bindings__ov_8hpp.html',1,'']]],
  ['bindings_5futils_2ehpp_18',['bindings_utils.hpp',['../de/d78/bindings__utils_8hpp.html',1,'']]],
  ['bioinspired_2ehpp_19',['bioinspired.hpp',['../d2/dfa/bioinspired_8hpp.html',1,'(Global Namespace)'],['../d4/d64/bioinspired_2bioinspired_8hpp.html',1,'(Global Namespace)']]],
  ['blenders_2ehpp_20',['blenders.hpp',['../d9/d88/blenders_8hpp.html',1,'']]],
  ['block_2ehpp_21',['block.hpp',['../d4/db0/contrib_2modules_2cudev_2include_2opencv2_2cudev_2block_2block_8hpp.html',1,'(Global Namespace)'],['../d3/d30/modules_2core_2include_2opencv2_2core_2cuda_2block_8hpp.html',1,'(Global Namespace)']]],
  ['block_5fmean_5fhash_2ehpp_22',['block_mean_hash.hpp',['../d8/d87/block__mean__hash_8hpp.html',1,'']]],
  ['bm3d_5fimage_5fdenoising_2ehpp_23',['bm3d_image_denoising.hpp',['../dd/dd5/bm3d__image__denoising_8hpp.html',1,'']]],
  ['border_5finterpolate_2ehpp_24',['border_interpolate.hpp',['../d5/dd1/border__interpolate_8hpp.html',1,'']]],
  ['bounding_5frects_5fcircles_2emarkdown_25',['bounding_rects_circles.markdown',['../d9/d5b/bounding__rects__circles_8markdown.html',1,'']]],
  ['bounding_5frotated_5fellipses_2emarkdown_26',['bounding_rotated_ellipses.markdown',['../dd/d8b/bounding__rotated__ellipses_8markdown.html',1,'']]],
  ['brightedges_2ehpp_27',['brightedges.hpp',['../d8/dc5/brightedges_8hpp.html',1,'']]],
  ['buffer_5farea_2eprivate_2ehpp_28',['buffer_area.private.hpp',['../dc/d4a/buffer__area_8private_8hpp.html',1,'']]],
  ['bufferpool_2ehpp_29',['bufferpool.hpp',['../df/d28/bufferpool_8hpp.html',1,'']]],
  ['building_5ftegra_5fcuda_2emarkdown_30',['building_tegra_cuda.markdown',['../d7/d04/building__tegra__cuda_8markdown.html',1,'']]]
];
