var searchData=
[
  ['macbeth_20chart_20module_0',['Macbeth Chart module',['../dd/d19/group__mcc.html',1,'']]],
  ['machine_20learning_1',['Machine Learning',['../dd/ded/group__ml.html',1,'']]],
  ['macos_20osx_20glue_2',['MacOS(OSX) glue',['../dc/d7e/group__imgcodecs__macosx.html',1,'']]],
  ['macros_3',['Utility and system functions and macros',['../db/de0/group__core__utils.html',1,'']]],
  ['magnitude_20calculation_4',['Magnitude calculation',['../d7/d99/group__core__hal__interface__magnitude.html',1,'']]],
  ['main_20classes_5',['G-API Main Classes',['../d8/dd0/group__gapi__main__classes.html',1,'']]],
  ['manipulating_20highgui_20windows_20and_20mouse_20events_6',['Flags related creating and manipulating HighGUI windows and mouse events',['../d0/d90/group__highgui__window__flags.html',1,'']]],
  ['marching_20method_7',['Fast Marching Method',['../db/d18/group__videostab__marching.html',1,'']]],
  ['markers_20and_20boards_20detection_20for_20robust_20camera_20pose_20estimation_8',['ArUco markers and boards detection for robust camera pose estimation',['../de/d67/group__objdetect__aruco.html',1,'']]],
  ['markers_20module_20functionality_20was_20moved_20to_20objdetect_20module_9',['Aruco markers, module functionality was moved to objdetect module',['../d9/d6a/group__aruco.html',1,'']]],
  ['mat_20data_10',['Plot function for Mat data',['../db/dfe/group__plot.html',1,'']]],
  ['matchers_11',['Descriptor Matchers',['../d8/d9b/group__features2d__match.html',1,'']]],
  ['matches_12',['Drawing Function of Keypoints and Matches',['../d4/d5d/group__features2d__draw.html',1,'']]],
  ['matching_13',['matching',['../df/d8c/group__stitching__match.html',1,'Features Finding and Images Matching'],['../d7/dd5/group__datasets__msm.html',1,'Multiview Stereo Matching'],['../d1/d85/group__shape.html',1,'Shape Distance and Matching'],['../d9/d25/group__surface__matching.html',1,'Surface Matching']]],
  ['matching_20algorithm_14',['Experimental 2D Features Matching Algorithm',['../db/dd9/group__xfeatures2d__match.html',1,'']]],
  ['math_20operations_15',['Graph API: Math operations',['../da/dd3/group__gapi__math.html',1,'']]],
  ['math_20with_20f0_20transform_20support_16',['Math with F0-transform support',['../d5/d8e/group__f0__math.html',1,'']]],
  ['math_20with_20f1_20transform_20support_17',['Math with F1-transform support',['../d6/df0/group__f1__math.html',1,'']]],
  ['mathematics_18',['Image processing based on fuzzy mathematics',['../df/d5b/group__fuzzy.html',1,'']]],
  ['matrices_19',['matrices',['../d9/d88/group__cudaarithm__arithm.html',1,'Arithm Operations on Matrices'],['../dd/d0c/group__cannops__core.html',1,'Core Operations on Matrices'],['../de/d09/group__cudaarithm__core.html',1,'Core Operations on Matrices'],['../d0/d86/group__gapi__matrixop.html',1,'Graph API: Operations on matrices'],['../d5/d8e/group__cudaarithm.html',1,'Operations on Matrices']]],
  ['matrix_20decomposition_20',['matrix decomposition',['../d8/d0e/group__core__hal__interface__decomp__cholesky.html',1,'Cholesky matrix decomposition'],['../d5/d42/group__core__hal__interface__decomp__lu.html',1,'LU matrix decomposition'],['../db/d36/group__core__hal__interface__decomp__qr.html',1,'QR matrix decomposition'],['../dd/d2a/group__core__hal__interface__decomp__svd.html',1,'Singular value matrix decomposition']]],
  ['matrix_20multiplication_21',['Matrix multiplication',['../d2/dab/group__core__hal__interface__matrix__multiplication.html',1,'']]],
  ['matrix_20reductions_22',['Matrix Reductions',['../d5/de6/group__cudaarithm__reduce.html',1,'']]],
  ['matting_23',['Alpha Matting',['../d4/d40/group__alphamat.html',1,'']]],
  ['maximum_24',['Element-wise minimum or maximum',['../dc/d19/group__core__hal__interface__minmax.html',1,'']]],
  ['merge_25',['Channel merge',['../df/d2e/group__core__hal__interface__merge.html',1,'']]],
  ['metadata_20descriptors_26',['G-API Metadata Descriptors',['../d3/d0c/group__gapi__meta__args.html',1,'']]],
  ['method_27',['Fast Marching Method',['../db/d18/group__videostab__marching.html',1,'']]],
  ['methods_28',['Improved Background-Foreground Segmentation Methods',['../d2/d55/group__bgsegm.html',1,'']]],
  ['minimum_20or_20maximum_29',['Element-wise minimum or maximum',['../dc/d19/group__core__hal__interface__minmax.html',1,'']]],
  ['miscellaneous_20image_20transformations_30',['Miscellaneous Image Transformations',['../d7/d1b/group__imgproc__misc.html',1,'']]],
  ['model_31',['model',['../de/df4/group__color__correction.html',1,'Color Correction Model'],['../db/d58/group__calib3d__fisheye.html',1,'Fisheye camera model']]],
  ['models_32',['Deformable Part-based Models',['../d9/d12/group__dpm.html',1,'']]],
  ['models_20and_20derivated_20tools_33',['Biologically inspired vision models and derivated tools',['../dd/deb/group__bioinspired.html',1,'']]],
  ['module_34',['module',['../d6/d0f/group__dnn.html',1,'Deep Neural Network module'],['../dd/d19/group__mcc.html',1,'Macbeth Chart module']]],
  ['module_20brings_20implementations_20of_20different_20image_20hashing_20algorithms_35',['The module brings implementations of different image hashing algorithms.',['../d4/d93/group__img__hash.html',1,'']]],
  ['module_20brings_20implementations_20of_20intensity_20transformation_20algorithms_20to_20adjust_20image_20contrast_36',['The module brings implementations of intensity transformation algorithms to adjust image contrast.',['../dc/dfe/group__intensity__transform.html',1,'']]],
  ['module_20functionality_20was_20moved_20to_20objdetect_20module_37',['Aruco markers, module functionality was moved to objdetect module',['../d9/d6a/group__aruco.html',1,'']]],
  ['morphology_20on_20run_20length_20encoded_20image_38',['Binary morphology on run-length encoded image',['../df/def/group__ximgproc__run__length__morphology.html',1,'']]],
  ['motion_39',['Structure From Motion',['../d8/d8c/group__sfm.html',1,'']]],
  ['motion_20analysis_40',['Motion Analysis',['../de/de1/group__video__motion.html',1,'']]],
  ['motion_20analysis_20and_20object_20tracking_41',['Motion Analysis and Object Tracking',['../d7/df3/group__imgproc__motion.html',1,'']]],
  ['motion_20estimation_42',['Global Motion Estimation',['../d4/d2c/group__videostab__motion.html',1,'']]],
  ['mouse_20events_43',['Flags related creating and manipulating HighGUI windows and mouse events',['../d0/d90/group__highgui__window__flags.html',1,'']]],
  ['moved_20to_20objdetect_20module_44',['Aruco markers, module functionality was moved to objdetect module',['../d9/d6a/group__aruco.html',1,'']]],
  ['multi_20dimensional_20spaces_45',['Clustering and Search in Multi-Dimensional Spaces',['../dc/de5/group__flann.html',1,'']]],
  ['multiplication_46',['Matrix multiplication',['../d2/dab/group__core__hal__interface__matrix__multiplication.html',1,'']]],
  ['multiply_47',['Element-wise multiply',['../de/db7/group__core__hal__interface__multiply.html',1,'']]],
  ['multiview_20stereo_20matching_48',['Multiview Stereo Matching',['../d7/dd5/group__datasets__msm.html',1,'']]]
];
