var searchData=
[
  ['edge_20detection_0',['Structured forests for fast edge detection',['../de/d51/group__ximgproc__edge.html',1,'']]],
  ['edgeboxes_1',['EdgeBoxes',['../d4/d0d/group__ximgproc__edgeboxes.html',1,'']]],
  ['edgedrawing_2',['EdgeDrawing',['../d4/d8b/group__ximgproc__edge__drawing.html',1,'']]],
  ['efficient_20image_20segmentation_3',['Hierarchical Feature Selection for Efficient Image Segmentation',['../dc/d29/group__hfs.html',1,'']]],
  ['eigen_20support_4',['Eigen support',['../d0/daf/group__core__eigen.html',1,'']]],
  ['element_20operations_5',['element operations',['../d5/d2b/group__cannops__elem.html',1,'Per-element Operations'],['../d8/d34/group__cudaarithm__elem.html',1,'Per-element Operations']]],
  ['element_20wise_20absolute_20difference_6',['Element-wise absolute difference',['../d5/dec/group__core__hal__interface__absdiff.html',1,'']]],
  ['element_20wise_20add_20and_20subtract_7',['Element-wise add and subtract',['../d8/d6f/group__core__hal__interface__addsub.html',1,'']]],
  ['element_20wise_20compare_8',['Element-wise compare',['../d6/dab/group__core__hal__interface__compare.html',1,'']]],
  ['element_20wise_20divide_9',['Element-wise divide',['../dd/d2c/group__core__hal__interface__divide.html',1,'']]],
  ['element_20wise_20minimum_20or_20maximum_10',['Element-wise minimum or maximum',['../dc/d19/group__core__hal__interface__minmax.html',1,'']]],
  ['element_20wise_20multiply_11',['Element-wise multiply',['../de/db7/group__core__hal__interface__multiply.html',1,'']]],
  ['element_20wise_20reciprocial_12',['Element-wise reciprocial',['../d4/de4/group__core__hal__interface__reciprocial.html',1,'']]],
  ['element_20wise_20weighted_20sum_13',['Element-wise weighted sum',['../da/d9b/group__core__hal__interface__addWeighted.html',1,'']]],
  ['encoded_20image_14',['Binary morphology on run-length encoded image',['../df/def/group__ximgproc__run__length__morphology.html',1,'']]],
  ['encoding_15',['encoding',['../db/dc4/group__videoio__hwaccel.html',1,'Hardware-accelerated video decoding and encoding'],['../df/d77/group__objdetect__qrcode.html',1,'QRCode detection and encoding']]],
  ['encoding_20decoding_16',['Video Encoding/Decoding',['../d0/d61/group__cudacodec.html',1,'']]],
  ['estimation_17',['estimation',['../de/d67/group__objdetect__aruco.html',1,'ArUco markers and boards detection for robust camera pose estimation'],['../d4/d2c/group__videostab__motion.html',1,'Global Motion Estimation'],['../d9/de0/group__datasets__hpe.html',1,'Human Pose Estimation'],['../db/d3a/group__robust.html',1,'Robust Estimation'],['../d7/d74/group__stitching__rotation.html',1,'Rotation Estimation'],['../d9/d24/group__stitching__seam.html',1,'Seam Estimation']]],
  ['events_18',['Flags related creating and manipulating HighGUI windows and mouse events',['../d0/d90/group__highgui__window__flags.html',1,'']]],
  ['experimental_202d_20features_20algorithms_19',['Experimental 2D Features Algorithms',['../d7/d7a/group__xfeatures2d__experiment.html',1,'']]],
  ['experimental_202d_20features_20matching_20algorithm_20',['Experimental 2D Features Matching Algorithm',['../db/dd9/group__xfeatures2d__match.html',1,'']]],
  ['exponent_20calculation_21',['Exponent calculation',['../d4/d8a/group__core__hal__interface__exp.html',1,'']]],
  ['exposure_20compensation_22',['Exposure Compensation',['../dd/dff/group__stitching__exposure.html',1,'']]],
  ['extended_20image_20processing_23',['Extended Image Processing',['../df/d2d/group__ximgproc.html',1,'']]],
  ['extended_20object_20detection_24',['Extended object detection',['../d4/d54/group__xobjdetect.html',1,'']]],
  ['external_20libraries_20plugins_25',['Low-level API for external libraries / plugins',['../da/dd2/group__core__lowlevel__api.html',1,'']]],
  ['extra_202d_20features_20framework_26',['Extra 2D Features Framework',['../d1/db4/group__xfeatures2d.html',1,'']]],
  ['extracted_20from_20an_20image_27',['Binary descriptors for lines extracted from an image',['../dc/ddd/group__line__descriptor.html',1,'']]]
];
