var searchData=
[
  ['o_0',['o',['../dd/d01/group__videoio__c.html',1,'C API for video I/O'],['../d4/d15/group__videoio__flags__base.html',1,'Flags for video I/O'],['../d5/d26/group__videoio__ios.html',1,'iOS glue for video I/O'],['../dd/de7/group__videoio.html',1,'Video I/O'],['../dd/d01/group__videoio__winrt.html',1,'WinRT glue for video I/O']]],
  ['o_20api_20backends_1',['Additional flags for video I/O API backends',['../dc/dfc/group__videoio__flags__others.html',1,'']]],
  ['o_20api_20backends_20registry_2',['Query I/O API backends registry',['../de/db1/group__videoio__registry.html',1,'']]],
  ['o_20routines_3',['Hierarchical Data Format I/O routines',['../db/d77/group__hdf.html',1,'']]],
  ['objdetect_20module_4',['Aruco markers, module functionality was moved to objdetect module',['../d9/d6a/group__aruco.html',1,'']]],
  ['object_20categorization_5',['Object Categorization',['../de/d24/group__features2d__category.html',1,'']]],
  ['object_20detection_6',['object detection',['../de/d37/group__objdetect__cascade__classifier.html',1,'Cascade Classifier for Object Detection'],['../d5/df6/group__dnn__objdetect.html',1,'DNN used for object detection'],['../d4/d54/group__xobjdetect.html',1,'Extended object detection'],['../df/dfb/group__imgproc__object.html',1,'Object Detection'],['../d9/d3f/group__cudaobjdetect.html',1,'Object Detection'],['../d5/d54/group__objdetect.html',1,'Object Detection']]],
  ['object_20detector_7',['HOG (Histogram of Oriented Gradients) descriptor and object detector',['../d4/d11/group__objdetect__hog.html',1,'']]],
  ['object_20recognition_8',['Object Recognition',['../dc/d24/group__datasets__or.html',1,'']]],
  ['object_20tracking_9',['object tracking',['../d7/df3/group__imgproc__motion.html',1,'Motion Analysis and Object Tracking'],['../dc/d6b/group__video__track.html',1,'Object Tracking'],['../d4/dc4/group__rapid.html',1,'silhouette based 3D object tracking']]],
  ['of_20computer_20vision_20programs_10',['GUI for Interactive Visual Debugging of Computer Vision Programs',['../df/dff/group__cvv.html',1,'']]],
  ['of_20different_20image_20hashing_20algorithms_11',['The module brings implementations of different image hashing algorithms.',['../d4/d93/group__img__hash.html',1,'']]],
  ['of_20implemented_20layers_12',['Partial List of Implemented Layers',['../d6/d87/group__dnnLayerList.html',1,'']]],
  ['of_20intensity_20transformation_20algorithms_20to_20adjust_20image_20contrast_13',['The module brings implementations of intensity transformation algorithms to adjust image contrast.',['../dc/dfe/group__intensity__transform.html',1,'']]],
  ['of_20keypoints_20and_20matches_14',['Drawing Function of Keypoints and Matches',['../d4/d5d/group__features2d__draw.html',1,'']]],
  ['of_20oriented_20gradients_20descriptor_20and_20object_20detector_15',['HOG (Histogram of Oriented Gradients) descriptor and object detector',['../d4/d11/group__objdetect__hog.html',1,'']]],
  ['ogre_203d_20visualiser_16',['OGRE 3D Visualiser',['../d2/d17/group__ovis.html',1,'']]],
  ['on_20arrays_17',['Operations on arrays',['../d2/de8/group__core__array.html',1,'']]],
  ['on_20fuzzy_20mathematics_18',['Image processing based on fuzzy mathematics',['../df/d5b/group__fuzzy.html',1,'']]],
  ['on_20matrices_19',['on matrices',['../d9/d88/group__cudaarithm__arithm.html',1,'Arithm Operations on Matrices'],['../de/d09/group__cudaarithm__core.html',1,'Core Operations on Matrices'],['../dd/d0c/group__cannops__core.html',1,'Core Operations on Matrices'],['../d0/d86/group__gapi__matrixop.html',1,'Graph API: Operations on matrices'],['../d5/d8e/group__cudaarithm.html',1,'Operations on Matrices']]],
  ['on_20run_20length_20encoded_20image_20',['Binary morphology on run-length encoded image',['../df/def/group__ximgproc__run__length__morphology.html',1,'']]],
  ['one_20color_20space_20to_20another_21',['Graph API: Converting image from one color space to another',['../dc/d38/group__gapi__colorconvert.html',1,'']]],
  ['opencl_20cl_20va_20interoperability_22',['Intel VA-API/OpenCL (CL-VA) interoperability',['../d1/daa/group__core__va__intel.html',1,'']]],
  ['opencl_20support_23',['OpenCL support',['../dc/d83/group__core__opencl.html',1,'']]],
  ['opencv_24',['opencv',['../d3/d50/group__imgproc__colormap.html',1,'ColorMaps in OpenCV'],['../d7/d44/group__julia.html',1,'Julia bindings for OpenCV']]],
  ['opencv_20samples_25',['Utility functions for OpenCV samples',['../d6/dba/group__core__utils__samples.html',1,'']]],
  ['opengl_20interoperability_26',['OpenGL interoperability',['../d2/d3c/group__core__opengl.html',1,'']]],
  ['opengl_20support_27',['OpenGL support',['../df/d24/group__highgui__opengl.html',1,'']]],
  ['operations_28',['operations',['../d2/d18/group__core__hal__interface__logical.html',1,'Bitwise logical operations'],['../da/dd3/group__gapi__math.html',1,'Graph API: Math operations'],['../d1/db2/group__gapi__pixelwise.html',1,'Graph API: Pixelwise operations'],['../d5/d2b/group__cannops__elem.html',1,'Per-element Operations'],['../d8/d34/group__cudaarithm__elem.html',1,'Per-element Operations']]],
  ['operations_20and_20functions_29',['Drawing operations and functions',['../d0/d43/group__gapi__draw__api.html',1,'']]],
  ['operations_20for_20ascend_20backend_30',['Operations for Ascend Backend.',['../df/d88/group__cannops__ops.html',1,'']]],
  ['operations_20on_20arrays_31',['Operations on arrays',['../d2/de8/group__core__array.html',1,'']]],
  ['operations_20on_20matrices_32',['operations on matrices',['../d9/d88/group__cudaarithm__arithm.html',1,'Arithm Operations on Matrices'],['../de/d09/group__cudaarithm__core.html',1,'Core Operations on Matrices'],['../dd/d0c/group__cannops__core.html',1,'Core Operations on Matrices'],['../d0/d86/group__gapi__matrixop.html',1,'Graph API: Operations on matrices'],['../d5/d8e/group__cudaarithm.html',1,'Operations on Matrices']]],
  ['optical_20flow_33',['Optical Flow',['../d7/d3f/group__cudaoptflow.html',1,'']]],
  ['optical_20flow_20algorithms_34',['Optical Flow Algorithms',['../d2/d84/group__optflow.html',1,'']]],
  ['optimization_20algorithms_35',['Optimization Algorithms',['../da/d01/group__core__optim.html',1,'']]],
  ['or_20maximum_36',['Element-wise minimum or maximum',['../dc/d19/group__core__hal__interface__minmax.html',1,'']]],
  ['oriented_20gradients_20descriptor_20and_20object_20detector_37',['HOG (Histogram of Oriented Gradients) descriptor and object detector',['../d4/d11/group__objdetect__hog.html',1,'']]],
  ['osx_20glue_38',['MacOS(OSX) glue',['../dc/d7e/group__imgcodecs__macosx.html',1,'']]],
  ['output_39',['Input/Output',['../d2/da3/group__io.html',1,'']]]
];
