var searchData=
[
  ['f0_20transform_20support_0',['Math with F0-transform support',['../d5/d8e/group__f0__math.html',1,'']]],
  ['f1_20transform_20support_1',['Math with F1-transform support',['../d6/df0/group__f1__math.html',1,'']]],
  ['face_20analysis_2',['Face Analysis',['../db/d7c/group__face.html',1,'']]],
  ['face_20detection_20and_20recognition_3',['DNN-based face detection and recognition',['../db/d11/group__objdetect__dnn__face.html',1,'']]],
  ['face_20recognition_4',['Face Recognition',['../de/d93/group__datasets__fr.html',1,'']]],
  ['facilities_5',['Logging facilities',['../d3/dcb/group__core__logging.html',1,'']]],
  ['fast_20edge_20detection_6',['Structured forests for fast edge detection',['../de/d51/group__ximgproc__edge.html',1,'']]],
  ['fast_20line_20detector_7',['Fast line detector',['../df/ded/group__ximgproc__fast__line__detector.html',1,'']]],
  ['fast_20marching_20method_8',['Fast Marching Method',['../db/d18/group__videostab__marching.html',1,'']]],
  ['feature_20detection_9',['feature detection',['../dd/d1a/group__imgproc__feature.html',1,'Feature Detection'],['../dc/d6d/group__cudaimgproc__feature.html',1,'Feature Detection'],['../d5/def/group__gapi__feature.html',1,'Graph API: Image Feature Detection']]],
  ['feature_20detection_20and_20description_10',['feature detection and description',['../d5/d51/group__features2d__main.html',1,'Feature Detection and Description'],['../d6/d1d/group__cudafeatures2d.html',1,'Feature Detection and Description']]],
  ['feature_20selection_20for_20efficient_20image_20segmentation_11',['Hierarchical Feature Selection for Efficient Image Segmentation',['../dc/d29/group__hfs.html',1,'']]],
  ['features_20algorithms_12',['features algorithms',['../d7/d7a/group__xfeatures2d__experiment.html',1,'Experimental 2D Features Algorithms'],['../d2/dca/group__xfeatures2d__nonfree.html',1,'Non-free 2D Features Algorithms']]],
  ['features_20finding_20and_20images_20matching_13',['Features Finding and Images Matching',['../df/d8c/group__stitching__match.html',1,'']]],
  ['features_20framework_14',['features framework',['../da/d9b/group__features2d.html',1,'2D Features Framework'],['../d1/db4/group__xfeatures2d.html',1,'Extra 2D Features Framework']]],
  ['features_20matching_20algorithm_15',['Experimental 2D Features Matching Algorithm',['../db/dd9/group__xfeatures2d__match.html',1,'']]],
  ['file_20reading_20and_20writing_16',['file reading and writing',['../d8/d6a/group__imgcodecs__flags.html',1,'Flags used for image file reading and writing'],['../d4/da8/group__imgcodecs.html',1,'Image file reading and writing']]],
  ['filtering_17',['filtering',['../dc/d66/group__cudafilters.html',1,'Image Filtering'],['../d4/d86/group__imgproc__filter.html',1,'Image Filtering']]],
  ['filters_18',['filters',['../da/d17/group__ximgproc__filters.html',1,'Filters'],['../da/dc5/group__gapi__filters.html',1,'Graph API: Image filters']]],
  ['finding_20and_20images_20matching_19',['Features Finding and Images Matching',['../df/d8c/group__stitching__match.html',1,'']]],
  ['fisheye_20camera_20model_20',['Fisheye camera model',['../db/d58/group__calib3d__fisheye.html',1,'']]],
  ['flags_20for_20video_20i_20o_21',['Flags for video I/O',['../d4/d15/group__videoio__flags__base.html',1,'']]],
  ['flags_20for_20video_20i_20o_20api_20backends_22',['Additional flags for video I/O API backends',['../dc/dfc/group__videoio__flags__others.html',1,'']]],
  ['flags_20related_20creating_20and_20manipulating_20highgui_20windows_20and_20mouse_20events_23',['Flags related creating and manipulating HighGUI windows and mouse events',['../d0/d90/group__highgui__window__flags.html',1,'']]],
  ['flags_20used_20for_20image_20file_20reading_20and_20writing_24',['Flags used for image file reading and writing',['../d8/d6a/group__imgcodecs__flags.html',1,'']]],
  ['flow_25',['Optical Flow',['../d7/d3f/group__cudaoptflow.html',1,'']]],
  ['flow_20algorithms_26',['Optical Flow Algorithms',['../d2/d84/group__optflow.html',1,'']]],
  ['for_203d_20reconstruction_27',['Custom Calibration Pattern for 3D reconstruction',['../d3/ddc/group__ccalib.html',1,'']]],
  ['for_20ascend_20backend_28',['Operations for Ascend Backend.',['../df/d88/group__cannops__ops.html',1,'']]],
  ['for_20detecting_20and_20parsing_20qr_20code_29',['WeChat QR code detector for detecting and parsing QR code.',['../dd/d63/group__wechat__qrcode.html',1,'']]],
  ['for_20efficient_20image_20segmentation_30',['Hierarchical Feature Selection for Efficient Image Segmentation',['../dc/d29/group__hfs.html',1,'']]],
  ['for_20external_20libraries_20plugins_31',['Low-level API for external libraries / plugins',['../da/dd2/group__core__lowlevel__api.html',1,'']]],
  ['for_20fast_20edge_20detection_32',['Structured forests for fast edge detection',['../de/d51/group__ximgproc__edge.html',1,'']]],
  ['for_20image_20file_20reading_20and_20writing_33',['Flags used for image file reading and writing',['../d8/d6a/group__imgcodecs__flags.html',1,'']]],
  ['for_20interactive_20visual_20debugging_20of_20computer_20vision_20programs_34',['GUI for Interactive Visual Debugging of Computer Vision Programs',['../df/dff/group__cvv.html',1,'']]],
  ['for_20lines_20extracted_20from_20an_20image_35',['Binary descriptors for lines extracted from an image',['../dc/ddd/group__line__descriptor.html',1,'']]],
  ['for_20mat_20data_36',['Plot function for Mat data',['../db/dfe/group__plot.html',1,'']]],
  ['for_20new_20layers_20registration_37',['Utilities for New Layers Registration',['../df/dc1/group__dnnLayerFactory.html',1,'']]],
  ['for_20object_20detection_38',['for object detection',['../de/d37/group__objdetect__cascade__classifier.html',1,'Cascade Classifier for Object Detection'],['../d5/df6/group__dnn__objdetect.html',1,'DNN used for object detection']]],
  ['for_20opencv_39',['Julia bindings for OpenCV',['../d7/d44/group__julia.html',1,'']]],
  ['for_20opencv_20samples_40',['Utility functions for OpenCV samples',['../d6/dba/group__core__utils__samples.html',1,'']]],
  ['for_20robust_20camera_20pose_20estimation_41',['ArUco markers and boards detection for robust camera pose estimation',['../de/d67/group__objdetect__aruco.html',1,'']]],
  ['for_20super_20resolution_42',['DNN used for super resolution',['../d9/de0/group__dnn__superres.html',1,'']]],
  ['for_20video_20i_20o_43',['for video i o',['../dd/d01/group__videoio__c.html',1,'C API for video I/O'],['../d4/d15/group__videoio__flags__base.html',1,'Flags for video I/O'],['../d5/d26/group__videoio__ios.html',1,'iOS glue for video I/O'],['../dd/d01/group__videoio__winrt.html',1,'WinRT glue for video I/O']]],
  ['for_20video_20i_20o_20api_20backends_44',['Additional flags for video I/O API backends',['../dc/dfc/group__videoio__flags__others.html',1,'']]],
  ['for_20working_20with_20different_20datasets_45',['Framework for working with different datasets',['../d8/d00/group__datasets.html',1,'']]],
  ['foreground_20segmentation_20methods_46',['Improved Background-Foreground Segmentation Methods',['../d2/d55/group__bgsegm.html',1,'']]],
  ['forests_20for_20fast_20edge_20detection_47',['Structured forests for fast edge detection',['../de/d51/group__ximgproc__edge.html',1,'']]],
  ['format_20i_20o_20routines_48',['Hierarchical Data Format I/O routines',['../db/d77/group__hdf.html',1,'']]],
  ['format_20version_205_49',['Hierarchical Data Format version 5',['../d6/dee/group__hdf5.html',1,'']]],
  ['fourier_20descriptors_50',['Fourier descriptors',['../dd/ddc/group__ximgproc__fourier.html',1,'']]],
  ['framework_51',['framework',['../da/d9b/group__features2d.html',1,'2D Features Framework'],['../d1/db4/group__xfeatures2d.html',1,'Extra 2D Features Framework'],['../d9/da6/group__gapi__ref.html',1,'G-API framework']]],
  ['framework_20for_20working_20with_20different_20datasets_52',['Framework for working with different datasets',['../d8/d00/group__datasets.html',1,'']]],
  ['free_202d_20features_20algorithms_53',['Non-free 2D Features Algorithms',['../d2/dca/group__xfeatures2d__nonfree.html',1,'']]],
  ['freetype_20harfbuzz_54',['Drawing UTF-8 strings with freetype/harfbuzz',['../d4/dfc/group__freetype.html',1,'']]],
  ['from_20an_20image_55',['Binary descriptors for lines extracted from an image',['../dc/ddd/group__line__descriptor.html',1,'']]],
  ['from_20motion_56',['Structure From Motion',['../d8/d8c/group__sfm.html',1,'']]],
  ['from_20one_20color_20space_20to_20another_57',['Graph API: Converting image from one color space to another',['../dc/d38/group__gapi__colorconvert.html',1,'']]],
  ['function_20for_20mat_20data_58',['Plot function for Mat data',['../db/dfe/group__plot.html',1,'']]],
  ['function_20of_20keypoints_20and_20matches_59',['Drawing Function of Keypoints and Matches',['../d4/d5d/group__features2d__draw.html',1,'']]],
  ['functionality_60',['functionality',['../d0/de1/group__core.html',1,'Core functionality'],['../df/d1f/group__gapi__core.html',1,'G-API Core functionality'],['../df/de4/group__gapi__draw.html',1,'G-API Drawing and composition functionality'],['../d2/d00/group__gapi__imgproc.html',1,'G-API Image processing functionality'],['../db/d06/group__gapi__serialization.html',1,'G-API Serialization functionality'],['../d4/d55/group__gapi__video.html',1,'G-API Video processing functionality']]],
  ['functionality_20was_20moved_20to_20objdetect_20module_61',['Aruco markers, module functionality was moved to objdetect module',['../d9/d6a/group__aruco.html',1,'']]],
  ['functions_62',['functions',['../d6/d6e/group__imgproc__draw.html',1,'Drawing Functions'],['../d0/d43/group__gapi__draw__api.html',1,'Drawing operations and functions'],['../d5/df1/group__imgproc__hal__functions.html',1,'Functions'],['../d3/ddd/group__core__hal__functions.html',1,'Functions'],['../d6/d91/group__gapi__transform.html',1,'Graph API: Image and channel composition functions'],['../dc/d46/group__highgui__qt.html',1,'Qt New Functions']]],
  ['functions_20and_20classes_63',['Common functions and classes',['../de/de1/group__objdetect__common.html',1,'']]],
  ['functions_20and_20macros_64',['Utility and system functions and macros',['../db/de0/group__core__utils.html',1,'']]],
  ['functions_20for_20opencv_20samples_65',['Utility functions for OpenCV samples',['../d6/dba/group__core__utils__samples.html',1,'']]],
  ['fundamental_66',['Fundamental',['../d7/d15/group__fundamental.html',1,'']]],
  ['fuzzy_20image_20processing_67',['Fuzzy image processing',['../d1/dfc/group__f__image.html',1,'']]],
  ['fuzzy_20mathematics_68',['Image processing based on fuzzy mathematics',['../df/d5b/group__fuzzy.html',1,'']]]
];
