var searchData=
[
  ['saliency_20api_0',['Saliency API',['../d8/d65/group__saliency.html',1,'']]],
  ['samples_1',['Utility functions for OpenCV samples',['../d6/dba/group__core__utils__samples.html',1,'']]],
  ['scene_20text_20detection_2',['Scene Text Detection',['../da/d56/group__text__detect.html',1,'']]],
  ['scene_20text_20detection_20and_20recognition_3',['Scene Text Detection and Recognition',['../d4/d61/group__text.html',1,'']]],
  ['scene_20text_20recognition_4',['Scene Text Recognition',['../d8/df2/group__text__recognize.html',1,'']]],
  ['seam_20estimation_5',['Seam Estimation',['../d9/d24/group__stitching__seam.html',1,'']]],
  ['seamless_20cloning_6',['Seamless Cloning',['../df/da0/group__photo__clone.html',1,'']]],
  ['search_20in_20multi_20dimensional_20spaces_7',['Clustering and Search in Multi-Dimensional Spaces',['../dc/de5/group__flann.html',1,'']]],
  ['segmentation_8',['segmentation',['../d6/d17/group__cudabgsegm.html',1,'Background Segmentation'],['../dc/d29/group__hfs.html',1,'Hierarchical Feature Selection for Efficient Image Segmentation'],['../d3/d2d/group__datasets__is.html',1,'Image Segmentation'],['../d5/df0/group__ximgproc__segmentation.html',1,'Image segmentation'],['../d3/d47/group__imgproc__segmentation.html',1,'Image Segmentation']]],
  ['segmentation_20methods_9',['Improved Background-Foreground Segmentation Methods',['../d2/d55/group__bgsegm.html',1,'']]],
  ['selection_20for_20efficient_20image_20segmentation_10',['Hierarchical Feature Selection for Efficient Image Segmentation',['../dc/d29/group__hfs.html',1,'']]],
  ['serialization_20functionality_11',['G-API Serialization functionality',['../db/d06/group__gapi__serialization.html',1,'']]],
  ['shape_20descriptors_12',['shape descriptors',['../d3/d01/group__gapi__shape.html',1,'Graph API: Image Structural Analysis and Shape Descriptors'],['../d3/dc0/group__imgproc__shape.html',1,'Structural Analysis and Shape Descriptors'],['../d4/de0/group__cudaimgproc__shape.html',1,'Structural Analysis and Shape Descriptors']]],
  ['shape_20distance_20and_20matching_13',['Shape Distance and Matching',['../d1/d85/group__shape.html',1,'']]],
  ['signal_20processing_14',['signal processing',['../de/d25/group__npps.html',1,'NPPST Signal Processing'],['../d2/d1f/group__signal.html',1,'Signal Processing']]],
  ['silhouette_20based_203d_20object_20tracking_15',['silhouette based 3D object tracking',['../d4/dc4/group__rapid.html',1,'']]],
  ['simple_20pipeline_16',['Simple Pipeline',['../d7/de2/group__simple__pipeline.html',1,'']]],
  ['singular_20value_20matrix_20decomposition_17',['Singular value matrix decomposition',['../dd/d2a/group__core__hal__interface__decomp__svd.html',1,'']]],
  ['slam_18',['SLAM',['../dc/dfb/group__datasets__slam.html',1,'']]],
  ['softfloat_20support_19',['Softfloat support',['../d7/dcc/group__core__utils__softfloat.html',1,'']]],
  ['space_20conversions_20',['Color Space Conversions',['../d8/d01/group__imgproc__color__conversions.html',1,'']]],
  ['space_20processing_21',['Color space processing',['../db/d8c/group__cudaimgproc__color.html',1,'']]],
  ['space_20to_20another_22',['Graph API: Converting image from one color space to another',['../dc/d38/group__gapi__colorconvert.html',1,'']]],
  ['spaces_23',['Clustering and Search in Multi-Dimensional Spaces',['../dc/de5/group__flann.html',1,'']]],
  ['split_24',['Channel split',['../df/df2/group__core__hal__interface__split.html',1,'']]],
  ['square_20root_20calculation_25',['square root calculation',['../d0/d5d/group__core__hal__interface__invSqrt.html',1,'Inverse square root calculation'],['../d5/dc3/group__core__hal__interface__sqrt.html',1,'Square root calculation']]],
  ['sse_20utilities_26',['SSE utilities',['../d6/d06/group__core__utils__sse.html',1,'']]],
  ['stabilization_27',['Video Stabilization',['../d5/d50/group__videostab.html',1,'']]],
  ['standard_20backends_28',['G-API Standard Backends',['../dc/d1c/group__gapi__std__backends.html',1,'']]],
  ['stereo_20correspondance_20algorithms_29',['Stereo Correspondance Algorithms',['../dd/d86/group__stereo.html',1,'']]],
  ['stereo_20correspondence_30',['Stereo Correspondence',['../dd/d47/group__cudastereo.html',1,'']]],
  ['stereo_20matching_31',['Multiview Stereo Matching',['../d7/dd5/group__datasets__msm.html',1,'']]],
  ['stitching_32',['Images stitching',['../d1/d46/group__stitching.html',1,'']]],
  ['strings_20with_20freetype_20harfbuzz_33',['Drawing UTF-8 strings with freetype/harfbuzz',['../d4/dfc/group__freetype.html',1,'']]],
  ['structural_20analysis_20and_20shape_20descriptors_34',['structural analysis and shape descriptors',['../d3/d01/group__gapi__shape.html',1,'Graph API: Image Structural Analysis and Shape Descriptors'],['../d3/dc0/group__imgproc__shape.html',1,'Structural Analysis and Shape Descriptors'],['../d4/de0/group__cudaimgproc__shape.html',1,'Structural Analysis and Shape Descriptors']]],
  ['structure_20from_20motion_35',['Structure From Motion',['../d8/d8c/group__sfm.html',1,'']]],
  ['structured_20forests_20for_20fast_20edge_20detection_36',['Structured forests for fast edge detection',['../de/d51/group__ximgproc__edge.html',1,'']]],
  ['structured_20light_20api_37',['Structured Light API',['../d1/d90/group__structured__light.html',1,'']]],
  ['structures_38',['structures',['../dc/d84/group__core__basic.html',1,'Basic structures'],['../d9/d41/group__cudacore__struct.html',1,'Data Structures'],['../d5/dbc/group__cann__struct.html',1,'Data Structures']]],
  ['subdivision_39',['Planar Subdivision',['../df/d5b/group__imgproc__subdiv2d.html',1,'']]],
  ['subtract_40',['Element-wise add and subtract',['../d8/d6f/group__core__hal__interface__addsub.html',1,'']]],
  ['sum_41',['Element-wise weighted sum',['../da/d9b/group__core__hal__interface__addWeighted.html',1,'']]],
  ['super_20resolution_42',['super resolution',['../d9/de0/group__dnn__superres.html',1,'DNN used for super resolution'],['../d7/d0a/group__superres.html',1,'Super Resolution'],['../d1/d5b/group__datasets__sr.html',1,'Super Resolution']]],
  ['superpixels_43',['Superpixels',['../df/d6c/group__ximgproc__superpixel.html',1,'']]],
  ['support_44',['support',['../d0/daf/group__core__eigen.html',1,'Eigen support'],['../d5/dc3/group__cudalegacy.html',1,'Legacy support'],['../d5/d8e/group__f0__math.html',1,'Math with F0-transform support'],['../d6/df0/group__f1__math.html',1,'Math with F1-transform support'],['../dc/d83/group__core__opencl.html',1,'OpenCL support'],['../df/d24/group__highgui__opengl.html',1,'OpenGL support'],['../d7/dcc/group__core__utils__softfloat.html',1,'Softfloat support'],['../d6/d2f/group__highgui__winrt.html',1,'WinRT support']]],
  ['surface_20matching_45',['Surface Matching',['../d9/d25/group__surface__matching.html',1,'']]],
  ['system_20functions_20and_20macros_46',['Utility and system functions and macros',['../db/de0/group__core__utils.html',1,'']]]
];
