var searchData=
[
  ['absolute_20difference_0',['Element-wise absolute difference',['../d5/dec/group__core__hal__interface__absdiff.html',1,'']]],
  ['accelerated_20computer_20vision_1',['accelerated computer vision',['../d6/df4/group__cannops.html',1,'Ascend-accelerated Computer Vision'],['../d1/d1e/group__cuda.html',1,'CUDA-accelerated Computer Vision']]],
  ['accelerated_20video_20decoding_20and_20encoding_2',['Hardware-accelerated video decoding and encoding',['../db/dc4/group__videoio__hwaccel.html',1,'']]],
  ['acceleration_20layer_3',['acceleration layer',['../d8/d45/group__feature2d__hal.html',1,'Hardware Acceleration Layer'],['../de/d85/group__core__hal.html',1,'Hardware Acceleration Layer'],['../d3/df3/group__imgproc__hal.html',1,'Hardware Acceleration Layer']]],
  ['action_20recognition_4',['Action Recognition',['../d4/d8b/group__datasets__ar.html',1,'']]],
  ['add_20and_20subtract_5',['Element-wise add and subtract',['../d8/d6f/group__core__hal__interface__addsub.html',1,'']]],
  ['additional_20flags_20for_20video_20i_20o_20api_20backends_6',['Additional flags for video I/O API backends',['../dc/dfc/group__videoio__flags__others.html',1,'']]],
  ['additional_20photo_20processing_20algorithms_7',['Additional photo processing algorithms',['../de/daa/group__xphoto.html',1,'']]],
  ['adjust_20image_20contrast_8',['The module brings implementations of intensity transformation algorithms to adjust image contrast.',['../dc/dfe/group__intensity__transform.html',1,'']]],
  ['algorithm_9',['Experimental 2D Features Matching Algorithm',['../db/dd9/group__xfeatures2d__match.html',1,'']]],
  ['algorithms_10',['algorithms',['../de/daa/group__xphoto.html',1,'Additional photo processing algorithms'],['../d7/d7a/group__xfeatures2d__experiment.html',1,'Experimental 2D Features Algorithms'],['../d2/dca/group__xfeatures2d__nonfree.html',1,'Non-free 2D Features Algorithms'],['../d2/d84/group__optflow.html',1,'Optical Flow Algorithms'],['../da/d01/group__core__optim.html',1,'Optimization Algorithms'],['../dd/d86/group__stereo.html',1,'Stereo Correspondance Algorithms'],['../d4/d93/group__img__hash.html',1,'The module brings implementations of different image hashing algorithms.']]],
  ['algorithms_20to_20adjust_20image_20contrast_11',['The module brings implementations of intensity transformation algorithms to adjust image contrast.',['../dc/dfe/group__intensity__transform.html',1,'']]],
  ['alpha_20matting_12',['Alpha Matting',['../d4/d40/group__alphamat.html',1,'']]],
  ['an_20image_13',['Binary descriptors for lines extracted from an image',['../dc/ddd/group__line__descriptor.html',1,'']]],
  ['analysis_14',['analysis',['../db/d7c/group__face.html',1,'Face Analysis'],['../de/de1/group__video__motion.html',1,'Motion Analysis'],['../d7/de9/group__video.html',1,'Video Analysis']]],
  ['analysis_20and_20object_20tracking_15',['Motion Analysis and Object Tracking',['../d7/df3/group__imgproc__motion.html',1,'']]],
  ['analysis_20and_20shape_20descriptors_16',['analysis and shape descriptors',['../d3/d01/group__gapi__shape.html',1,'Graph API: Image Structural Analysis and Shape Descriptors'],['../d4/de0/group__cudaimgproc__shape.html',1,'Structural Analysis and Shape Descriptors'],['../d3/dc0/group__imgproc__shape.html',1,'Structural Analysis and Shape Descriptors']]],
  ['analysis_20iqa_20api_17',['Image Quality Analysis (IQA) API',['../dc/d20/group__quality.html',1,'']]],
  ['and_203d_20reconstruction_18',['Camera Calibration and 3D Reconstruction',['../d9/d0c/group__calib3d.html',1,'']]],
  ['and_20boards_20detection_20for_20robust_20camera_20pose_20estimation_19',['ArUco markers and boards detection for robust camera pose estimation',['../de/d67/group__objdetect__aruco.html',1,'']]],
  ['and_20channel_20composition_20functions_20',['Graph API: Image and channel composition functions',['../d6/d91/group__gapi__transform.html',1,'']]],
  ['and_20classes_21',['Common functions and classes',['../de/de1/group__objdetect__common.html',1,'']]],
  ['and_20composition_20functionality_22',['G-API Drawing and composition functionality',['../df/de4/group__gapi__draw.html',1,'']]],
  ['and_20decoding_23',['Barcode detection and decoding',['../d7/d2a/group__objdetect__barcode.html',1,'']]],
  ['and_20derivated_20tools_24',['Biologically inspired vision models and derivated tools',['../dd/deb/group__bioinspired.html',1,'']]],
  ['and_20description_25',['and description',['../d5/d51/group__features2d__main.html',1,'Feature Detection and Description'],['../d6/d1d/group__cudafeatures2d.html',1,'Feature Detection and Description']]],
  ['and_20encoding_26',['and encoding',['../db/dc4/group__videoio__hwaccel.html',1,'Hardware-accelerated video decoding and encoding'],['../df/d77/group__objdetect__qrcode.html',1,'QRCode detection and encoding']]],
  ['and_20functions_27',['Drawing operations and functions',['../d0/d43/group__gapi__draw__api.html',1,'']]],
  ['and_20images_20matching_28',['Features Finding and Images Matching',['../df/d8c/group__stitching__match.html',1,'']]],
  ['and_20information_29',['and information',['../d2/de9/group__cann__init.html',1,'Initialization and Information'],['../d8/d40/group__cudacore__init.html',1,'Initialization and Information']]],
  ['and_20manipulating_20highgui_20windows_20and_20mouse_20events_30',['Flags related creating and manipulating HighGUI windows and mouse events',['../d0/d90/group__highgui__window__flags.html',1,'']]],
  ['and_20matches_31',['Drawing Function of Keypoints and Matches',['../d4/d5d/group__features2d__draw.html',1,'']]],
  ['and_20matching_32',['Shape Distance and Matching',['../d1/d85/group__shape.html',1,'']]],
  ['and_20object_20detector_33',['HOG (Histogram of Oriented Gradients) descriptor and object detector',['../d4/d11/group__objdetect__hog.html',1,'']]],
  ['and_20object_20tracking_34',['Motion Analysis and Object Tracking',['../d7/df3/group__imgproc__motion.html',1,'']]],
  ['and_20parsing_20qr_20code_35',['WeChat QR code detector for detecting and parsing QR code.',['../dd/d63/group__wechat__qrcode.html',1,'']]],
  ['and_20recognition_36',['and recognition',['../db/d11/group__objdetect__dnn__face.html',1,'DNN-based face detection and recognition'],['../d4/d61/group__text.html',1,'Scene Text Detection and Recognition']]],
  ['and_20search_20in_20multi_20dimensional_20spaces_37',['Clustering and Search in Multi-Dimensional Spaces',['../dc/de5/group__flann.html',1,'']]],
  ['and_20shape_20descriptors_38',['and shape descriptors',['../d3/d01/group__gapi__shape.html',1,'Graph API: Image Structural Analysis and Shape Descriptors'],['../d4/de0/group__cudaimgproc__shape.html',1,'Structural Analysis and Shape Descriptors'],['../d3/dc0/group__imgproc__shape.html',1,'Structural Analysis and Shape Descriptors']]],
  ['and_20subtract_39',['Element-wise add and subtract',['../d8/d6f/group__core__hal__interface__addsub.html',1,'']]],
  ['and_20system_20functions_20and_20macros_40',['Utility and system functions and macros',['../db/de0/group__core__utils.html',1,'']]],
  ['and_20writing_41',['and writing',['../d8/d6a/group__imgcodecs__flags.html',1,'Flags used for image file reading and writing'],['../d4/da8/group__imgcodecs.html',1,'Image file reading and writing']]],
  ['another_42',['Graph API: Converting image from one color space to another',['../dc/d38/group__gapi__colorconvert.html',1,'']]],
  ['api_43',['api',['../da/d57/group__core__async.html',1,'Asynchronous API'],['../dc/d20/group__quality.html',1,'Image Quality Analysis (IQA) API'],['../dc/d6b/group__tracking__legacy.html',1,'Legacy Tracking API'],['../de/d55/group__core__parallel__backend.html',1,'Parallel backends API'],['../df/d3a/group__phase__unwrapping.html',1,'Phase Unwrapping API'],['../d8/d65/group__saliency.html',1,'Saliency API'],['../d1/d90/group__structured__light.html',1,'Structured Light API'],['../d9/df8/group__tracking.html',1,'Tracking API']]],
  ['api_20backends_44',['Additional flags for video I/O API backends',['../dc/dfc/group__videoio__flags__others.html',1,'']]],
  ['api_20backends_20registry_45',['Query I/O API backends registry',['../de/db1/group__videoio__registry.html',1,'']]],
  ['api_20core_20functionality_46',['G-API Core functionality',['../df/d1f/group__gapi__core.html',1,'']]],
  ['api_20data_20types_47',['G-API Data Types',['../db/df1/group__gapi__data__objects.html',1,'']]],
  ['api_20drawing_20and_20composition_20functionality_48',['G-API Drawing and composition functionality',['../df/de4/group__gapi__draw.html',1,'']]],
  ['api_20for_20external_20libraries_20plugins_49',['Low-level API for external libraries / plugins',['../da/dd2/group__core__lowlevel__api.html',1,'']]],
  ['api_20for_20video_20i_20o_50',['C API for video I/O',['../dd/d01/group__videoio__c.html',1,'']]],
  ['api_20framework_51',['G-API framework',['../d9/da6/group__gapi__ref.html',1,'']]],
  ['api_20graph_20compilation_20arguments_52',['G-API Graph Compilation Arguments',['../d9/d29/group__gapi__compile__args.html',1,'']]],
  ['api_20image_20processing_20functionality_53',['G-API Image processing functionality',['../d2/d00/group__gapi__imgproc.html',1,'']]],
  ['api_20implementation_20details_54',['Tracking API implementation details',['../d5/d0b/group__tracking__detail.html',1,'']]],
  ['api_20main_20classes_55',['G-API Main Classes',['../d8/dd0/group__gapi__main__classes.html',1,'']]],
  ['api_20metadata_20descriptors_56',['G-API Metadata Descriptors',['../d3/d0c/group__gapi__meta__args.html',1,'']]],
  ['api_20opencl_20cl_20va_20interoperability_57',['Intel VA-API/OpenCL (CL-VA) interoperability',['../d1/daa/group__core__va__intel.html',1,'']]],
  ['api_20serialization_20functionality_58',['G-API Serialization functionality',['../db/d06/group__gapi__serialization.html',1,'']]],
  ['api_20standard_20backends_59',['G-API Standard Backends',['../dc/d1c/group__gapi__std__backends.html',1,'']]],
  ['api_20video_20processing_20functionality_60',['G-API Video processing functionality',['../d4/d55/group__gapi__video.html',1,'']]],
  ['api_3a_20converting_20image_20from_20one_20color_20space_20to_20another_61',['Graph API: Converting image from one color space to another',['../dc/d38/group__gapi__colorconvert.html',1,'']]],
  ['api_3a_20image_20and_20channel_20composition_20functions_62',['Graph API: Image and channel composition functions',['../d6/d91/group__gapi__transform.html',1,'']]],
  ['api_3a_20image_20feature_20detection_63',['Graph API: Image Feature Detection',['../d5/def/group__gapi__feature.html',1,'']]],
  ['api_3a_20image_20filters_64',['Graph API: Image filters',['../da/dc5/group__gapi__filters.html',1,'']]],
  ['api_3a_20image_20structural_20analysis_20and_20shape_20descriptors_65',['Graph API: Image Structural Analysis and Shape Descriptors',['../d3/d01/group__gapi__shape.html',1,'']]],
  ['api_3a_20math_20operations_66',['Graph API: Math operations',['../da/dd3/group__gapi__math.html',1,'']]],
  ['api_3a_20operations_20on_20matrices_67',['Graph API: Operations on matrices',['../d0/d86/group__gapi__matrixop.html',1,'']]],
  ['api_3a_20pixelwise_20operations_68',['Graph API: Pixelwise operations',['../d1/db2/group__gapi__pixelwise.html',1,'']]],
  ['arguments_69',['G-API Graph Compilation Arguments',['../d9/d29/group__gapi__compile__args.html',1,'']]],
  ['arithm_20operations_20on_20matrices_70',['Arithm Operations on Matrices',['../d9/d88/group__cudaarithm__arithm.html',1,'']]],
  ['arrays_71',['Operations on arrays',['../d2/de8/group__core__array.html',1,'']]],
  ['aruco_20markers_20and_20boards_20detection_20for_20robust_20camera_20pose_20estimation_72',['ArUco markers and boards detection for robust camera pose estimation',['../de/d67/group__objdetect__aruco.html',1,'']]],
  ['aruco_20markers_20module_20functionality_20was_20moved_20to_20objdetect_20module_73',['Aruco markers, module functionality was moved to objdetect module',['../d9/d6a/group__aruco.html',1,'']]],
  ['ascend_20accelerated_20computer_20vision_74',['Ascend-accelerated Computer Vision',['../d6/df4/group__cannops.html',1,'']]],
  ['ascend_20backend_75',['Operations for Ascend Backend.',['../df/d88/group__cannops__ops.html',1,'']]],
  ['asynchronous_20api_76',['Asynchronous API',['../da/d57/group__core__async.html',1,'']]],
  ['asynchronous_20c_20c_20converters_77',['Intel IPP Asynchronous C/C++ Converters',['../d6/dcf/group__core__ipp.html',1,'']]],
  ['atan_20calculation_78',['Atan calculation',['../d5/df4/group__core__hal__interface__fastAtan.html',1,'']]],
  ['autocalibration_79',['Autocalibration',['../d4/dbc/group__stitching__autocalib.html',1,'']]]
];
