var searchData=
[
  ['i_20o_0',['i o',['../dd/d01/group__videoio__c.html',1,'C API for video I/O'],['../d4/d15/group__videoio__flags__base.html',1,'Flags for video I/O'],['../d5/d26/group__videoio__ios.html',1,'iOS glue for video I/O'],['../dd/de7/group__videoio.html',1,'Video I/O'],['../dd/d01/group__videoio__winrt.html',1,'WinRT glue for video I/O']]],
  ['i_20o_20api_20backends_1',['Additional flags for video I/O API backends',['../dc/dfc/group__videoio__flags__others.html',1,'']]],
  ['i_20o_20api_20backends_20registry_2',['Query I/O API backends registry',['../de/db1/group__videoio__registry.html',1,'']]],
  ['i_20o_20routines_3',['Hierarchical Data Format I/O routines',['../db/d77/group__hdf.html',1,'']]],
  ['image_4',['image',['../dc/ddd/group__line__descriptor.html',1,'Binary descriptors for lines extracted from an image'],['../df/def/group__ximgproc__run__length__morphology.html',1,'Binary morphology on run-length encoded image']]],
  ['image_20and_20channel_20composition_20functions_5',['Graph API: Image and channel composition functions',['../d6/d91/group__gapi__transform.html',1,'']]],
  ['image_20blenders_6',['Image Blenders',['../d9/d46/group__stitching__blend.html',1,'']]],
  ['image_20contrast_7',['The module brings implementations of intensity transformation algorithms to adjust image contrast.',['../dc/dfe/group__intensity__transform.html',1,'']]],
  ['image_20feature_20detection_8',['Graph API: Image Feature Detection',['../d5/def/group__gapi__feature.html',1,'']]],
  ['image_20file_20reading_20and_20writing_9',['image file reading and writing',['../d8/d6a/group__imgcodecs__flags.html',1,'Flags used for image file reading and writing'],['../d4/da8/group__imgcodecs.html',1,'Image file reading and writing']]],
  ['image_20filtering_10',['image filtering',['../dc/d66/group__cudafilters.html',1,'Image Filtering'],['../d4/d86/group__imgproc__filter.html',1,'Image Filtering']]],
  ['image_20filters_11',['Graph API: Image filters',['../da/dc5/group__gapi__filters.html',1,'']]],
  ['image_20from_20one_20color_20space_20to_20another_12',['Graph API: Converting image from one color space to another',['../dc/d38/group__gapi__colorconvert.html',1,'']]],
  ['image_20hashing_20algorithms_13',['The module brings implementations of different image hashing algorithms.',['../d4/d93/group__img__hash.html',1,'']]],
  ['image_20processing_14',['image processing',['../df/d2d/group__ximgproc.html',1,'Extended Image Processing'],['../d1/dfc/group__f__image.html',1,'Fuzzy image processing'],['../dd/d43/group__cannimgproc.html',1,'Image Processing'],['../d7/dbd/group__imgproc.html',1,'Image Processing'],['../d0/d05/group__cudaimgproc.html',1,'Image Processing'],['../d1/d0d/group__nppi.html',1,'NPPST Image Processing']]],
  ['image_20processing_20based_20on_20fuzzy_20mathematics_15',['Image processing based on fuzzy mathematics',['../df/d5b/group__fuzzy.html',1,'']]],
  ['image_20processing_20functionality_16',['G-API Image processing functionality',['../d2/d00/group__gapi__imgproc.html',1,'']]],
  ['image_20quality_20analysis_20iqa_20api_17',['Image Quality Analysis (IQA) API',['../dc/d20/group__quality.html',1,'']]],
  ['image_20registration_18',['image registration',['../db/d61/group__reg.html',1,'Image Registration'],['../dc/def/group__datasets__ir.html',1,'Image Registration']]],
  ['image_20segmentation_19',['image segmentation',['../dc/d29/group__hfs.html',1,'Hierarchical Feature Selection for Efficient Image Segmentation'],['../d5/df0/group__ximgproc__segmentation.html',1,'Image segmentation'],['../d3/d2d/group__datasets__is.html',1,'Image Segmentation'],['../d3/d47/group__imgproc__segmentation.html',1,'Image Segmentation']]],
  ['image_20structural_20analysis_20and_20shape_20descriptors_20',['Graph API: Image Structural Analysis and Shape Descriptors',['../d3/d01/group__gapi__shape.html',1,'']]],
  ['image_20transformations_21',['image transformations',['../da/d54/group__imgproc__transform.html',1,'Geometric Image Transformations'],['../d7/d1b/group__imgproc__misc.html',1,'Miscellaneous Image Transformations']]],
  ['image_20warping_22',['Image Warping',['../db/d29/group__cudawarping.html',1,'']]],
  ['images_20matching_23',['Features Finding and Images Matching',['../df/d8c/group__stitching__match.html',1,'']]],
  ['images_20stitching_24',['Images stitching',['../d1/d46/group__stitching.html',1,'']]],
  ['images_20warping_25',['Images Warping',['../d0/dfa/group__stitching__warp.html',1,'']]],
  ['imaging_26',['HDR imaging',['../d6/df5/group__photo__hdr.html',1,'']]],
  ['implementation_20details_27',['Tracking API implementation details',['../d5/d0b/group__tracking__detail.html',1,'']]],
  ['implementation_20helpers_28',['Private implementation helpers',['../dd/d96/group__core__hal__intrin__impl.html',1,'']]],
  ['implementations_20of_20different_20image_20hashing_20algorithms_29',['The module brings implementations of different image hashing algorithms.',['../d4/d93/group__img__hash.html',1,'']]],
  ['implementations_20of_20intensity_20transformation_20algorithms_20to_20adjust_20image_20contrast_30',['The module brings implementations of intensity transformation algorithms to adjust image contrast.',['../dc/dfe/group__intensity__transform.html',1,'']]],
  ['implemented_20layers_31',['Partial List of Implemented Layers',['../d6/d87/group__dnnLayerList.html',1,'']]],
  ['improved_20background_20foreground_20segmentation_20methods_32',['Improved Background-Foreground Segmentation Methods',['../d2/d55/group__bgsegm.html',1,'']]],
  ['in_20multi_20dimensional_20spaces_33',['Clustering and Search in Multi-Dimensional Spaces',['../dc/de5/group__flann.html',1,'']]],
  ['in_20opencv_34',['ColorMaps in OpenCV',['../d3/d50/group__imgproc__colormap.html',1,'']]],
  ['information_35',['information',['../d2/de9/group__cann__init.html',1,'Initialization and Information'],['../d8/d40/group__cudacore__init.html',1,'Initialization and Information']]],
  ['initialization_20and_20information_36',['initialization and information',['../d2/de9/group__cann__init.html',1,'Initialization and Information'],['../d8/d40/group__cudacore__init.html',1,'Initialization and Information']]],
  ['inpainting_37',['Inpainting',['../d7/d8b/group__photo__inpaint.html',1,'']]],
  ['input_20output_38',['Input/Output',['../d2/da3/group__io.html',1,'']]],
  ['inspired_20vision_20models_20and_20derivated_20tools_39',['Biologically inspired vision models and derivated tools',['../dd/deb/group__bioinspired.html',1,'']]],
  ['intel_20ipp_20asynchronous_20c_20c_20converters_40',['Intel IPP Asynchronous C/C++ Converters',['../d6/dcf/group__core__ipp.html',1,'']]],
  ['intel_20va_20api_20opencl_20cl_20va_20interoperability_41',['Intel VA-API/OpenCL (CL-VA) interoperability',['../d1/daa/group__core__va__intel.html',1,'']]],
  ['intensity_20transformation_20algorithms_20to_20adjust_20image_20contrast_42',['The module brings implementations of intensity transformation algorithms to adjust image contrast.',['../dc/dfe/group__intensity__transform.html',1,'']]],
  ['interactive_20visual_20debugging_20of_20computer_20vision_20programs_43',['GUI for Interactive Visual Debugging of Computer Vision Programs',['../df/dff/group__cvv.html',1,'']]],
  ['interface_44',['interface',['../db/d47/group__features2d__hal__interface.html',1,'Interface'],['../dd/d8b/group__imgproc__hal__interface.html',1,'Interface'],['../d1/d1b/group__core__hal__interface.html',1,'Interface']]],
  ['interoperability_45',['interoperability',['../de/dc1/group__core__directx.html',1,'DirectX interoperability'],['../d1/daa/group__core__va__intel.html',1,'Intel VA-API/OpenCL (CL-VA) interoperability'],['../d2/d3c/group__core__opengl.html',1,'OpenGL interoperability']]],
  ['intrinsics_46',['Universal intrinsics',['../df/d91/group__core__hal__intrin.html',1,'']]],
  ['inverse_20square_20root_20calculation_47',['Inverse square root calculation',['../d0/d5d/group__core__hal__interface__invSqrt.html',1,'']]],
  ['ios_20glue_48',['iOS glue',['../d2/d92/group__imgcodecs__ios.html',1,'']]],
  ['ios_20glue_20for_20video_20i_20o_49',['iOS glue for video I/O',['../d5/d26/group__videoio__ios.html',1,'']]],
  ['ipp_20asynchronous_20c_20c_20converters_50',['Intel IPP Asynchronous C/C++ Converters',['../d6/dcf/group__core__ipp.html',1,'']]],
  ['iqa_20api_51',['Image Quality Analysis (IQA) API',['../dc/d20/group__quality.html',1,'']]]
];
