var searchData=
[
  ['g_20api_20core_20functionality_0',['G-API Core functionality',['../df/d1f/group__gapi__core.html',1,'']]],
  ['g_20api_20data_20types_1',['G-API Data Types',['../db/df1/group__gapi__data__objects.html',1,'']]],
  ['g_20api_20drawing_20and_20composition_20functionality_2',['G-API Drawing and composition functionality',['../df/de4/group__gapi__draw.html',1,'']]],
  ['g_20api_20framework_3',['G-API framework',['../d9/da6/group__gapi__ref.html',1,'']]],
  ['g_20api_20graph_20compilation_20arguments_4',['G-API Graph Compilation Arguments',['../d9/d29/group__gapi__compile__args.html',1,'']]],
  ['g_20api_20image_20processing_20functionality_5',['G-API Image processing functionality',['../d2/d00/group__gapi__imgproc.html',1,'']]],
  ['g_20api_20main_20classes_6',['G-API Main Classes',['../d8/dd0/group__gapi__main__classes.html',1,'']]],
  ['g_20api_20metadata_20descriptors_7',['G-API Metadata Descriptors',['../d3/d0c/group__gapi__meta__args.html',1,'']]],
  ['g_20api_20serialization_20functionality_8',['G-API Serialization functionality',['../db/d06/group__gapi__serialization.html',1,'']]],
  ['g_20api_20standard_20backends_9',['G-API Standard Backends',['../dc/d1c/group__gapi__std__backends.html',1,'']]],
  ['g_20api_20video_20processing_20functionality_10',['G-API Video processing functionality',['../d4/d55/group__gapi__video.html',1,'']]],
  ['gapi_5fdata_5fstructures_11',['Gapi_data_structures',['../d9/d51/group__gapi__data__structures.html',1,'']]],
  ['geometric_20image_20transformations_12',['Geometric Image Transformations',['../da/d54/group__imgproc__transform.html',1,'']]],
  ['gesture_20recognition_13',['Gesture Recognition',['../d9/db7/group__datasets__gr.html',1,'']]],
  ['global_20motion_20estimation_14',['Global Motion Estimation',['../d4/d2c/group__videostab__motion.html',1,'']]],
  ['glue_15',['glue',['../d2/d92/group__imgcodecs__ios.html',1,'iOS glue'],['../dc/d7e/group__imgcodecs__macosx.html',1,'MacOS(OSX) glue']]],
  ['glue_20for_20video_20i_20o_16',['glue for video i o',['../d5/d26/group__videoio__ios.html',1,'iOS glue for video I/O'],['../dd/d01/group__videoio__winrt.html',1,'WinRT glue for video I/O']]],
  ['gradients_20descriptor_20and_20object_20detector_17',['HOG (Histogram of Oriented Gradients) descriptor and object detector',['../d4/d11/group__objdetect__hog.html',1,'']]],
  ['graph_20api_3a_20converting_20image_20from_20one_20color_20space_20to_20another_18',['Graph API: Converting image from one color space to another',['../dc/d38/group__gapi__colorconvert.html',1,'']]],
  ['graph_20api_3a_20image_20and_20channel_20composition_20functions_19',['Graph API: Image and channel composition functions',['../d6/d91/group__gapi__transform.html',1,'']]],
  ['graph_20api_3a_20image_20feature_20detection_20',['Graph API: Image Feature Detection',['../d5/def/group__gapi__feature.html',1,'']]],
  ['graph_20api_3a_20image_20filters_21',['Graph API: Image filters',['../da/dc5/group__gapi__filters.html',1,'']]],
  ['graph_20api_3a_20image_20structural_20analysis_20and_20shape_20descriptors_22',['Graph API: Image Structural Analysis and Shape Descriptors',['../d3/d01/group__gapi__shape.html',1,'']]],
  ['graph_20api_3a_20math_20operations_23',['Graph API: Math operations',['../da/dd3/group__gapi__math.html',1,'']]],
  ['graph_20api_3a_20operations_20on_20matrices_24',['Graph API: Operations on matrices',['../d0/d86/group__gapi__matrixop.html',1,'']]],
  ['graph_20api_3a_20pixelwise_20operations_25',['Graph API: Pixelwise operations',['../d1/db2/group__gapi__pixelwise.html',1,'']]],
  ['graph_20compilation_20arguments_26',['G-API Graph Compilation Arguments',['../d9/d29/group__gapi__compile__args.html',1,'']]],
  ['gui_27',['High-level GUI',['../d7/dfc/group__highgui.html',1,'']]],
  ['gui_20for_20interactive_20visual_20debugging_20of_20computer_20vision_20programs_28',['GUI for Interactive Visual Debugging of Computer Vision Programs',['../df/dff/group__cvv.html',1,'']]]
];
