var searchData=
[
  ['warping_0',['warping',['../db/d29/group__cudawarping.html',1,'Image Warping'],['../d0/dfa/group__stitching__warp.html',1,'Images Warping']]],
  ['was_20moved_20to_20objdetect_20module_1',['Aruco markers, module functionality was moved to objdetect module',['../d9/d6a/group__aruco.html',1,'']]],
  ['wechat_20qr_20code_20detector_20for_20detecting_20and_20parsing_20qr_20code_2',['WeChat QR code detector for detecting and parsing QR code.',['../dd/d63/group__wechat__qrcode.html',1,'']]],
  ['weighted_20sum_3',['Element-wise weighted sum',['../da/d9b/group__core__hal__interface__addWeighted.html',1,'']]],
  ['widget_4',['Widget',['../dc/d5c/group__viz__widget.html',1,'']]],
  ['windows_20and_20mouse_20events_5',['Flags related creating and manipulating HighGUI windows and mouse events',['../d0/d90/group__highgui__window__flags.html',1,'']]],
  ['winrt_20glue_20for_20video_20i_20o_6',['WinRT glue for video I/O',['../dd/d01/group__videoio__winrt.html',1,'']]],
  ['winrt_20support_7',['WinRT support',['../d6/d2f/group__highgui__winrt.html',1,'']]],
  ['wise_20absolute_20difference_8',['Element-wise absolute difference',['../d5/dec/group__core__hal__interface__absdiff.html',1,'']]],
  ['wise_20add_20and_20subtract_9',['Element-wise add and subtract',['../d8/d6f/group__core__hal__interface__addsub.html',1,'']]],
  ['wise_20compare_10',['Element-wise compare',['../d6/dab/group__core__hal__interface__compare.html',1,'']]],
  ['wise_20divide_11',['Element-wise divide',['../dd/d2c/group__core__hal__interface__divide.html',1,'']]],
  ['wise_20minimum_20or_20maximum_12',['Element-wise minimum or maximum',['../dc/d19/group__core__hal__interface__minmax.html',1,'']]],
  ['wise_20multiply_13',['Element-wise multiply',['../de/db7/group__core__hal__interface__multiply.html',1,'']]],
  ['wise_20reciprocial_14',['Element-wise reciprocial',['../d4/de4/group__core__hal__interface__reciprocial.html',1,'']]],
  ['wise_20weighted_20sum_15',['Element-wise weighted sum',['../da/d9b/group__core__hal__interface__addWeighted.html',1,'']]],
  ['with_20different_20datasets_16',['Framework for working with different datasets',['../d8/d00/group__datasets.html',1,'']]],
  ['with_20f0_20transform_20support_17',['Math with F0-transform support',['../d5/d8e/group__f0__math.html',1,'']]],
  ['with_20f1_20transform_20support_18',['Math with F1-transform support',['../d6/df0/group__f1__math.html',1,'']]],
  ['with_20freetype_20harfbuzz_19',['Drawing UTF-8 strings with freetype/harfbuzz',['../d4/dfc/group__freetype.html',1,'']]],
  ['working_20with_20different_20datasets_20',['Framework for working with different datasets',['../d8/d00/group__datasets.html',1,'']]],
  ['writing_21',['writing',['../d8/d6a/group__imgcodecs__flags.html',1,'Flags used for image file reading and writing'],['../d4/da8/group__imgcodecs.html',1,'Image file reading and writing']]]
];
