var searchData=
[
  ['parallel_20backends_20api_0',['Parallel backends API',['../de/d55/group__core__parallel__backend.html',1,'']]],
  ['parallel_20processing_1',['Parallel Processing',['../d3/d89/group__core__parallel.html',1,'']]],
  ['parsing_20qr_20code_2',['WeChat QR code detector for detecting and parsing QR code.',['../dd/d63/group__wechat__qrcode.html',1,'']]],
  ['part_3',['part',['../d7/d05/group__cudacore.html',1,'Core part'],['../d4/d69/group__canncore.html',1,'Core part']]],
  ['part_20based_20models_4',['Deformable Part-based Models',['../d9/d12/group__dpm.html',1,'']]],
  ['partial_20list_20of_20implemented_20layers_5',['Partial List of Implemented Layers',['../d6/d87/group__dnnLayerList.html',1,'']]],
  ['pattern_20for_203d_20reconstruction_6',['Custom Calibration Pattern for 3D reconstruction',['../d3/ddc/group__ccalib.html',1,'']]],
  ['pedestrian_20detection_7',['Pedestrian Detection',['../d8/db1/group__datasets__pd.html',1,'']]],
  ['per_20element_20operations_8',['per element operations',['../d8/d34/group__cudaarithm__elem.html',1,'Per-element Operations'],['../d5/d2b/group__cannops__elem.html',1,'Per-element Operations']]],
  ['persistence_9',['XML/YAML Persistence',['../d4/da4/group__core__xml.html',1,'']]],
  ['phase_20unwrapping_20api_10',['Phase Unwrapping API',['../df/d3a/group__phase__unwrapping.html',1,'']]],
  ['photo_20processing_20algorithms_11',['Additional photo processing algorithms',['../de/daa/group__xphoto.html',1,'']]],
  ['photography_12',['Computational Photography',['../d1/d0d/group__photo.html',1,'']]],
  ['photorealistic_20rendering_13',['Non-Photorealistic Rendering',['../df/dac/group__photo__render.html',1,'']]],
  ['pipeline_14',['Simple Pipeline',['../d7/de2/group__simple__pipeline.html',1,'']]],
  ['pixelwise_20operations_15',['Graph API: Pixelwise operations',['../d1/db2/group__gapi__pixelwise.html',1,'']]],
  ['planar_20subdivision_16',['Planar Subdivision',['../df/d5b/group__imgproc__subdiv2d.html',1,'']]],
  ['plot_20function_20for_20mat_20data_17',['Plot function for Mat data',['../db/dfe/group__plot.html',1,'']]],
  ['plugins_18',['Low-level API for external libraries / plugins',['../da/dd2/group__core__lowlevel__api.html',1,'']]],
  ['pose_20estimation_19',['pose estimation',['../de/d67/group__objdetect__aruco.html',1,'ArUco markers and boards detection for robust camera pose estimation'],['../d9/de0/group__datasets__hpe.html',1,'Human Pose Estimation']]],
  ['preserving_20decolorization_20',['Contrast Preserving Decolorization',['../d4/d32/group__photo__decolor.html',1,'']]],
  ['primitives_21',['Drawing primitives',['../de/db8/group__gapi__draw__prims.html',1,'']]],
  ['private_20implementation_20helpers_22',['Private implementation helpers',['../dd/d96/group__core__hal__intrin__impl.html',1,'']]],
  ['processing_23',['processing',['../db/d8c/group__cudaimgproc__color.html',1,'Color space processing'],['../df/d2d/group__ximgproc.html',1,'Extended Image Processing'],['../d1/dfc/group__f__image.html',1,'Fuzzy image processing'],['../d0/d05/group__cudaimgproc.html',1,'Image Processing'],['../dd/d43/group__cannimgproc.html',1,'Image Processing'],['../d7/dbd/group__imgproc.html',1,'Image Processing'],['../d1/d0d/group__nppi.html',1,'NPPST Image Processing'],['../de/d25/group__npps.html',1,'NPPST Signal Processing'],['../d3/d89/group__core__parallel.html',1,'Parallel Processing'],['../d2/d3a/group__rgbd.html',1,'RGB-Depth Processing'],['../d2/d1f/group__signal.html',1,'Signal Processing']]],
  ['processing_20algorithms_24',['Additional photo processing algorithms',['../de/daa/group__xphoto.html',1,'']]],
  ['processing_20based_20on_20fuzzy_20mathematics_25',['Image processing based on fuzzy mathematics',['../df/d5b/group__fuzzy.html',1,'']]],
  ['processing_20functionality_26',['processing functionality',['../d2/d00/group__gapi__imgproc.html',1,'G-API Image processing functionality'],['../d4/d55/group__gapi__video.html',1,'G-API Video processing functionality']]],
  ['programs_27',['GUI for Interactive Visual Debugging of Computer Vision Programs',['../df/dff/group__cvv.html',1,'']]],
  ['projection_28',['Projection',['../d0/daf/group__projection.html',1,'']]]
];
