var searchData=
[
  ['data_0',['Plot function for Mat data',['../db/dfe/group__plot.html',1,'']]],
  ['data_20format_20i_20o_20routines_1',['Hierarchical Data Format I/O routines',['../db/d77/group__hdf.html',1,'']]],
  ['data_20format_20version_205_2',['Hierarchical Data Format version 5',['../d6/dee/group__hdf5.html',1,'']]],
  ['data_20structures_3',['data structures',['../d9/d41/group__cudacore__struct.html',1,'Data Structures'],['../d5/dbc/group__cann__struct.html',1,'Data Structures']]],
  ['data_20types_4',['G-API Data Types',['../db/df1/group__gapi__data__objects.html',1,'']]],
  ['datasets_5',['Framework for working with different datasets',['../d8/d00/group__datasets.html',1,'']]],
  ['debugging_20of_20computer_20vision_20programs_6',['GUI for Interactive Visual Debugging of Computer Vision Programs',['../df/dff/group__cvv.html',1,'']]],
  ['decoding_7',['decoding',['../d7/d2a/group__objdetect__barcode.html',1,'Barcode detection and decoding'],['../d0/d61/group__cudacodec.html',1,'Video Encoding/Decoding']]],
  ['decoding_20and_20encoding_8',['Hardware-accelerated video decoding and encoding',['../db/dc4/group__videoio__hwaccel.html',1,'']]],
  ['decolorization_9',['Contrast Preserving Decolorization',['../d4/d32/group__photo__decolor.html',1,'']]],
  ['decomposition_10',['decomposition',['../d8/d0e/group__core__hal__interface__decomp__cholesky.html',1,'Cholesky matrix decomposition'],['../d5/d42/group__core__hal__interface__decomp__lu.html',1,'LU matrix decomposition'],['../db/d36/group__core__hal__interface__decomp__qr.html',1,'QR matrix decomposition'],['../dd/d2a/group__core__hal__interface__decomp__svd.html',1,'Singular value matrix decomposition']]],
  ['deep_20neural_20network_20module_11',['Deep Neural Network module',['../d6/d0f/group__dnn.html',1,'']]],
  ['deformable_20part_20based_20models_12',['Deformable Part-based Models',['../d9/d12/group__dpm.html',1,'']]],
  ['denoising_13',['Denoising',['../d1/d79/group__photo__denoise.html',1,'']]],
  ['depth_20processing_14',['RGB-Depth Processing',['../d2/d3a/group__rgbd.html',1,'']]],
  ['derivated_20tools_15',['Biologically inspired vision models and derivated tools',['../dd/deb/group__bioinspired.html',1,'']]],
  ['description_16',['description',['../d5/d51/group__features2d__main.html',1,'Feature Detection and Description'],['../d6/d1d/group__cudafeatures2d.html',1,'Feature Detection and Description']]],
  ['descriptor_20and_20object_20detector_17',['HOG (Histogram of Oriented Gradients) descriptor and object detector',['../d4/d11/group__objdetect__hog.html',1,'']]],
  ['descriptor_20matchers_18',['Descriptor Matchers',['../d8/d9b/group__features2d__match.html',1,'']]],
  ['descriptors_19',['descriptors',['../dd/ddc/group__ximgproc__fourier.html',1,'Fourier descriptors'],['../d3/d0c/group__gapi__meta__args.html',1,'G-API Metadata Descriptors'],['../d3/d01/group__gapi__shape.html',1,'Graph API: Image Structural Analysis and Shape Descriptors'],['../d4/de0/group__cudaimgproc__shape.html',1,'Structural Analysis and Shape Descriptors'],['../d3/dc0/group__imgproc__shape.html',1,'Structural Analysis and Shape Descriptors']]],
  ['descriptors_20for_20lines_20extracted_20from_20an_20image_20',['Binary descriptors for lines extracted from an image',['../dc/ddd/group__line__descriptor.html',1,'']]],
  ['details_21',['Tracking API implementation details',['../d5/d0b/group__tracking__detail.html',1,'']]],
  ['detecting_20and_20parsing_20qr_20code_22',['WeChat QR code detector for detecting and parsing QR code.',['../dd/d63/group__wechat__qrcode.html',1,'']]],
  ['detection_23',['detection',['../de/d37/group__objdetect__cascade__classifier.html',1,'Cascade Classifier for Object Detection'],['../d5/df6/group__dnn__objdetect.html',1,'DNN used for object detection'],['../d4/d54/group__xobjdetect.html',1,'Extended object detection'],['../dc/d6d/group__cudaimgproc__feature.html',1,'Feature Detection'],['../dd/d1a/group__imgproc__feature.html',1,'Feature Detection'],['../d5/def/group__gapi__feature.html',1,'Graph API: Image Feature Detection'],['../d5/d54/group__objdetect.html',1,'Object Detection'],['../df/dfb/group__imgproc__object.html',1,'Object Detection'],['../d9/d3f/group__cudaobjdetect.html',1,'Object Detection'],['../d8/db1/group__datasets__pd.html',1,'Pedestrian Detection'],['../da/d56/group__text__detect.html',1,'Scene Text Detection'],['../de/d51/group__ximgproc__edge.html',1,'Structured forests for fast edge detection']]],
  ['detection_20and_20decoding_24',['Barcode detection and decoding',['../d7/d2a/group__objdetect__barcode.html',1,'']]],
  ['detection_20and_20description_25',['detection and description',['../d6/d1d/group__cudafeatures2d.html',1,'Feature Detection and Description'],['../d5/d51/group__features2d__main.html',1,'Feature Detection and Description']]],
  ['detection_20and_20encoding_26',['QRCode detection and encoding',['../df/d77/group__objdetect__qrcode.html',1,'']]],
  ['detection_20and_20recognition_27',['detection and recognition',['../db/d11/group__objdetect__dnn__face.html',1,'DNN-based face detection and recognition'],['../d4/d61/group__text.html',1,'Scene Text Detection and Recognition']]],
  ['detection_20for_20robust_20camera_20pose_20estimation_28',['ArUco markers and boards detection for robust camera pose estimation',['../de/d67/group__objdetect__aruco.html',1,'']]],
  ['detector_29',['detector',['../df/ded/group__ximgproc__fast__line__detector.html',1,'Fast line detector'],['../d4/d11/group__objdetect__hog.html',1,'HOG (Histogram of Oriented Gradients) descriptor and object detector']]],
  ['detector_20for_20detecting_20and_20parsing_20qr_20code_30',['WeChat QR code detector for detecting and parsing QR code.',['../dd/d63/group__wechat__qrcode.html',1,'']]],
  ['device_20layer_31',['Device layer',['../df/dfc/group__cudev.html',1,'']]],
  ['difference_32',['Element-wise absolute difference',['../d5/dec/group__core__hal__interface__absdiff.html',1,'']]],
  ['different_20datasets_33',['Framework for working with different datasets',['../d8/d00/group__datasets.html',1,'']]],
  ['different_20image_20hashing_20algorithms_34',['The module brings implementations of different image hashing algorithms.',['../d4/d93/group__img__hash.html',1,'']]],
  ['dimensional_20spaces_35',['Clustering and Search in Multi-Dimensional Spaces',['../dc/de5/group__flann.html',1,'']]],
  ['directx_20interoperability_36',['DirectX interoperability',['../de/dc1/group__core__directx.html',1,'']]],
  ['distance_37',['Hamming distance',['../da/db0/group__core__hal__interface__hamming.html',1,'']]],
  ['distance_20and_20matching_38',['Shape Distance and Matching',['../d1/d85/group__shape.html',1,'']]],
  ['divide_39',['Element-wise divide',['../dd/d2c/group__core__hal__interface__divide.html',1,'']]],
  ['dnn_20based_20face_20detection_20and_20recognition_40',['DNN-based face detection and recognition',['../db/d11/group__objdetect__dnn__face.html',1,'']]],
  ['dnn_20used_20for_20object_20detection_41',['DNN used for object detection',['../d5/df6/group__dnn__objdetect.html',1,'']]],
  ['dnn_20used_20for_20super_20resolution_42',['DNN used for super resolution',['../d9/de0/group__dnn__superres.html',1,'']]],
  ['drawing_20and_20composition_20functionality_43',['G-API Drawing and composition functionality',['../df/de4/group__gapi__draw.html',1,'']]],
  ['drawing_20function_20of_20keypoints_20and_20matches_44',['Drawing Function of Keypoints and Matches',['../d4/d5d/group__features2d__draw.html',1,'']]],
  ['drawing_20functions_45',['Drawing Functions',['../d6/d6e/group__imgproc__draw.html',1,'']]],
  ['drawing_20operations_20and_20functions_46',['Drawing operations and functions',['../d0/d43/group__gapi__draw__api.html',1,'']]],
  ['drawing_20primitives_47',['Drawing primitives',['../de/db8/group__gapi__draw__prims.html',1,'']]],
  ['drawing_20utf_208_20strings_20with_20freetype_20harfbuzz_48',['Drawing UTF-8 strings with freetype/harfbuzz',['../d4/dfc/group__freetype.html',1,'']]]
];
