var searchData=
[
  ['c_20api_20for_20video_20i_20o_0',['C API for video I/O',['../dd/d01/group__videoio__c.html',1,'']]],
  ['c_20c_20converters_1',['Intel IPP Asynchronous C/C++ Converters',['../d6/dcf/group__core__ipp.html',1,'']]],
  ['calculation_2',['calculation',['../d5/df4/group__core__hal__interface__fastAtan.html',1,'Atan calculation'],['../d4/d8a/group__core__hal__interface__exp.html',1,'Exponent calculation'],['../d8/d0e/group__cudaimgproc__hist.html',1,'Histogram Calculation'],['../d0/d5d/group__core__hal__interface__invSqrt.html',1,'Inverse square root calculation'],['../d7/d99/group__core__hal__interface__magnitude.html',1,'Magnitude calculation'],['../d2/de4/group__core__hal__interface__log.html',1,'Natural logarithm calculation'],['../d5/dc3/group__core__hal__interface__sqrt.html',1,'Square root calculation']]],
  ['calib3d_5fhal_5finterface_3',['Calib3d_hal_interface',['../db/d17/group__calib3d__hal__interface.html',1,'']]],
  ['calibration_20and_203d_20reconstruction_4',['Camera Calibration and 3D Reconstruction',['../d9/d0c/group__calib3d.html',1,'']]],
  ['calibration_20pattern_20for_203d_20reconstruction_5',['Custom Calibration Pattern for 3D reconstruction',['../d3/ddc/group__ccalib.html',1,'']]],
  ['camera_20calibration_20and_203d_20reconstruction_6',['Camera Calibration and 3D Reconstruction',['../d9/d0c/group__calib3d.html',1,'']]],
  ['camera_20model_7',['Fisheye camera model',['../db/d58/group__calib3d__fisheye.html',1,'']]],
  ['camera_20pose_20estimation_8',['ArUco markers and boards detection for robust camera pose estimation',['../de/d67/group__objdetect__aruco.html',1,'']]],
  ['cascade_20classifier_20for_20object_20detection_9',['Cascade Classifier for Object Detection',['../de/d37/group__objdetect__cascade__classifier.html',1,'']]],
  ['categorization_10',['Object Categorization',['../de/d24/group__features2d__category.html',1,'']]],
  ['channel_20composition_20functions_11',['Graph API: Image and channel composition functions',['../d6/d91/group__gapi__transform.html',1,'']]],
  ['channel_20merge_12',['Channel merge',['../df/d2e/group__core__hal__interface__merge.html',1,'']]],
  ['channel_20split_13',['Channel split',['../df/df2/group__core__hal__interface__split.html',1,'']]],
  ['chart_20module_14',['Macbeth Chart module',['../dd/d19/group__mcc.html',1,'']]],
  ['cholesky_20matrix_20decomposition_15',['Cholesky matrix decomposition',['../d8/d0e/group__core__hal__interface__decomp__cholesky.html',1,'']]],
  ['cl_20va_20interoperability_16',['Intel VA-API/OpenCL (CL-VA) interoperability',['../d1/daa/group__core__va__intel.html',1,'']]],
  ['classes_17',['classes',['../de/de1/group__objdetect__common.html',1,'Common functions and classes'],['../d8/dd0/group__gapi__main__classes.html',1,'G-API Main Classes']]],
  ['classifier_20for_20object_20detection_18',['Cascade Classifier for Object Detection',['../de/d37/group__objdetect__cascade__classifier.html',1,'']]],
  ['cloning_19',['Seamless Cloning',['../df/da0/group__photo__clone.html',1,'']]],
  ['clustering_20',['Clustering',['../d5/d38/group__core__cluster.html',1,'']]],
  ['clustering_20and_20search_20in_20multi_20dimensional_20spaces_21',['Clustering and Search in Multi-Dimensional Spaces',['../dc/de5/group__flann.html',1,'']]],
  ['code_20detector_20for_20detecting_20and_20parsing_20qr_20code_22',['WeChat QR code detector for detecting and parsing QR code.',['../dd/d63/group__wechat__qrcode.html',1,'']]],
  ['color_20correction_20model_23',['Color Correction Model',['../de/df4/group__color__correction.html',1,'']]],
  ['color_20space_20conversions_24',['Color Space Conversions',['../d8/d01/group__imgproc__color__conversions.html',1,'']]],
  ['color_20space_20processing_25',['Color space processing',['../db/d8c/group__cudaimgproc__color.html',1,'']]],
  ['color_20space_20to_20another_26',['Graph API: Converting image from one color space to another',['../dc/d38/group__gapi__colorconvert.html',1,'']]],
  ['colormaps_20in_20opencv_27',['ColorMaps in OpenCV',['../d3/d50/group__imgproc__colormap.html',1,'']]],
  ['common_20functions_20and_20classes_28',['Common functions and classes',['../de/de1/group__objdetect__common.html',1,'']]],
  ['compare_29',['Element-wise compare',['../d6/dab/group__core__hal__interface__compare.html',1,'']]],
  ['compensation_30',['Exposure Compensation',['../dd/dff/group__stitching__exposure.html',1,'']]],
  ['compilation_20arguments_31',['G-API Graph Compilation Arguments',['../d9/d29/group__gapi__compile__args.html',1,'']]],
  ['composition_20functionality_32',['G-API Drawing and composition functionality',['../df/de4/group__gapi__draw.html',1,'']]],
  ['composition_20functions_33',['Graph API: Image and channel composition functions',['../d6/d91/group__gapi__transform.html',1,'']]],
  ['computational_20photography_34',['Computational Photography',['../d1/d0d/group__photo.html',1,'']]],
  ['computer_20vision_35',['computer vision',['../d6/df4/group__cannops.html',1,'Ascend-accelerated Computer Vision'],['../d1/d1e/group__cuda.html',1,'CUDA-accelerated Computer Vision']]],
  ['computer_20vision_20programs_36',['GUI for Interactive Visual Debugging of Computer Vision Programs',['../df/dff/group__cvv.html',1,'']]],
  ['conditioning_37',['Conditioning',['../da/d8b/group__conditioning.html',1,'']]],
  ['contrast_38',['The module brings implementations of intensity transformation algorithms to adjust image contrast.',['../dc/dfe/group__intensity__transform.html',1,'']]],
  ['contrast_20preserving_20decolorization_39',['Contrast Preserving Decolorization',['../d4/d32/group__photo__decolor.html',1,'']]],
  ['conversions_40',['Color Space Conversions',['../d8/d01/group__imgproc__color__conversions.html',1,'']]],
  ['converters_41',['Intel IPP Asynchronous C/C++ Converters',['../d6/dcf/group__core__ipp.html',1,'']]],
  ['converting_20image_20from_20one_20color_20space_20to_20another_42',['Graph API: Converting image from one color space to another',['../dc/d38/group__gapi__colorconvert.html',1,'']]],
  ['core_43',['NPPST Core',['../d5/ddd/group__core__npp.html',1,'']]],
  ['core_20functionality_44',['core functionality',['../d0/de1/group__core.html',1,'Core functionality'],['../df/d1f/group__gapi__core.html',1,'G-API Core functionality']]],
  ['core_20operations_20on_20matrices_45',['core operations on matrices',['../de/d09/group__cudaarithm__core.html',1,'Core Operations on Matrices'],['../dd/d0c/group__cannops__core.html',1,'Core Operations on Matrices']]],
  ['core_20part_46',['core part',['../d7/d05/group__cudacore.html',1,'Core part'],['../d4/d69/group__canncore.html',1,'Core part']]],
  ['core_5fc_47',['Core_c',['../d2/df8/group__core__c.html',1,'']]],
  ['correction_20model_48',['Color Correction Model',['../de/df4/group__color__correction.html',1,'']]],
  ['correspondance_20algorithms_49',['Stereo Correspondance Algorithms',['../dd/d86/group__stereo.html',1,'']]],
  ['correspondence_50',['Stereo Correspondence',['../dd/d47/group__cudastereo.html',1,'']]],
  ['creating_20and_20manipulating_20highgui_20windows_20and_20mouse_20events_51',['Flags related creating and manipulating HighGUI windows and mouse events',['../d0/d90/group__highgui__window__flags.html',1,'']]],
  ['cuda_20accelerated_20computer_20vision_52',['CUDA-accelerated Computer Vision',['../d1/d1e/group__cuda.html',1,'']]],
  ['custom_20calibration_20pattern_20for_203d_20reconstruction_53',['Custom Calibration Pattern for 3D reconstruction',['../d3/ddc/group__ccalib.html',1,'']]]
];
