var searchData=
[
  ['watch_3a_20viewing_20in_20memory_20images_20in_20the_20visual_20studio_20debugger_0',['Image Watch: viewing in-memory images in the Visual Studio debugger',['../d4/d14/tutorial_windows_visual_studio_image_watch.html',1,'tutorial_table_of_content_introduction']]],
  ['watershed_20algorithm_1',['watershed algorithm',['../d2/dbd/tutorial_distance_transform.html',1,'Image Segmentation with Distance Transform and Watershed Algorithm'],['../d7/d1c/tutorial_js_watershed.html',1,'Image Segmentation with Watershed Algorithm'],['../d3/db4/tutorial_py_watershed.html',1,'Image Segmentation with Watershed Algorithm']]],
  ['wayland_20highgui_20backend_20in_20ubuntu_2',['Using Wayland highgui-backend in Ubuntu',['../d9/db6/tutorial_wayland_ubuntu.html',1,'tutorial_table_of_content_app']]],
  ['white_20balance_20algorithm_3',['Training the learning-based white balance algorithm',['../dc/dcb/tutorial_xphoto_training_white_balance.html',1,'tutorial_contrib_root']]],
  ['why_20graph_20api_4',['Why Graph API?',['../d6/dc9/gapi_purposes.html',1,'gapi']]],
  ['widget_5',['Pose of a widget',['../d8/df0/tutorial_widget_pose.html',1,'tutorial_table_of_content_viz']]],
  ['widgets_6',['Creating Widgets',['../d2/d64/tutorial_creating_widgets.html',1,'tutorial_table_of_content_viz']]],
  ['windows_7',['windows',['../d5/de5/tutorial_py_setup_in_windows.html',1,'Install OpenCV-Python in Windows'],['../d3/d52/tutorial_windows_install.html',1,'Installation in Windows']]],
  ['with_20aruco_20and_20charuco_8',['Calibration with ArUco and ChArUco',['../da/d13/tutorial_aruco_calibration.html',1,'tutorial_table_of_content_objdetect']]],
  ['with_20camera_9',['with camera',['../db/d08/tutorial_js_image_classification_with_camera.html',1,'Image Classification Example with Camera'],['../d2/d14/tutorial_js_object_detection_with_camera.html',1,'Object Detection Example with Camera']]],
  ['with_20clojure_10',['Introduction to OpenCV Development with Clojure',['../d7/d1e/tutorial_clojure_dev_intro.html',1,'tutorial_table_of_content_introduction']]],
  ['with_20code_11',['Basic concepts of the homography explained with code',['../d9/dab/tutorial_homography.html',1,'tutorial_table_of_content_features2d']]],
  ['with_20cuda_12',['Building OpenCV for Tegra with CUDA',['../d6/d15/tutorial_building_tegra_cuda.html',1,'tutorial_table_of_content_introduction']]],
  ['with_20distance_20transform_20and_20watershed_20algorithm_13',['Image Segmentation with Distance Transform and Watershed Algorithm',['../d2/dbd/tutorial_distance_transform.html',1,'tutorial_table_of_content_imgproc']]],
  ['with_20eclipse_14',['Using OpenCV Java with Eclipse',['../d1/d0a/tutorial_java_eclipse.html',1,'tutorial_table_of_content_introduction']]],
  ['with_20eclipse_20plugin_20cdt_15',['Using OpenCV with Eclipse (plugin CDT)',['../d7/d16/tutorial_linux_eclipse.html',1,'tutorial_table_of_content_introduction']]],
  ['with_20flann_16',['Feature Matching with FLANN',['../d5/d6f/tutorial_feature_flann_matcher.html',1,'tutorial_table_of_content_features2d']]],
  ['with_20g_20api_17',['with g api',['../d8/d24/tutorial_gapi_interactive_face_detection.html',1,'Face analytics pipeline with G-API'],['../d4/d48/tutorial_gapi_face_beautification.html',1,'Implementing a face beautification algorithm with G-API']]],
  ['with_20gcc_20and_20cmake_18',['Using OpenCV with gcc and CMake',['../db/df5/tutorial_linux_gcc_cmake.html',1,'tutorial_table_of_content_introduction']]],
  ['with_20gdal_19',['Reading Geospatial Raster files with GDAL',['../d7/d73/tutorial_raster_io_gdal.html',1,'tutorial_table_of_content_app']]],
  ['with_20gdb_20powered_20ides_20',['Using OpenCV with gdb-powered IDEs',['../d6/d25/tutorial_linux_gdb_pretty_printer.html',1,'tutorial_table_of_content_introduction']]],
  ['with_20generalized_20ballard_20and_20guil_20hough_20transform_21',['Object detection with Generalized Ballard and Guil Hough Transform',['../da/ddc/tutorial_generalized_hough_ballard_guil.html',1,'tutorial_table_of_content_imgproc']]],
  ['with_20images_22',['with images',['../dc/d2e/tutorial_py_image_display.html',1,'Getting Started with Images'],['../db/deb/tutorial_display_image.html',1,'Getting Started with Images'],['../df/d24/tutorial_js_image_display.html',1,'Getting Started with Images'],['../d5/d98/tutorial_mat_operations.html',1,'Operations with images']]],
  ['with_20opencv_23',['with opencv',['../d5/df8/tutorial_dev_with_OCV_on_Android.html',1,'Android Development with OpenCV'],['../d4/d94/tutorial_camera_calibration.html',1,'Camera calibration With OpenCV'],['../d7/d9a/pytorch_segm_tutorial_dnn_conversion.html',1,'Conversion of PyTorch Segmentation Models and Launch with OpenCV'],['../dc/db4/tf_segm_tutorial_dnn_conversion.html',1,'Conversion of TensorFlow Segmentation Models and Launch with OpenCV'],['../d7/d9e/tutorial_video_write.html',1,'Creating a video with OpenCV'],['../da/d60/tutorial_face_main.html',1,'Face Recognition with OpenCV'],['../db/da5/tutorial_how_to_scan_images.html',1,'How to scan images, lookup tables and time measurement with OpenCV'],['../df/d61/tutorial_random_generator_and_text.html',1,'Random generator and text with OpenCV']]],
  ['with_20opencv_20and_20similarity_20measurement_24',['Video Input with OpenCV and similarity measurement',['../d5/dc4/tutorial_video_input_psnr_ssim.html',1,'tutorial_table_of_content_app']]],
  ['with_20opencv_20c_25',['Conversion of PyTorch Classification Models and Launch with OpenCV C++',['../dd/d55/pytorch_cls_c_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['with_20opencv_20inside_20the_20microsoft_20visual_20studio_26',['How to build applications with OpenCV inside the &quot;Microsoft Visual Studio&quot;',['../dd/d6e/tutorial_windows_visual_studio_opencv.html',1,'tutorial_table_of_content_introduction']]],
  ['with_20opencv_20overview_27',['Video I/O with OpenCV Overview',['../d0/da7/videoio_overview.html',1,'']]],
  ['with_20opencv_20python_28',['with opencv python',['../dc/d70/pytorch_cls_tutorial_dnn_conversion.html',1,'Conversion of PyTorch Classification Models and Launch with OpenCV Python'],['../d1/d8f/tf_cls_tutorial_dnn_conversion.html',1,'Conversion of TensorFlow Classification Models and Launch with OpenCV Python'],['../d4/d2f/tf_det_tutorial_dnn_conversion.html',1,'Conversion of TensorFlow Detection Models and Launch with OpenCV Python']]],
  ['with_20openvino_29',['OpenCV usage with OpenVINO',['../dc/dfe/tutorial_dnn_openvino.html',1,'tutorial_table_of_content_dnn']]],
  ['with_20square_20chessboard_30',['Camera calibration with square chessboard',['../dc/d43/tutorial_camera_calibration_square_chess.html',1,'tutorial_table_of_content_calib3d']]],
  ['with_20thrust_31',['Using a cv::cuda::GpuMat with thrust',['../d8/db9/tutorial_gpu_thrust_interop.html',1,'tutorial_table_of_content_gpu']]],
  ['with_20ubuntu_20debian_32',['MultiArch cross-compilation with Ubuntu/Debian',['../d3/dd9/tutorial_crosscompile_with_multiarch.html',1,'tutorial_table_of_content_introduction']]],
  ['with_20videos_33',['with videos',['../dd/d43/tutorial_py_video_display.html',1,'Getting Started with Videos'],['../dd/d00/tutorial_js_video_display.html',1,'Getting Started with Videos']]],
  ['with_20watershed_20algorithm_34',['with watershed algorithm',['../d3/db4/tutorial_py_watershed.html',1,'Image Segmentation with Watershed Algorithm'],['../d7/d1c/tutorial_js_watershed.html',1,'Image Segmentation with Watershed Algorithm']]],
  ['works_35',['How OpenCV-Python Bindings Works?',['../da/d49/tutorial_py_bindings_basics.html',1,'tutorial_py_table_of_contents_bindings']]],
  ['world_20vision_36',['Retina and real-world vision',['../d3/d86/tutorial_bioinspired_retina_model.html',1,'tutorial_table_of_content_retina']]],
  ['writing_20and_20reading_20datasets_37',['Creating, Writing and Reading Datasets',['../d4/d93/tutorial_hdf_create_read_write_datasets.html',1,'tutorial_table_of_content_hdf']]],
  ['writing_20attributes_38',['Reading and Writing Attributes',['../d5/d10/tutorial_hdf_read_write_attributes.html',1,'tutorial_table_of_content_hdf']]],
  ['writing_20documentation_20for_20opencv_39',['Writing documentation for OpenCV',['../d4/db1/tutorial_documentation.html',1,'tutorial_table_of_content_introduction']]],
  ['written_20data_20using_20knn_40',['OCR of Hand-written Data using kNN',['../d8/d4b/tutorial_py_knn_opencv.html',1,'tutorial_py_knn_index']]],
  ['written_20data_20using_20svm_41',['OCR of Hand-written Data using SVM',['../dd/d3b/tutorial_py_svm_opencv.html',1,'tutorial_py_svm_index']]]
];
