var searchData=
[
  ['haar_20cascades_0',['haar cascades',['../d2/d99/tutorial_js_face_detection.html',1,'Face Detection using Haar Cascades'],['../d7/d8b/tutorial_py_face_detection.html',1,'Face Detection using Haar Cascades']]],
  ['halide_20backend_1',['How to schedule your network for Halide backend',['../de/d5d/tutorial_dnn_halide_scheduling.html',1,'tutorial_table_of_content_dnn']]],
  ['halide_20backend_20for_20improve_20efficiency_2',['How to enable Halide backend for improve efficiency',['../de/d37/tutorial_dnn_halide.html',1,'tutorial_table_of_content_dnn']]],
  ['hand_20written_20data_20using_20knn_3',['OCR of Hand-written Data using kNN',['../d8/d4b/tutorial_py_knn_opencv.html',1,'tutorial_py_knn_index']]],
  ['hand_20written_20data_20using_20svm_4',['OCR of Hand-written Data using SVM',['../dd/d3b/tutorial_py_svm_opencv.html',1,'tutorial_py_svm_index']]],
  ['hardware_20oak_20depth_20sensors_5',['Using DepthAI Hardware / OAK depth sensors',['../df/d88/tutorial_gapi_oak_devices.html',1,'tutorial_table_of_content_gapi']]],
  ['harris_20corner_20detection_6',['Harris Corner Detection',['../dc/d0d/tutorial_py_features_harris.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['harris_20corner_20detector_7',['Harris corner detector',['../d4/d7d/tutorial_harris_detector.html',1,'tutorial_table_of_content_features2d']]],
  ['hdf_20i_20o_8',['The Hierarchical Data Format (hdf) I/O',['../d3/d00/tutorial_table_of_content_hdf.html',1,'tutorial_contrib_root']]],
  ['hdr_9',['High Dynamic Range (HDR)',['../d2/df0/tutorial_py_hdr.html',1,'tutorial_py_table_of_contents_photo']]],
  ['hello_10',['OpenCV iOS Hello',['../d7/d88/tutorial_hello.html',1,'tutorial_table_of_content_ios']]],
  ['hierarchical_20data_20format_20hdf_20i_20o_11',['The Hierarchical Data Format (hdf) I/O',['../d3/d00/tutorial_table_of_content_hdf.html',1,'tutorial_contrib_root']]],
  ['hierarchy_12',['hierarchy',['../d9/d8b/tutorial_py_contours_hierarchy.html',1,'Contours Hierarchy'],['../da/d0a/tutorial_js_contours_hierarchy.html',1,'Contours Hierarchy']]],
  ['high_20dynamic_20range_20hdr_13',['High Dynamic Range (HDR)',['../d2/df0/tutorial_py_hdr.html',1,'tutorial_py_table_of_contents_photo']]],
  ['high_20dynamic_20range_20imaging_14',['High Dynamic Range Imaging',['../d3/db7/tutorial_hdr_imaging.html',1,'tutorial_table_of_content_other']]],
  ['high_20level_20api_3a_20textdetectionmodel_20and_20textrecognitionmodel_15',['High Level API: TextDetectionModel and TextRecognitionModel',['../d4/d43/tutorial_dnn_text_spotting.html',1,'tutorial_table_of_content_dnn']]],
  ['high_20level_20design_20overview_16',['High-level design overview',['../de/d4d/gapi_hld.html',1,'gapi']]],
  ['high_20level_20gui_20and_20media_20highgui_20module_17',['High Level GUI and Media (highgui module)',['../d0/de2/tutorial_table_of_content_highgui.html',1,'']]],
  ['high_20level_20stitching_20api_20stitcher_20class_18',['High level stitching API (Stitcher class)',['../d8/d19/tutorial_stitcher.html',1,'tutorial_table_of_content_other']]],
  ['highgui_20backend_20in_20ubuntu_19',['Using Wayland highgui-backend in Ubuntu',['../d9/db6/tutorial_wayland_ubuntu.html',1,'tutorial_table_of_content_app']]],
  ['highgui_20imgcodecs_20videoio_20modules_20',['Application utils (highgui, imgcodecs, videoio modules)',['../de/d3d/tutorial_table_of_content_app.html',1,'tutorial_root']]],
  ['highgui_20module_21',['High Level GUI and Media (highgui module)',['../d0/de2/tutorial_table_of_content_highgui.html',1,'']]],
  ['histogram_22',['Creating a 3D histogram',['../d1/d1d/tutorial_histo3D.html',1,'tutorial_table_of_content_viz']]],
  ['histogram_203_20_3a_20histogram_20backprojection_23',['Histogram - 3 : Histogram Backprojection',['../dd/d4d/tutorial_js_histogram_backprojection.html',1,'tutorial_js_table_of_contents_histograms']]],
  ['histogram_204_20_3a_20histogram_20backprojection_24',['Histogram - 4 : Histogram Backprojection',['../dc/df6/tutorial_py_histogram_backprojection.html',1,'tutorial_py_table_of_contents_histograms']]],
  ['histogram_20calculation_25',['Histogram Calculation',['../d8/dbc/tutorial_histogram_calculation.html',1,'tutorial_table_of_content_imgproc']]],
  ['histogram_20comparison_26',['Histogram Comparison',['../d8/dc8/tutorial_histogram_comparison.html',1,'tutorial_table_of_content_imgproc']]],
  ['histogram_20equalization_27',['histogram equalization',['../d4/d1b/tutorial_histogram_equalization.html',1,'Histogram Equalization'],['../d2/d74/tutorial_js_histogram_equalization.html',1,'Histograms - 2: Histogram Equalization'],['../d5/daf/tutorial_py_histogram_equalization.html',1,'Histograms - 2: Histogram Equalization']]],
  ['histograms_201_20_3a_20find_20plot_20analyze_28',['histograms 1 : find plot analyze',['../d1/db7/tutorial_py_histogram_begins.html',1,'Histograms - 1 : Find, Plot, Analyze !!!'],['../d7/d32/tutorial_js_histogram_begins.html',1,'Histograms - 1 : Find, Plot, Analyze !!!']]],
  ['histograms_202_3a_20histogram_20equalization_29',['histograms 2: histogram equalization',['../d2/d74/tutorial_js_histogram_equalization.html',1,'Histograms - 2: Histogram Equalization'],['../d5/daf/tutorial_py_histogram_equalization.html',1,'Histograms - 2: Histogram Equalization']]],
  ['histograms_203_20_3a_202d_20histograms_30',['Histograms - 3 : 2D Histograms',['../dd/d0d/tutorial_py_2d_histogram.html',1,'tutorial_py_table_of_contents_histograms']]],
  ['histograms_20in_20opencv_31',['Histograms in OpenCV',['../de/db2/tutorial_py_table_of_contents_histograms.html',1,'tutorial_py_table_of_contents_imgproc']]],
  ['histograms_20in_20opencv_20js_32',['Histograms in OpenCV.js',['../d5/dc0/tutorial_js_table_of_contents_histograms.html',1,'tutorial_js_table_of_contents_imgproc']]],
  ['hit_20or_20miss_33',['Hit-or-Miss',['../db/d06/tutorial_hitOrMiss.html',1,'tutorial_table_of_content_imgproc']]],
  ['homography_20explained_20with_20code_34',['Basic concepts of the homography explained with code',['../d9/dab/tutorial_homography.html',1,'tutorial_table_of_content_features2d']]],
  ['homography_20to_20find_20a_20known_20object_35',['Features2D + Homography to find a known object',['../d7/dff/tutorial_feature_homography.html',1,'tutorial_table_of_content_features2d']]],
  ['homography_20to_20find_20objects_36',['Feature Matching + Homography to find Objects',['../d1/de0/tutorial_py_feature_homography.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['horizontal_20and_20vertical_20lines_20by_20using_20morphological_20operations_37',['Extract horizontal and vertical lines by using morphological operations',['../dd/dd7/tutorial_morph_lines_detection.html',1,'tutorial_table_of_content_imgproc']]],
  ['hough_20circle_20transform_38',['hough circle transform',['../da/d53/tutorial_py_houghcircles.html',1,'Hough Circle Transform'],['../d4/d70/tutorial_hough_circle.html',1,'Hough Circle Transform'],['../d3/de5/tutorial_js_houghcircles.html',1,'Hough Circle Transform']]],
  ['hough_20line_20transform_39',['hough line transform',['../d6/d10/tutorial_py_houghlines.html',1,'Hough Line Transform'],['../d3/de6/tutorial_js_houghlines.html',1,'Hough Line Transform'],['../d9/db0/tutorial_hough_lines.html',1,'Hough Line Transform']]],
  ['hough_20transform_40',['Object detection with Generalized Ballard and Guil Hough Transform',['../da/ddc/tutorial_generalized_hough_ballard_guil.html',1,'tutorial_table_of_content_imgproc']]],
  ['how_20opencv_20python_20bindings_20works_41',['How OpenCV-Python Bindings Works?',['../da/d49/tutorial_py_bindings_basics.html',1,'tutorial_py_table_of_contents_bindings']]],
  ['how_20to_20build_20applications_20with_20opencv_20inside_20the_20microsoft_20visual_20studio_42',['How to build applications with OpenCV inside the &quot;Microsoft Visual Studio&quot;',['../dd/d6e/tutorial_windows_visual_studio_opencv.html',1,'tutorial_table_of_content_introduction']]],
  ['how_20to_20enable_20halide_20backend_20for_20improve_20efficiency_43',['How to enable Halide backend for improve efficiency',['../de/d37/tutorial_dnn_halide.html',1,'tutorial_table_of_content_dnn']]],
  ['how_20to_20run_20custom_20ocr_20model_44',['How to run custom OCR model',['../d9/d1e/tutorial_dnn_OCR.html',1,'tutorial_table_of_content_dnn']]],
  ['how_20to_20run_20deep_20networks_20in_20browser_45',['How to run deep networks in browser',['../d5/d86/tutorial_dnn_javascript.html',1,'tutorial_table_of_content_dnn']]],
  ['how_20to_20run_20deep_20networks_20on_20android_20device_46',['How to run deep networks on Android device',['../de/dfe/tutorial_android_dnn_intro.html',1,'tutorial_table_of_content_introduction']]],
  ['how_20to_20scan_20images_20lookup_20tables_20and_20time_20measurement_20with_20opencv_47',['How to scan images, lookup tables and time measurement with OpenCV',['../db/da5/tutorial_how_to_scan_images.html',1,'tutorial_table_of_content_core']]],
  ['how_20to_20schedule_20your_20network_20for_20halide_20backend_48',['How to schedule your network for Halide backend',['../de/d5d/tutorial_dnn_halide_scheduling.html',1,'tutorial_table_of_content_dnn']]],
  ['how_20to_20use_20background_20subtraction_20methods_49',['How to Use Background Subtraction Methods',['../d1/dc5/tutorial_background_subtraction.html',1,'tutorial_table_of_content_other']]],
  ['how_20to_20use_20the_20opencv_20parallel_5ffor_5f_20to_20parallelize_20your_20code_50',['how to use the opencv parallel_for_ to parallelize your code',['../d7/dff/tutorial_how_to_use_OpenCV_parallel_for_.html',1,'How to use the OpenCV parallel_for_ to parallelize your code'],['../dc/ddf/tutorial_how_to_use_OpenCV_parallel_for_new.html',1,'How to use the OpenCV parallel_for_ to parallelize your code']]],
  ['hull_51',['Convex Hull',['../d7/d1d/tutorial_hull.html',1,'tutorial_table_of_content_imgproc']]],
  ['human_20retina_20and_20its_20use_20for_20image_20processing_52',['Discovering the human retina and its use for image processing',['../df/dee/tutorial_table_of_content_retina.html',1,'tutorial_contrib_root']]]
];
