var searchData=
[
  ['a_203d_20histogram_0',['Creating a 3D histogram',['../d1/d1d/tutorial_histo3D.html',1,'tutorial_table_of_content_viz']]],
  ['a_20cv_3a_3acuda_3a_3agpumat_20with_20thrust_1',['Using a cv::cuda::GpuMat with thrust',['../d8/db9/tutorial_gpu_thrust_interop.html',1,'tutorial_table_of_content_gpu']]],
  ['a_20face_20beautification_20algorithm_20with_20g_20api_2',['Implementing a face beautification algorithm with G-API',['../d4/d48/tutorial_gapi_face_beautification.html',1,'tutorial_table_of_content_gapi']]],
  ['a_20gradient_20structure_20tensor_3',['Anisotropic image segmentation by a gradient structure tensor',['../d4/d70/tutorial_anisotropic_image_segmentation_by_a_gst.html',1,'tutorial_table_of_content_imgproc']]],
  ['a_20known_20object_4',['Features2D + Homography to find a known object',['../d7/dff/tutorial_feature_homography.html',1,'tutorial_table_of_content_features2d']]],
  ['a_20new_20algorithm_20to_20the_20facemark_20api_5',['Adding a new algorithm to the Facemark API',['../d4/d3e/tutorial_facemark_add_algorithm.html',1,'tutorial_table_of_content_facemark']]],
  ['a_20paint_20brush_6',['Mouse as a Paint-Brush',['../db/d5b/tutorial_py_mouse_handling.html',1,'tutorial_py_table_of_contents_gui']]],
  ['a_20template_20parameter_20file_7',['Exporting a template parameter file',['../df/dc0/tutorial_qds_export_parameters.html',1,'tutorial_table_of_content_quasi_dense_stereo']]],
  ['a_20textured_20object_8',['Real Time pose estimation of a textured object',['../dc/d2c/tutorial_real_time_pose.html',1,'tutorial_table_of_content_calib3d']]],
  ['a_20trackbar_20to_20our_20applications_9',['Adding a Trackbar to our applications!',['../da/d6a/tutorial_trackbar.html',1,'tutorial_table_of_content_app']]],
  ['a_20trackbar_20to_20your_20application_10',['Add a Trackbar to Your Application',['../d5/df3/tutorial_js_trackbar.html',1,'tutorial_js_table_of_contents_gui']]],
  ['a_20video_11',['Face landmark detection in a video',['../d8/d3c/tutorial_face_landmark_detection_in_video.html',1,'tutorial_table_of_content_face']]],
  ['a_20video_20with_20opencv_12',['Creating a video with OpenCV',['../d7/d9e/tutorial_video_write.html',1,'tutorial_table_of_content_app']]],
  ['a_20widget_13',['Pose of a widget',['../d8/df0/tutorial_widget_pose.html',1,'tutorial_table_of_content_viz']]],
  ['accelerated_20computer_20vision_20cuda_20module_14',['GPU-Accelerated Computer Vision (cuda module)',['../da/d2c/tutorial_table_of_content_gpu.html',1,'tutorial_root']]],
  ['add_20a_20trackbar_20to_20your_20application_15',['Add a Trackbar to Your Application',['../d5/df3/tutorial_js_trackbar.html',1,'tutorial_js_table_of_contents_gui']]],
  ['adding_20a_20new_20algorithm_20to_20the_20facemark_20api_16',['Adding a new algorithm to the Facemark API',['../d4/d3e/tutorial_facemark_add_algorithm.html',1,'tutorial_table_of_content_facemark']]],
  ['adding_20a_20trackbar_20to_20our_20applications_17',['Adding a Trackbar to our applications!',['../da/d6a/tutorial_trackbar.html',1,'tutorial_table_of_content_app']]],
  ['adding_20blending_20two_20images_20using_20opencv_18',['Adding (blending) two images using OpenCV',['../d5/dc4/tutorial_adding_images.html',1,'tutorial_table_of_content_core']]],
  ['adding_20borders_20to_20your_20images_19',['Adding borders to your images',['../dc/da3/tutorial_copyMakeBorder.html',1,'tutorial_table_of_content_imgproc']]],
  ['affine_20transformations_20',['Affine Transformations',['../d4/d61/tutorial_warp_affine.html',1,'tutorial_table_of_content_imgproc']]],
  ['akaze_20and_20orb_20planar_20tracking_21',['AKAZE and ORB planar tracking',['../dc/d16/tutorial_akaze_tracking.html',1,'tutorial_table_of_content_features2d']]],
  ['akaze_20local_20features_20matching_22',['AKAZE local features matching',['../db/d70/tutorial_akaze_matching.html',1,'tutorial_table_of_content_features2d']]],
  ['algorithm_23',['algorithm',['../dd/dfc/tutorial_js_grabcut.html',1,'Foreground Extraction using GrabCut Algorithm'],['../d7/dbe/kinfu_icp.html',1,'ICP point-to-plane odometry algorithm'],['../d2/dbd/tutorial_distance_transform.html',1,'Image Segmentation with Distance Transform and Watershed Algorithm'],['../d3/db4/tutorial_py_watershed.html',1,'Image Segmentation with Watershed Algorithm'],['../d7/d1c/tutorial_js_watershed.html',1,'Image Segmentation with Watershed Algorithm'],['../d8/d83/tutorial_py_grabcut.html',1,'Interactive Foreground Extraction using GrabCut Algorithm'],['../dc/dcb/tutorial_xphoto_training_white_balance.html',1,'Training the learning-based white balance algorithm']]],
  ['algorithm_20for_20corner_20detection_24',['FAST Algorithm for Corner Detection',['../df/d0c/tutorial_py_fast.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['algorithm_20to_20the_20facemark_20api_25',['Adding a new algorithm to the Facemark API',['../d4/d3e/tutorial_facemark_add_algorithm.html',1,'tutorial_table_of_content_facemark']]],
  ['algorithm_20with_20g_20api_26',['Implementing a face beautification algorithm with G-API',['../d4/d48/tutorial_gapi_face_beautification.html',1,'tutorial_table_of_content_gapi']]],
  ['algorithms_27',['Detecting colorcheckers using basic algorithms',['../d9/d7e/tutorial_mcc_basic_chart_detection.html',1,'tutorial_table_of_content_mcc']]],
  ['alpha_20matting_28',['Information Flow Alpha Matting',['../dd/d0e/tutorial_alphamat.html',1,'tutorial_contrib_root']]],
  ['an_20image_29',['an image',['../d3/dc1/tutorial_basic_linear_transform.html',1,'Changing the contrast and brightness of an image!'],['../d2/d42/tutorial_face_landmark_detection_in_an_image.html',1,'Face landmark detection in an image'],['../db/d64/tutorial_load_save_image.html',1,'Load, Modify, and Save an Image']]],
  ['analysis_30',['analysis',['../d3/db0/tutorial_py_table_of_contents_video.html',1,'Video Analysis'],['../de/db6/tutorial_js_table_of_contents_video.html',1,'Video Analysis']]],
  ['analysis_20pca_31',['Introduction to Principal Component Analysis (PCA)',['../d1/dee/tutorial_introduction_to_pca.html',1,'tutorial_table_of_content_other']]],
  ['analysis_20video_20module_32',['Video analysis (video module)',['../da/dd0/tutorial_table_of_content_video.html',1,'']]],
  ['analytics_20pipeline_20with_20g_20api_33',['Face analytics pipeline with G-API',['../d8/d24/tutorial_gapi_interactive_face_detection.html',1,'tutorial_table_of_content_gapi']]],
  ['analyze_34',['analyze',['../d7/d32/tutorial_js_histogram_begins.html',1,'Histograms - 1 : Find, Plot, Analyze !!!'],['../d1/db7/tutorial_py_histogram_begins.html',1,'Histograms - 1 : Find, Plot, Analyze !!!']]],
  ['and_203d_20reconstruction_35',['Camera Calibration and 3D Reconstruction',['../d9/db7/tutorial_py_table_of_contents_calib3d.html',1,'tutorial_py_root']]],
  ['and_203d_20reconstruction_20calib3d_20module_36',['Camera calibration and 3D reconstruction (calib3d module)',['../d6/d55/tutorial_table_of_content_calib3d.html',1,'tutorial_root']]],
  ['and_20brightness_20of_20an_20image_37',['Changing the contrast and brightness of an image!',['../d3/dc1/tutorial_basic_linear_transform.html',1,'tutorial_table_of_content_core']]],
  ['and_20camshift_38',['and camshift',['../db/df8/tutorial_py_meanshift.html',1,'Meanshift and Camshift'],['../df/def/tutorial_js_meanshift.html',1,'Meanshift and Camshift'],['../d7/d00/tutorial_meanshift.html',1,'Meanshift and Camshift']]],
  ['and_20charuco_39',['Calibration with ArUco and ChArUco',['../da/d13/tutorial_aruco_calibration.html',1,'tutorial_table_of_content_objdetect']]],
  ['and_20circles_20for_20contours_40',['Creating Bounding boxes and circles for contours',['../da/d0c/tutorial_bounding_rects_circles.html',1,'tutorial_table_of_content_imgproc']]],
  ['and_20cmake_41',['Using OpenCV with gcc and CMake',['../db/df5/tutorial_linux_gcc_cmake.html',1,'tutorial_table_of_content_introduction']]],
  ['and_20cmake_20version_203_209_201_42',['Tesseract (master) installation by using git-bash (version&gt;=2.14.1) and cmake (version &gt;=3.9.1)',['../db/d4c/tutorial_install_tesseract.html',1,'tutorial_table_of_content_text']]],
  ['and_20debugging_20the_20detection_20system_43',['Customising and Debugging the detection system',['../d0/de5/tutorial_mcc_debugging_the_system.html',1,'tutorial_table_of_content_mcc']]],
  ['and_20description_44',['Feature Detection and Description',['../db/d27/tutorial_py_table_of_contents_feature2d.html',1,'tutorial_py_root']]],
  ['and_20dilating_45',['Eroding and Dilating',['../db/df6/tutorial_erosion_dilatation.html',1,'tutorial_table_of_content_imgproc']]],
  ['and_20ellipses_20for_20contours_46',['Creating Bounding rotated boxes and ellipses for contours',['../de/d62/tutorial_bounding_rotated_ellipses.html',1,'tutorial_table_of_content_imgproc']]],
  ['and_20guil_20hough_20transform_47',['Object detection with Generalized Ballard and Guil Hough Transform',['../da/ddc/tutorial_generalized_hough_ballard_guil.html',1,'tutorial_table_of_content_imgproc']]],
  ['and_20improvement_20techniques_48',['Performance Measurement and Improvement Techniques',['../dc/d71/tutorial_py_optimization.html',1,'tutorial_py_table_of_contents_core']]],
  ['and_20its_20use_20for_20image_20processing_49',['Discovering the human retina and its use for image processing',['../df/dee/tutorial_table_of_content_retina.html',1,'tutorial_contrib_root']]],
  ['and_20launch_20with_20opencv_50',['and launch with opencv',['../d7/d9a/pytorch_segm_tutorial_dnn_conversion.html',1,'Conversion of PyTorch Segmentation Models and Launch with OpenCV'],['../dc/db4/tf_segm_tutorial_dnn_conversion.html',1,'Conversion of TensorFlow Segmentation Models and Launch with OpenCV']]],
  ['and_20launch_20with_20opencv_20c_51',['Conversion of PyTorch Classification Models and Launch with OpenCV C++',['../dd/d55/pytorch_cls_c_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['and_20launch_20with_20opencv_20python_52',['and launch with opencv python',['../dc/d70/pytorch_cls_tutorial_dnn_conversion.html',1,'Conversion of PyTorch Classification Models and Launch with OpenCV Python'],['../d1/d8f/tf_cls_tutorial_dnn_conversion.html',1,'Conversion of TensorFlow Classification Models and Launch with OpenCV Python'],['../d4/d2f/tf_det_tutorial_dnn_conversion.html',1,'Conversion of TensorFlow Detection Models and Launch with OpenCV Python']]],
  ['and_20media_20highgui_20module_53',['High Level GUI and Media (highgui module)',['../d0/de2/tutorial_table_of_content_highgui.html',1,'']]],
  ['and_20orb_20planar_20tracking_54',['AKAZE and ORB planar tracking',['../dc/d16/tutorial_akaze_tracking.html',1,'tutorial_table_of_content_features2d']]],
  ['and_20other_20intel_20realsense_20sdk_20compatible_20depth_20sensors_55',['Using Creative Senz3D and other Intel RealSense SDK compatible depth sensors',['../db/d08/tutorial_intelperc.html',1,'tutorial_table_of_content_app']]],
  ['and_20other_20openni_20compatible_20depth_20sensors_56',['Using Kinect and other OpenNI compatible depth sensors',['../d7/d6f/tutorial_kinect_openni.html',1,'tutorial_table_of_content_app']]],
  ['and_20output_20imgcodecs_20module_57',['Image Input and Output (imgcodecs module)',['../da/d8f/tutorial_table_of_content_imgcodecs.html',1,'']]],
  ['and_20output_20using_20xml_20and_20yaml_20files_58',['File Input and Output using XML and YAML files',['../dd/d74/tutorial_file_input_output_with_xml_yml.html',1,'tutorial_table_of_content_core']]],
  ['and_20output_20videoio_20module_59',['Video Input and Output (videoio module)',['../df/d2c/tutorial_table_of_content_videoio.html',1,'']]],
  ['and_20reading_20datasets_60',['Creating, Writing and Reading Datasets',['../d4/d93/tutorial_hdf_create_read_write_datasets.html',1,'tutorial_table_of_content_hdf']]],
  ['and_20real_20world_20vision_61',['Retina and real-world vision',['../d3/d86/tutorial_bioinspired_retina_model.html',1,'tutorial_table_of_content_retina']]],
  ['and_20recognition_62',['DNN-based Face Detection And Recognition',['../d0/dd4/tutorial_dnn_face.html',1,'tutorial_table_of_content_dnn']]],
  ['and_20rotated_20brief_63',['ORB (Oriented FAST and Rotated BRIEF)',['../d1/d89/tutorial_py_orb.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['and_20save_20an_20image_64',['Load, Modify, and Save an Image',['../db/d64/tutorial_load_save_image.html',1,'']]],
  ['and_20similarity_20measurement_65',['Video Input with OpenCV and similarity measurement',['../d5/dc4/tutorial_video_input_psnr_ssim.html',1,'tutorial_table_of_content_app']]],
  ['and_20ssim_20on_20the_20gpu_66',['Similarity check (PNSR and SSIM) on the GPU',['../dd/d3d/tutorial_gpu_basics_similarity.html',1,'tutorial_table_of_content_gpu']]],
  ['and_20text_20with_20opencv_67',['Random generator and text with OpenCV',['../df/d61/tutorial_random_generator_and_text.html',1,'tutorial_table_of_content_imgproc']]],
  ['and_20textrecognitionmodel_68',['High Level API: TextDetectionModel and TextRecognitionModel',['../d4/d43/tutorial_dnn_text_spotting.html',1,'tutorial_table_of_content_dnn']]],
  ['and_20time_20measurement_20with_20opencv_69',['How to scan images, lookup tables and time measurement with OpenCV',['../db/da5/tutorial_how_to_scan_images.html',1,'tutorial_table_of_content_core']]],
  ['and_20tutorials_70',['Introduction to OpenCV.js and Tutorials',['../df/d0a/tutorial_js_intro.html',1,'tutorial_js_table_of_contents_setup']]],
  ['and_20vertical_20lines_20by_20using_20morphological_20operations_71',['Extract horizontal and vertical lines by using morphological operations',['../dd/dd7/tutorial_morph_lines_detection.html',1,'tutorial_table_of_content_imgproc']]],
  ['and_20watershed_20algorithm_72',['Image Segmentation with Distance Transform and Watershed Algorithm',['../d2/dbd/tutorial_distance_transform.html',1,'tutorial_table_of_content_imgproc']]],
  ['and_20writing_20attributes_73',['Reading and Writing Attributes',['../d5/d10/tutorial_hdf_read_write_attributes.html',1,'tutorial_table_of_content_hdf']]],
  ['android_20camera_20preview_20based_20cv_20application_74',['Use OpenCL in Android camera preview based CV application',['../d7/dbd/tutorial_android_ocl_intro.html',1,'tutorial_table_of_content_introduction']]],
  ['android_20development_75',['Introduction into Android Development',['../d9/d3f/tutorial_android_dev_intro.html',1,'tutorial_table_of_content_introduction']]],
  ['android_20development_20with_20opencv_76',['Android Development with OpenCV',['../d5/df8/tutorial_dev_with_OCV_on_Android.html',1,'tutorial_table_of_content_introduction']]],
  ['android_20device_77',['How to run deep networks on Android device',['../de/dfe/tutorial_android_dnn_intro.html',1,'tutorial_table_of_content_introduction']]],
  ['anisotropic_20image_20segmentation_20by_20a_20gradient_20structure_20tensor_78',['Anisotropic image segmentation by a gradient structure tensor',['../d4/d70/tutorial_anisotropic_image_segmentation_by_a_gst.html',1,'tutorial_table_of_content_imgproc']]],
  ['anisotropic_20image_20segmentation_20on_20g_20api_79',['Porting anisotropic image segmentation on G-API',['../d3/d7a/tutorial_gapi_anisotropic_segmentation.html',1,'tutorial_table_of_content_gapi']]],
  ['api_80',['api',['../d4/d3e/tutorial_facemark_add_algorithm.html',1,'Adding a new algorithm to the Facemark API'],['../d8/d24/tutorial_gapi_interactive_face_detection.html',1,'Face analytics pipeline with G-API'],['../d0/d1e/gapi.html',1,'Graph API'],['../d4/d48/tutorial_gapi_face_beautification.html',1,'Implementing a face beautification algorithm with G-API'],['../d0/d25/gapi_kernel_api.html',1,'Kernel API'],['../d3/d7a/tutorial_gapi_anisotropic_segmentation.html',1,'Porting anisotropic image segmentation on G-API'],['../d5/d47/tutorial_table_of_content_facemark.html',1,'Tutorial on Facial Landmark Detector API'],['../d7/dec/tutorial_facemark_usage.html',1,'Using the Facemark API'],['../d6/dc9/gapi_purposes.html',1,'Why Graph API?']]],
  ['api_20gapi_20module_81',['Graph API (gapi module)',['../df/d7e/tutorial_table_of_content_gapi.html',1,'tutorial_root']]],
  ['api_20overview_82',['G-API Overview',['../de/d96/md_gapi_2doc_2slides_2README.html',1,'']]],
  ['api_20stitcher_20class_83',['High level stitching API (Stitcher class)',['../d8/d19/tutorial_stitcher.html',1,'tutorial_table_of_content_other']]],
  ['api_3a_20textdetectionmodel_20and_20textrecognitionmodel_84',['High Level API: TextDetectionModel and TextRecognitionModel',['../d4/d43/tutorial_dnn_text_spotting.html',1,'tutorial_table_of_content_dnn']]],
  ['application_85',['application',['../d5/df3/tutorial_js_trackbar.html',1,'Add a Trackbar to Your Application'],['../d7/d21/tutorial_interactive_calibration.html',1,'Interactive camera calibration application'],['../d7/dbd/tutorial_android_ocl_intro.html',1,'Use OpenCL in Android camera preview based CV application']]],
  ['application_20utils_20highgui_20imgcodecs_20videoio_20modules_86',['Application utils (highgui, imgcodecs, videoio modules)',['../de/d3d/tutorial_table_of_content_app.html',1,'tutorial_root']]],
  ['applications_87',['applications',['../da/d6a/tutorial_trackbar.html',1,'Adding a Trackbar to our applications!'],['../d7/dcf/tutorial_cvv_introduction.html',1,'Interactive Visual Debugging of Computer Vision applications']]],
  ['applications_20with_20opencv_20inside_20the_20microsoft_20visual_20studio_88',['How to build applications with OpenCV inside the &quot;Microsoft Visual Studio&quot;',['../dd/d6e/tutorial_windows_visual_studio_opencv.html',1,'tutorial_table_of_content_introduction']]],
  ['arithmetic_20operations_20on_20images_89',['arithmetic operations on images',['../dd/d4d/tutorial_js_image_arithmetics.html',1,'Arithmetic Operations on Images'],['../d0/d86/tutorial_py_image_arithmetics.html',1,'Arithmetic Operations on Images']]],
  ['arm_20based_20linux_20systems_90',['Cross compilation for ARM based Linux systems',['../d0/d76/tutorial_arm_crosscompile_with_cmake.html',1,'tutorial_table_of_content_introduction']]],
  ['aruco_20and_20charuco_91',['Calibration with ArUco and ChArUco',['../da/d13/tutorial_aruco_calibration.html',1,'tutorial_table_of_content_objdetect']]],
  ['aruco_20boards_92',['Detection of ArUco boards',['../db/da9/tutorial_aruco_board_detection.html',1,'tutorial_table_of_content_objdetect']]],
  ['aruco_20markers_93',['Detection of ArUco Markers',['../d5/dae/tutorial_aruco_detection.html',1,'tutorial_table_of_content_objdetect']]],
  ['aruco_20module_20faq_94',['Aruco module FAQ',['../d1/dcb/tutorial_aruco_faq.html',1,'tutorial_table_of_content_objdetect']]],
  ['as_20a_20paint_20brush_95',['Mouse as a Paint-Brush',['../db/d5b/tutorial_py_mouse_handling.html',1,'tutorial_py_table_of_contents_gui']]],
  ['as_20the_20color_20palette_96',['Trackbar as the Color Palette',['../d9/dc8/tutorial_py_trackbar.html',1,'tutorial_py_table_of_contents_gui']]],
  ['ascend_20npu_20image_20processing_97',['Ascend NPU Image Processing',['../d9/d56/tutorial_ascend_npu_image_processing.html',1,'tutorial_contrib_root']]],
  ['asked_20questions_98',['Frequently Asked Questions',['../d3/d2d/faq.html',1,'']]],
  ['astra_203d_20cameras_99',['Using Orbbec Astra 3D cameras',['../d4/d65/tutorial_orbbec_astra.html',1,'tutorial_table_of_content_app']]],
  ['attributes_100',['Reading and Writing Attributes',['../d5/d10/tutorial_hdf_read_write_attributes.html',1,'tutorial_table_of_content_hdf']]]
];
