var searchData=
[
  ['random_20generator_20and_20text_20with_20opencv_0',['Random generator and text with OpenCV',['../df/d61/tutorial_random_generator_and_text.html',1,'tutorial_table_of_content_imgproc']]],
  ['random_20sample_20consensus_20in_20opencv_1',['USAC: Improvement of Random Sample Consensus in OpenCV',['../de/d3e/tutorial_usac.html',1,'tutorial_table_of_content_calib3d']]],
  ['range_20hdr_2',['High Dynamic Range (HDR)',['../d2/df0/tutorial_py_hdr.html',1,'tutorial_py_table_of_contents_photo']]],
  ['range_20imaging_3',['High Dynamic Range Imaging',['../d3/db7/tutorial_hdr_imaging.html',1,'tutorial_table_of_content_other']]],
  ['raster_20files_20with_20gdal_4',['Reading Geospatial Raster files with GDAL',['../d7/d73/tutorial_raster_io_gdal.html',1,'tutorial_table_of_content_app']]],
  ['reading_20and_20writing_20attributes_5',['Reading and Writing Attributes',['../d5/d10/tutorial_hdf_read_write_attributes.html',1,'tutorial_table_of_content_hdf']]],
  ['reading_20datasets_6',['Creating, Writing and Reading Datasets',['../d4/d93/tutorial_hdf_create_read_write_datasets.html',1,'tutorial_table_of_content_hdf']]],
  ['reading_20geospatial_20raster_20files_20with_20gdal_7',['Reading Geospatial Raster files with GDAL',['../d7/d73/tutorial_raster_io_gdal.html',1,'tutorial_table_of_content_app']]],
  ['real_20time_20pose_20estimation_20of_20a_20textured_20object_8',['Real Time pose estimation of a textured object',['../dc/d2c/tutorial_real_time_pose.html',1,'tutorial_table_of_content_calib3d']]],
  ['real_20world_20vision_9',['Retina and real-world vision',['../d3/d86/tutorial_bioinspired_retina_model.html',1,'tutorial_table_of_content_retina']]],
  ['realsense_20sdk_20compatible_20depth_20sensors_10',['Using Creative Senz3D and other Intel RealSense SDK compatible depth sensors',['../db/d08/tutorial_intelperc.html',1,'tutorial_table_of_content_app']]],
  ['recognition_11',['recognition',['../d6/d25/tutorial_barcode_detect_and_decode.html',1,'Barcode Recognition'],['../d0/dd4/tutorial_dnn_face.html',1,'DNN-based Face Detection And Recognition']]],
  ['recognition_20with_20opencv_12',['Face Recognition with OpenCV',['../da/d60/tutorial_face_main.html',1,'tutorial_table_of_content_face']]],
  ['reconstruction_13',['reconstruction',['../d9/db7/tutorial_py_table_of_contents_calib3d.html',1,'Camera Calibration and 3D Reconstruction'],['../de/dfd/tutorial_sfm_import_reconstruction.html',1,'Import Reconstruction'],['../d4/d18/tutorial_sfm_scene_reconstruction.html',1,'Scene Reconstruction']]],
  ['reconstruction_20calib3d_20module_14',['Camera calibration and 3D reconstruction (calib3d module)',['../d6/d55/tutorial_table_of_content_calib3d.html',1,'tutorial_root']]],
  ['reference_15',['reference',['../db/d05/tutorial_config_reference.html',1,'OpenCV configuration options reference'],['../d6/dea/tutorial_env_reference.html',1,'OpenCV environment variables reference']]],
  ['referencing_20opencv_20from_20other_20doxygen_20projects_16',['Cross referencing OpenCV from other Doxygen projects',['../d3/dff/tutorial_cross_referencing.html',1,'tutorial_table_of_content_introduction']]],
  ['remapping_17',['Remapping',['../d1/da0/tutorial_remap.html',1,'tutorial_table_of_content_imgproc']]],
  ['removing_20filter_18',['Periodic Noise Removing Filter',['../d2/d0b/tutorial_periodic_noise_removing_filter.html',1,'tutorial_table_of_content_imgproc']]],
  ['resolution_20benchmarking_19',['Super-resolution benchmarking',['../dc/d69/tutorial_dnn_superres_benchmark.html',1,'tutorial_table_of_content_dnn_superres']]],
  ['resolution_20using_20cnns_20',['Super Resolution using CNNs',['../d8/df8/tutorial_table_of_content_dnn_superres.html',1,'tutorial_contrib_root']]],
  ['retina_20and_20its_20use_20for_20image_20processing_21',['Discovering the human retina and its use for image processing',['../df/dee/tutorial_table_of_content_retina.html',1,'tutorial_contrib_root']]],
  ['retina_20and_20real_20world_20vision_22',['Retina and real-world vision',['../d3/d86/tutorial_bioinspired_retina_model.html',1,'tutorial_table_of_content_retina']]],
  ['retina_20introduction_23',['Bioinspired Module Retina Introduction',['../d2/d94/bioinspired_retina.html',1,'']]],
  ['robust_20features_24',['Introduction to SURF (Speeded-Up Robust Features)',['../df/dd2/tutorial_py_surf_intro.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['robust_20independent_20elementary_20features_25',['BRIEF (Binary Robust Independent Elementary Features)',['../dc/d7d/tutorial_py_brief.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['rotated_20boxes_20and_20ellipses_20for_20contours_26',['Creating Bounding rotated boxes and ellipses for contours',['../de/d62/tutorial_bounding_rotated_ellipses.html',1,'tutorial_table_of_content_imgproc']]],
  ['rotated_20brief_27',['ORB (Oriented FAST and Rotated BRIEF)',['../d1/d89/tutorial_py_orb.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['run_20custom_20ocr_20model_28',['How to run custom OCR model',['../d9/d1e/tutorial_dnn_OCR.html',1,'tutorial_table_of_content_dnn']]],
  ['run_20deep_20networks_20in_20browser_29',['How to run deep networks in browser',['../d5/d86/tutorial_dnn_javascript.html',1,'tutorial_table_of_content_dnn']]],
  ['run_20deep_20networks_20on_20android_20device_30',['How to run deep networks on Android device',['../de/dfe/tutorial_android_dnn_intro.html',1,'tutorial_table_of_content_introduction']]]
];
