var searchData=
[
  ['machine_20learning_0',['Machine Learning',['../d6/de2/tutorial_py_table_of_contents_ml.html',1,'tutorial_py_root']]],
  ['machine_20learning_20ml_20module_1',['Machine Learning (ml module)',['../d1/d69/tutorial_table_of_content_ml.html',1,'']]],
  ['machine_20learning_20overview_2',['Machine Learning Overview',['../dc/dd6/ml_intro.html',1,'']]],
  ['machines_3',['Introduction to Support Vector Machines',['../d1/d73/tutorial_introduction_to_svm.html',1,'tutorial_table_of_content_other']]],
  ['machines_20for_20non_20linearly_20separable_20data_4',['Support Vector Machines for Non-Linearly Separable Data',['../d0/dcc/tutorial_non_linear_svms.html',1,'tutorial_table_of_content_other']]],
  ['machines_20svm_5',['Support Vector Machines (SVM)',['../d3/d02/tutorial_py_svm_index.html',1,'tutorial_py_table_of_contents_ml']]],
  ['macos_6',['Installation in MacOS',['../d0/db2/tutorial_macos_install.html',1,'tutorial_table_of_content_introduction']]],
  ['making_20your_20own_20linear_20filters_7',['Making your own linear filters!',['../d4/dbd/tutorial_filter_2d.html',1,'tutorial_table_of_content_imgproc']]],
  ['map_20from_20stereo_20images_8',['Depth Map from Stereo Images',['../dd/d53/tutorial_py_depthmap.html',1,'tutorial_py_table_of_contents_calib3d']]],
  ['map_20post_20filtering_9',['Disparity map post-filtering',['../d3/d14/tutorial_ximgproc_disparity_filtering.html',1,'tutorial_contrib_root']]],
  ['maps_10',['Unwrap two-dimensional phase maps',['../d9/dfb/tutorial_unwrap.html',1,'tutorial_unwrap_phase_map']]],
  ['markers_11',['markers',['../d5/dae/tutorial_aruco_detection.html',1,'Detection of ArUco Markers'],['../d5/d07/tutorial_charuco_diamond_detection.html',1,'Detection of Diamond Markers']]],
  ['mask_20operations_20on_20matrices_12',['Mask operations on matrices',['../d7/d37/tutorial_mat_mask_operations.html',1,'tutorial_table_of_content_core']]],
  ['master_20installation_20by_20using_20git_20bash_20version_202_2014_201_20and_20cmake_20version_203_209_201_13',['Tesseract (master) installation by using git-bash (version&gt;=2.14.1) and cmake (version &gt;=3.9.1)',['../db/d4c/tutorial_install_tesseract.html',1,'tutorial_table_of_content_text']]],
  ['mat_20the_20basic_20image_20container_14',['Mat - The Basic Image Container',['../d6/d6d/tutorial_mat_the_basic_image_container.html',1,'tutorial_table_of_content_core']]],
  ['matching_15',['matching',['../db/d70/tutorial_akaze_matching.html',1,'AKAZE local features matching'],['../dc/dc3/tutorial_py_matcher.html',1,'Feature Matching'],['../d4/dc6/tutorial_py_template_matching.html',1,'Template Matching'],['../de/da9/tutorial_template_matching.html',1,'Template Matching'],['../d8/dd1/tutorial_js_template_matching.html',1,'Template Matching']]],
  ['matching_20homography_20to_20find_20objects_16',['Feature Matching + Homography to find Objects',['../d1/de0/tutorial_py_feature_homography.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['matching_20with_20flann_17',['Feature Matching with FLANN',['../d5/d6f/tutorial_feature_flann_matcher.html',1,'tutorial_table_of_content_features2d']]],
  ['matrices_18',['Mask operations on matrices',['../d7/d37/tutorial_mat_mask_operations.html',1,'tutorial_table_of_content_core']]],
  ['matting_19',['Information Flow Alpha Matting',['../dd/d0e/tutorial_alphamat.html',1,'tutorial_contrib_root']]],
  ['means_20clustering_20',['means clustering',['../d9/d70/tutorial_py_kmeans_index.html',1,'K-Means Clustering'],['../de/d4d/tutorial_py_kmeans_understanding.html',1,'Understanding K-Means Clustering']]],
  ['means_20clustering_20in_20opencv_21',['K-Means Clustering in OpenCV',['../d1/d5c/tutorial_py_kmeans_opencv.html',1,'tutorial_py_kmeans_index']]],
  ['meanshift_20and_20camshift_22',['meanshift and camshift',['../db/df8/tutorial_py_meanshift.html',1,'Meanshift and Camshift'],['../d7/d00/tutorial_meanshift.html',1,'Meanshift and Camshift'],['../df/def/tutorial_js_meanshift.html',1,'Meanshift and Camshift']]],
  ['measurement_23',['Video Input with OpenCV and similarity measurement',['../d5/dc4/tutorial_video_input_psnr_ssim.html',1,'tutorial_table_of_content_app']]],
  ['measurement_20and_20improvement_20techniques_24',['Performance Measurement and Improvement Techniques',['../dc/d71/tutorial_py_optimization.html',1,'tutorial_py_table_of_contents_core']]],
  ['measurement_20with_20opencv_25',['How to scan images, lookup tables and time measurement with OpenCV',['../db/da5/tutorial_how_to_scan_images.html',1,'tutorial_table_of_content_core']]],
  ['media_20highgui_20module_26',['High Level GUI and Media (highgui module)',['../d0/de2/tutorial_table_of_content_highgui.html',1,'']]],
  ['memory_20images_20in_20the_20visual_20studio_20debugger_27',['Image Watch: viewing in-memory images in the Visual Studio debugger',['../d4/d14/tutorial_windows_visual_studio_image_watch.html',1,'tutorial_table_of_content_introduction']]],
  ['methods_28',['How to Use Background Subtraction Methods',['../d1/dc5/tutorial_background_subtraction.html',1,'tutorial_table_of_content_other']]],
  ['microsoft_20visual_20studio_29',['How to build applications with OpenCV inside the &quot;Microsoft Visual Studio&quot;',['../dd/d6e/tutorial_windows_visual_studio_opencv.html',1,'tutorial_table_of_content_introduction']]],
  ['miss_30',['Hit-or-Miss',['../db/d06/tutorial_hitOrMiss.html',1,'tutorial_table_of_content_imgproc']]],
  ['ml_20module_31',['Machine Learning (ml module)',['../d1/d69/tutorial_table_of_content_ml.html',1,'']]],
  ['ml_20objdetect_20photo_20stitching_20video_32',['Other tutorials (ml, objdetect, photo, stitching, video)',['../d3/dd5/tutorial_table_of_content_other.html',1,'tutorial_root']]],
  ['model_33',['model',['../d1/dc1/tutorial_ccm_color_correction_model.html',1,'Color Correction Model'],['../db/db3/tutorial_table_of_content_ccm.html',1,'Color Correction Model'],['../d9/d1e/tutorial_dnn_OCR.html',1,'How to run custom OCR model']]],
  ['models_34',['Load Caffe framework models',['../d5/de7/tutorial_dnn_googlenet.html',1,'tutorial_table_of_content_dnn']]],
  ['models_20and_20launch_20with_20opencv_35',['models and launch with opencv',['../d7/d9a/pytorch_segm_tutorial_dnn_conversion.html',1,'Conversion of PyTorch Segmentation Models and Launch with OpenCV'],['../dc/db4/tf_segm_tutorial_dnn_conversion.html',1,'Conversion of TensorFlow Segmentation Models and Launch with OpenCV']]],
  ['models_20and_20launch_20with_20opencv_20c_36',['Conversion of PyTorch Classification Models and Launch with OpenCV C++',['../dd/d55/pytorch_cls_c_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['models_20and_20launch_20with_20opencv_20python_37',['models and launch with opencv python',['../dc/d70/pytorch_cls_tutorial_dnn_conversion.html',1,'Conversion of PyTorch Classification Models and Launch with OpenCV Python'],['../d1/d8f/tf_cls_tutorial_dnn_conversion.html',1,'Conversion of TensorFlow Classification Models and Launch with OpenCV Python'],['../d4/d2f/tf_det_tutorial_dnn_conversion.html',1,'Conversion of TensorFlow Detection Models and Launch with OpenCV Python']]],
  ['modify_20and_20save_20an_20image_38',['Load, Modify, and Save an Image',['../db/d64/tutorial_load_save_image.html',1,'']]],
  ['module_39',['module',['../d9/d97/tutorial_table_of_content_features2d.html',1,'2D Features framework (feature2d module)'],['../d6/d55/tutorial_table_of_content_calib3d.html',1,'Camera calibration and 3D reconstruction (calib3d module)'],['../da/de7/tutorial_table_of_content_photo.html',1,'Computational photography (photo module)'],['../d0/db7/tutorial_js_table_of_contents_dnn.html',1,'Deep Neural Networks (dnn module)'],['../d2/d58/tutorial_table_of_content_dnn.html',1,'Deep Neural Networks (dnn module)'],['../da/d2c/tutorial_table_of_content_gpu.html',1,'GPU-Accelerated Computer Vision (cuda module)'],['../df/d7e/tutorial_table_of_content_gapi.html',1,'Graph API (gapi module)'],['../d0/de2/tutorial_table_of_content_highgui.html',1,'High Level GUI and Media (highgui module)'],['../da/d8f/tutorial_table_of_content_imgcodecs.html',1,'Image Input and Output (imgcodecs module)'],['../d7/da8/tutorial_table_of_content_imgproc.html',1,'Image Processing (imgproc module)'],['../d0/d33/tutorial_table_of_content_stitching.html',1,'Images stitching (stitching module)'],['../d1/d69/tutorial_table_of_content_ml.html',1,'Machine Learning (ml module)'],['../d2/d64/tutorial_table_of_content_objdetect.html',1,'Object Detection (objdetect module)'],['../d9/d58/tutorial_table_of_content_quasi_dense_stereo.html',1,'Quasi Dense Stereo (stereo module)'],['../d0/dda/tutorial_table_of_content_text.html',1,'Text module'],['../de/d7a/tutorial_table_of_content_core.html',1,'The Core Functionality (core module)'],['../d3/d89/tutorial_table_of_content_bgsegm.html',1,'Tutorials for bgsegm module'],['../de/d27/tutorial_table_of_content_face.html',1,'Tutorials for face module'],['../da/dd0/tutorial_table_of_content_video.html',1,'Video analysis (video module)'],['../df/d2c/tutorial_table_of_content_videoio.html',1,'Video Input and Output (videoio module)']]],
  ['module_20changelog_40',['Face module changelog',['../d9/d47/face_changelog.html',1,'']]],
  ['module_20faq_41',['Aruco module FAQ',['../d1/dcb/tutorial_aruco_faq.html',1,'tutorial_table_of_content_objdetect']]],
  ['module_20installation_42',['SFM module installation',['../db/db8/tutorial_sfm_installation.html',1,'tutorial_table_of_content_sfm']]],
  ['module_20introduction_43',['CUDA Module Introduction',['../d2/dbc/cuda_intro.html',1,'']]],
  ['module_20retina_20introduction_44',['Bioinspired Module Retina Introduction',['../d2/d94/bioinspired_retina.html',1,'']]],
  ['modules_45',['modules',['../de/d3d/tutorial_table_of_content_app.html',1,'Application utils (highgui, imgcodecs, videoio modules)'],['../index.html',1,'OpenCV modules'],['../d3/d81/tutorial_contrib_root.html',1,'Tutorials for contrib modules']]],
  ['moments_46',['Image Moments',['../d0/d49/tutorial_moments.html',1,'tutorial_table_of_content_imgproc']]],
  ['more_20functions_47',['more functions',['../d8/d1c/tutorial_js_contours_more_functions.html',1,'Contours : More Functions'],['../d5/d45/tutorial_py_contours_more_functions.html',1,'Contours : More Functions']]],
  ['more_20morphology_20transformations_48',['More Morphology Transformations',['../d3/dbe/tutorial_opening_closing_hats.html',1,'tutorial_table_of_content_imgproc']]],
  ['morphological_20operations_49',['Extract horizontal and vertical lines by using morphological operations',['../dd/dd7/tutorial_morph_lines_detection.html',1,'tutorial_table_of_content_imgproc']]],
  ['morphological_20transformations_50',['morphological transformations',['../d4/d76/tutorial_js_morphological_ops.html',1,'Morphological Transformations'],['../d9/d61/tutorial_py_morphological_ops.html',1,'Morphological Transformations']]],
  ['morphology_20transformations_51',['More Morphology Transformations',['../d3/dbe/tutorial_opening_closing_hats.html',1,'tutorial_table_of_content_imgproc']]],
  ['motion_52',['Structure From Motion',['../de/d7c/tutorial_table_of_content_sfm.html',1,'tutorial_contrib_root']]],
  ['motion_20deblur_20filter_53',['Motion Deblur Filter',['../d1/dfd/tutorial_motion_deblur_filter.html',1,'tutorial_table_of_content_imgproc']]],
  ['motion_20estimation_54',['Camera Motion Estimation',['../d5/dab/tutorial_sfm_trajectory_estimation.html',1,'tutorial_table_of_content_sfm']]],
  ['mouse_20as_20a_20paint_20brush_55',['Mouse as a Paint-Brush',['../db/d5b/tutorial_py_mouse_handling.html',1,'tutorial_py_table_of_contents_gui']]],
  ['multi_20camera_20calibration_56',['Multi-camera Calibration',['../d2/d1c/tutorial_multi_camera_main.html',1,'tutorial_contrib_root']]],
  ['multi_20output_57',['Upscaling images: multi-output',['../d6/dca/tutorial_dnn_superres_upscale_image_multi.html',1,'tutorial_table_of_content_dnn_superres']]],
  ['multiarch_20cross_20compilation_20with_20ubuntu_20debian_58',['MultiArch cross-compilation with Ubuntu/Debian',['../d3/dd9/tutorial_crosscompile_with_multiarch.html',1,'tutorial_table_of_content_introduction']]],
  ['multitracker_59',['Using MultiTracker',['../d5/d07/tutorial_multitracker.html',1,'tutorial_contrib_root']]]
];
