var searchData=
[
  ['o_0',['The Hierarchical Data Format (hdf) I/O',['../d3/d00/tutorial_table_of_content_hdf.html',1,'tutorial_contrib_root']]],
  ['o_20with_20opencv_20overview_1',['Video I/O with OpenCV Overview',['../d0/da7/videoio_overview.html',1,'']]],
  ['oak_20depth_20sensors_2',['Using DepthAI Hardware / OAK depth sensors',['../df/d88/tutorial_gapi_oak_devices.html',1,'tutorial_table_of_content_gapi']]],
  ['objdetect_20module_3',['Object Detection (objdetect module)',['../d2/d64/tutorial_table_of_content_objdetect.html',1,'tutorial_root']]],
  ['objdetect_20photo_20stitching_20video_4',['Other tutorials (ml, objdetect, photo, stitching, video)',['../d3/dd5/tutorial_table_of_content_other.html',1,'tutorial_root']]],
  ['object_5',['object',['../d7/dff/tutorial_feature_homography.html',1,'Features2D + Homography to find a known object'],['../dc/d2c/tutorial_real_time_pose.html',1,'Real Time pose estimation of a textured object']]],
  ['object_20detection_6',['object detection',['../d9/de5/tutorial_py_table_of_contents_objdetect.html',1,'Object Detection'],['../dc/d73/tutorial_js_table_of_contents_objdetect.html',1,'Object Detection']]],
  ['object_20detection_20example_7',['Object Detection Example',['../d0/d0f/tutorial_js_object_detection.html',1,'tutorial_js_table_of_contents_dnn']]],
  ['object_20detection_20example_20with_20camera_8',['Object Detection Example with Camera',['../d2/d14/tutorial_js_object_detection_with_camera.html',1,'tutorial_js_table_of_contents_dnn']]],
  ['object_20detection_20objdetect_20module_9',['Object Detection (objdetect module)',['../d2/d64/tutorial_table_of_content_objdetect.html',1,'tutorial_root']]],
  ['object_20detection_20using_20cnns_10',['Object Detection using CNNs',['../d2/da2/tutorial_dnn_objdetect.html',1,'tutorial_contrib_root']]],
  ['object_20detection_20with_20generalized_20ballard_20and_20guil_20hough_20transform_11',['Object detection with Generalized Ballard and Guil Hough Transform',['../da/ddc/tutorial_generalized_hough_ballard_guil.html',1,'tutorial_table_of_content_imgproc']]],
  ['objects_12',['objects',['../dd/dd4/tutorial_detection_of_planar_objects.html',1,'Detection of planar objects'],['../d1/de0/tutorial_py_feature_homography.html',1,'Feature Matching + Homography to find Objects']]],
  ['ocr_20model_13',['How to run custom OCR model',['../d9/d1e/tutorial_dnn_OCR.html',1,'tutorial_table_of_content_dnn']]],
  ['ocr_20of_20hand_20written_20data_20using_20knn_14',['OCR of Hand-written Data using kNN',['../d8/d4b/tutorial_py_knn_opencv.html',1,'tutorial_py_knn_index']]],
  ['ocr_20of_20hand_20written_20data_20using_20svm_15',['OCR of Hand-written Data using SVM',['../dd/d3b/tutorial_py_svm_opencv.html',1,'tutorial_py_svm_index']]],
  ['odometry_20algorithm_16',['ICP point-to-plane odometry algorithm',['../d7/dbe/kinfu_icp.html',1,'']]],
  ['of_20a_20textured_20object_17',['Real Time pose estimation of a textured object',['../dc/d2c/tutorial_real_time_pose.html',1,'tutorial_table_of_content_calib3d']]],
  ['of_20a_20widget_18',['Pose of a widget',['../d8/df0/tutorial_widget_pose.html',1,'tutorial_table_of_content_viz']]],
  ['of_20an_20image_19',['Changing the contrast and brightness of an image!',['../d3/dc1/tutorial_basic_linear_transform.html',1,'tutorial_table_of_content_core']]],
  ['of_20aruco_20boards_20',['Detection of ArUco boards',['../db/da9/tutorial_aruco_board_detection.html',1,'tutorial_table_of_content_objdetect']]],
  ['of_20aruco_20markers_21',['Detection of ArUco Markers',['../d5/dae/tutorial_aruco_detection.html',1,'tutorial_table_of_content_objdetect']]],
  ['of_20charuco_20boards_22',['Detection of ChArUco Boards',['../df/d4a/tutorial_charuco_detection.html',1,'tutorial_table_of_content_objdetect']]],
  ['of_20computer_20vision_20applications_23',['Interactive Visual Debugging of Computer Vision applications',['../d7/dcf/tutorial_cvv_introduction.html',1,'tutorial_contrib_root']]],
  ['of_20diamond_20markers_24',['Detection of Diamond Markers',['../d5/d07/tutorial_charuco_diamond_detection.html',1,'tutorial_table_of_content_objdetect']]],
  ['of_20focus_20deblur_20filter_25',['Out-of-focus Deblur Filter',['../de/d3c/tutorial_out_of_focus_deblur_filter.html',1,'tutorial_table_of_content_imgproc']]],
  ['of_20hand_20written_20data_20using_20knn_26',['OCR of Hand-written Data using kNN',['../d8/d4b/tutorial_py_knn_opencv.html',1,'tutorial_py_knn_index']]],
  ['of_20hand_20written_20data_20using_20svm_27',['OCR of Hand-written Data using SVM',['../dd/d3b/tutorial_py_svm_opencv.html',1,'tutorial_py_svm_index']]],
  ['of_20images_28',['of images',['../da/d6e/tutorial_py_geometric_transformations.html',1,'Geometric Transformations of Images'],['../dd/d52/tutorial_js_geometric_transformations.html',1,'Geometric Transformations of Images']]],
  ['of_20planar_20objects_29',['Detection of planar objects',['../dd/dd4/tutorial_detection_of_planar_objects.html',1,'tutorial_table_of_content_features2d']]],
  ['of_20pytorch_20classification_20models_20and_20launch_20with_20opencv_20c_30',['Conversion of PyTorch Classification Models and Launch with OpenCV C++',['../dd/d55/pytorch_cls_c_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['of_20pytorch_20classification_20models_20and_20launch_20with_20opencv_20python_31',['Conversion of PyTorch Classification Models and Launch with OpenCV Python',['../dc/d70/pytorch_cls_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['of_20pytorch_20segmentation_20models_20and_20launch_20with_20opencv_32',['Conversion of PyTorch Segmentation Models and Launch with OpenCV',['../d7/d9a/pytorch_segm_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['of_20random_20sample_20consensus_20in_20opencv_33',['USAC: Improvement of Random Sample Consensus in OpenCV',['../de/d3e/tutorial_usac.html',1,'tutorial_table_of_content_calib3d']]],
  ['of_20tensorflow_20classification_20models_20and_20launch_20with_20opencv_20python_34',['Conversion of TensorFlow Classification Models and Launch with OpenCV Python',['../d1/d8f/tf_cls_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['of_20tensorflow_20detection_20models_20and_20launch_20with_20opencv_20python_35',['Conversion of TensorFlow Detection Models and Launch with OpenCV Python',['../d4/d2f/tf_det_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['of_20tensorflow_20segmentation_20models_20and_20launch_20with_20opencv_36',['Conversion of TensorFlow Segmentation Models and Launch with OpenCV',['../dc/db4/tf_segm_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['of_20the_20homography_20explained_20with_20code_37',['Basic concepts of the homography explained with code',['../d9/dab/tutorial_homography.html',1,'tutorial_table_of_content_features2d']]],
  ['oil_20painting_20effect_38',['Oil painting effect',['../dd/d8c/tutorial_xphoto_oil_painting_effect.html',1,'tutorial_contrib_root']]],
  ['omnidirectional_20camera_20calibration_39',['Omnidirectional Camera Calibration',['../dd/d12/tutorial_omnidir_calib_main.html',1,'tutorial_contrib_root']]],
  ['on_20android_20device_40',['How to run deep networks on Android device',['../de/dfe/tutorial_android_dnn_intro.html',1,'tutorial_table_of_content_introduction']]],
  ['on_20facial_20landmark_20detector_20api_41',['Tutorial on Facial Landmark Detector API',['../d5/d47/tutorial_table_of_content_facemark.html',1,'tutorial_contrib_root']]],
  ['on_20g_20api_42',['Porting anisotropic image segmentation on G-API',['../d3/d7a/tutorial_gapi_anisotropic_segmentation.html',1,'tutorial_table_of_content_gapi']]],
  ['on_20images_43',['on images',['../d0/d86/tutorial_py_image_arithmetics.html',1,'Arithmetic Operations on Images'],['../dd/d4d/tutorial_js_image_arithmetics.html',1,'Arithmetic Operations on Images'],['../d3/df2/tutorial_py_basic_ops.html',1,'Basic Operations on Images'],['../de/d06/tutorial_js_basic_ops.html',1,'Basic Operations on Images']]],
  ['on_20matrices_44',['Mask operations on matrices',['../d7/d37/tutorial_mat_mask_operations.html',1,'tutorial_table_of_content_core']]],
  ['on_20the_20gpu_45',['Similarity check (PNSR and SSIM) on the GPU',['../dd/d3d/tutorial_gpu_basics_similarity.html',1,'tutorial_table_of_content_gpu']]],
  ['opencl_20in_20android_20camera_20preview_20based_20cv_20application_46',['Use OpenCL in Android camera preview based CV application',['../d7/dbd/tutorial_android_ocl_intro.html',1,'tutorial_table_of_content_introduction']]],
  ['opencv_47',['opencv',['../d5/dc4/tutorial_adding_images.html',1,'Adding (blending) two images using OpenCV'],['../d5/df8/tutorial_dev_with_OCV_on_Android.html',1,'Android Development with OpenCV'],['../d4/d94/tutorial_camera_calibration.html',1,'Camera calibration With OpenCV'],['../d3/d05/tutorial_py_table_of_contents_contours.html',1,'Contours in OpenCV'],['../de/d09/tutorial_table_of_contents_contours.html',1,'Contours in OpenCV'],['../d7/d9a/pytorch_segm_tutorial_dnn_conversion.html',1,'Conversion of PyTorch Segmentation Models and Launch with OpenCV'],['../dc/db4/tf_segm_tutorial_dnn_conversion.html',1,'Conversion of TensorFlow Segmentation Models and Launch with OpenCV'],['../d7/d9e/tutorial_video_write.html',1,'Creating a video with OpenCV'],['../dc/da5/tutorial_py_drawing_functions.html',1,'Drawing Functions in OpenCV'],['../da/d60/tutorial_face_main.html',1,'Face Recognition with OpenCV'],['../dc/d4d/tutorial_py_table_of_contents_gui.html',1,'Gui Features in OpenCV'],['../de/db2/tutorial_py_table_of_contents_histograms.html',1,'Histograms in OpenCV'],['../db/da5/tutorial_how_to_scan_images.html',1,'How to scan images, lookup tables and time measurement with OpenCV'],['../d2/d96/tutorial_py_table_of_contents_imgproc.html',1,'Image Processing in OpenCV'],['../dd/dc4/tutorial_py_table_of_contents_transforms.html',1,'Image Transforms in OpenCV'],['../da/df6/tutorial_py_table_of_contents_setup.html',1,'Introduction to OpenCV'],['../df/d65/tutorial_table_of_content_introduction.html',1,'Introduction to OpenCV'],['../d1/d5c/tutorial_py_kmeans_opencv.html',1,'K-Means Clustering in OpenCV'],['../df/d61/tutorial_random_generator_and_text.html',1,'Random generator and text with OpenCV'],['../de/d3e/tutorial_usac.html',1,'USAC: Improvement of Random Sample Consensus in OpenCV'],['../d4/db1/tutorial_documentation.html',1,'Writing documentation for OpenCV']]],
  ['opencv_20and_20similarity_20measurement_48',['Video Input with OpenCV and similarity measurement',['../d5/dc4/tutorial_video_input_psnr_ssim.html',1,'tutorial_table_of_content_app']]],
  ['opencv_20binding_49',['Introduction to Julia OpenCV Binding',['../d8/da4/tutorial_julia.html',1,'tutorial_contrib_root']]],
  ['opencv_20c_50',['Conversion of PyTorch Classification Models and Launch with OpenCV C++',['../dd/d55/pytorch_cls_c_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['opencv_20configuration_20options_20reference_51',['OpenCV configuration options reference',['../db/d05/tutorial_config_reference.html',1,'tutorial_table_of_content_introduction']]],
  ['opencv_20development_20with_20clojure_52',['Introduction to OpenCV Development with Clojure',['../d7/d1e/tutorial_clojure_dev_intro.html',1,'tutorial_table_of_content_introduction']]],
  ['opencv_20environment_20variables_20reference_53',['OpenCV environment variables reference',['../d6/dea/tutorial_env_reference.html',1,'tutorial_table_of_content_introduction']]],
  ['opencv_20for_20tegra_20with_20cuda_54',['Building OpenCV for Tegra with CUDA',['../d6/d15/tutorial_building_tegra_cuda.html',1,'tutorial_table_of_content_introduction']]],
  ['opencv_20from_20other_20doxygen_20projects_55',['Cross referencing OpenCV from other Doxygen projects',['../d3/dff/tutorial_cross_referencing.html',1,'tutorial_table_of_content_introduction']]],
  ['opencv_20inside_20the_20microsoft_20visual_20studio_56',['How to build applications with OpenCV inside the &quot;Microsoft Visual Studio&quot;',['../dd/d6e/tutorial_windows_visual_studio_opencv.html',1,'tutorial_table_of_content_introduction']]],
  ['opencv_20installation_20overview_57',['OpenCV installation overview',['../d0/d3d/tutorial_general_install.html',1,'tutorial_table_of_content_introduction']]],
  ['opencv_20ios_58',['OpenCV iOS',['../d3/dc9/tutorial_table_of_content_ios.html',1,'tutorial_root']]],
  ['opencv_20ios_20hello_59',['OpenCV iOS Hello',['../d7/d88/tutorial_hello.html',1,'tutorial_table_of_content_ios']]],
  ['opencv_20ios_20image_20processing_60',['OpenCV iOS - Image Processing',['../d3/def/tutorial_image_manipulation.html',1,'tutorial_table_of_content_ios']]],
  ['opencv_20ios_20video_20processing_61',['OpenCV iOS - Video Processing',['../db/dc8/tutorial_video_processing.html',1,'tutorial_table_of_content_ios']]],
  ['opencv_20java_20with_20eclipse_62',['Using OpenCV Java with Eclipse',['../d1/d0a/tutorial_java_eclipse.html',1,'tutorial_table_of_content_introduction']]],
  ['opencv_20js_63',['opencv js',['../d4/da1/tutorial_js_setup.html',1,'Build OpenCV.js'],['../d0/d43/tutorial_js_table_of_contents_contours.html',1,'Contours in OpenCV.js'],['../d5/dc0/tutorial_js_table_of_contents_histograms.html',1,'Histograms in OpenCV.js'],['../db/db3/tutorial_js_table_of_contents_transforms.html',1,'Image Transforms in OpenCV.js'],['../df/df7/tutorial_js_table_of_contents_setup.html',1,'Introduction to OpenCV.js'],['../d0/d84/tutorial_js_usage.html',1,'Using OpenCV.js']]],
  ['opencv_20js_20and_20tutorials_64',['Introduction to OpenCV.js and Tutorials',['../df/d0a/tutorial_js_intro.html',1,'tutorial_js_table_of_contents_setup']]],
  ['opencv_20js_20in_20node_20js_65',['Using OpenCV.js In Node.js',['../dc/de6/tutorial_js_nodejs.html',1,'tutorial_js_table_of_contents_setup']]],
  ['opencv_20js_20tutorials_66',['OpenCV.js Tutorials',['../d5/d10/tutorial_js_root.html',1,'']]],
  ['opencv_20modules_67',['OpenCV modules',['../index.html',1,'']]],
  ['opencv_20overview_68',['Video I/O with OpenCV Overview',['../d0/da7/videoio_overview.html',1,'']]],
  ['opencv_20parallel_5ffor_5f_20to_20parallelize_20your_20code_69',['opencv parallel_for_ to parallelize your code',['../dc/ddf/tutorial_how_to_use_OpenCV_parallel_for_new.html',1,'How to use the OpenCV parallel_for_ to parallelize your code'],['../d7/dff/tutorial_how_to_use_OpenCV_parallel_for_.html',1,'How to use the OpenCV parallel_for_ to parallelize your code']]],
  ['opencv_20python_70',['opencv python',['../dc/d70/pytorch_cls_tutorial_dnn_conversion.html',1,'Conversion of PyTorch Classification Models and Launch with OpenCV Python'],['../d1/d8f/tf_cls_tutorial_dnn_conversion.html',1,'Conversion of TensorFlow Classification Models and Launch with OpenCV Python'],['../d4/d2f/tf_det_tutorial_dnn_conversion.html',1,'Conversion of TensorFlow Detection Models and Launch with OpenCV Python']]],
  ['opencv_20python_20bindings_71',['OpenCV-Python Bindings',['../df/da2/tutorial_py_table_of_contents_bindings.html',1,'tutorial_py_root']]],
  ['opencv_20python_20bindings_20works_72',['How OpenCV-Python Bindings Works?',['../da/d49/tutorial_py_bindings_basics.html',1,'tutorial_py_table_of_contents_bindings']]],
  ['opencv_20python_20in_20fedora_73',['Install OpenCV-Python in Fedora',['../dd/dd5/tutorial_py_setup_in_fedora.html',1,'tutorial_py_table_of_contents_setup']]],
  ['opencv_20python_20in_20ubuntu_74',['Install OpenCV-Python in Ubuntu',['../d2/de6/tutorial_py_setup_in_ubuntu.html',1,'tutorial_py_table_of_contents_setup']]],
  ['opencv_20python_20in_20windows_75',['Install OpenCV-Python in Windows',['../d5/de5/tutorial_py_setup_in_windows.html',1,'tutorial_py_table_of_contents_setup']]],
  ['opencv_20python_20tutorials_76',['opencv python tutorials',['../d0/de3/tutorial_py_intro.html',1,'Introduction to OpenCV-Python Tutorials'],['../d6/d00/tutorial_py_root.html',1,'OpenCV-Python Tutorials']]],
  ['opencv_20tracker_77',['Introduction to OpenCV Tracker',['../d2/d0a/tutorial_introduction_to_tracker.html',1,'tutorial_contrib_root']]],
  ['opencv_20tutorials_78',['OpenCV Tutorials',['../d9/df8/tutorial_root.html',1,'']]],
  ['opencv_20usage_20with_20openvino_79',['OpenCV usage with OpenVINO',['../dc/dfe/tutorial_dnn_openvino.html',1,'tutorial_table_of_content_dnn']]],
  ['opencv_20viz_80',['OpenCV Viz',['../d7/df9/tutorial_table_of_content_viz.html',1,'tutorial_contrib_root']]],
  ['opencv_20with_20eclipse_20plugin_20cdt_81',['Using OpenCV with Eclipse (plugin CDT)',['../d7/d16/tutorial_linux_eclipse.html',1,'tutorial_table_of_content_introduction']]],
  ['opencv_20with_20gcc_20and_20cmake_82',['Using OpenCV with gcc and CMake',['../db/df5/tutorial_linux_gcc_cmake.html',1,'tutorial_table_of_content_introduction']]],
  ['opencv_20with_20gdb_20powered_20ides_83',['Using OpenCV with gdb-powered IDEs',['../d6/d25/tutorial_linux_gdb_pretty_printer.html',1,'tutorial_table_of_content_introduction']]],
  ['openni_20compatible_20depth_20sensors_84',['Using Kinect and other OpenNI compatible depth sensors',['../d7/d6f/tutorial_kinect_openni.html',1,'tutorial_table_of_content_app']]],
  ['openvino_85',['OpenCV usage with OpenVINO',['../dc/dfe/tutorial_dnn_openvino.html',1,'tutorial_table_of_content_dnn']]],
  ['operations_86',['operations',['../db/d8e/tutorial_threshold.html',1,'Basic Thresholding Operations'],['../d1/d78/tutorial_js_table_of_contents_core.html',1,'Core Operations'],['../d7/d16/tutorial_py_table_of_contents_core.html',1,'Core Operations'],['../dd/dd7/tutorial_morph_lines_detection.html',1,'Extract horizontal and vertical lines by using morphological operations']]],
  ['operations_20on_20images_87',['operations on images',['../dd/d4d/tutorial_js_image_arithmetics.html',1,'Arithmetic Operations on Images'],['../d0/d86/tutorial_py_image_arithmetics.html',1,'Arithmetic Operations on Images'],['../de/d06/tutorial_js_basic_ops.html',1,'Basic Operations on Images'],['../d3/df2/tutorial_py_basic_ops.html',1,'Basic Operations on Images']]],
  ['operations_20on_20matrices_88',['Mask operations on matrices',['../d7/d37/tutorial_mat_mask_operations.html',1,'tutorial_table_of_content_core']]],
  ['operations_20using_20inrange_89',['Thresholding Operations using inRange',['../da/d97/tutorial_threshold_inRange.html',1,'tutorial_table_of_content_imgproc']]],
  ['operations_20with_20images_90',['Operations with images',['../d5/d98/tutorial_mat_operations.html',1,'tutorial_table_of_content_core']]],
  ['operator_91',['Laplace Operator',['../d5/db5/tutorial_laplace_operator.html',1,'tutorial_table_of_content_imgproc']]],
  ['optical_20flow_92',['optical flow',['../d7/d8b/tutorial_py_lucas_kanade.html',1,'Optical Flow'],['../db/d7f/tutorial_js_lucas_kanade.html',1,'Optical Flow'],['../d4/dee/tutorial_optical_flow.html',1,'Optical Flow']]],
  ['optical_20illusions_93',['Processing images causing optical illusions',['../d7/d8f/tutorial_bioinspired_retina_illusion.html',1,'tutorial_table_of_content_retina']]],
  ['options_20reference_94',['OpenCV configuration options reference',['../db/d05/tutorial_config_reference.html',1,'tutorial_table_of_content_introduction']]],
  ['or_20miss_95',['Hit-or-Miss',['../db/d06/tutorial_hitOrMiss.html',1,'tutorial_table_of_content_imgproc']]],
  ['orb_20oriented_20fast_20and_20rotated_20brief_96',['ORB (Oriented FAST and Rotated BRIEF)',['../d1/d89/tutorial_py_orb.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['orb_20planar_20tracking_97',['AKAZE and ORB planar tracking',['../dc/d16/tutorial_akaze_tracking.html',1,'tutorial_table_of_content_features2d']]],
  ['orbbec_20astra_203d_20cameras_98',['Using Orbbec Astra 3D cameras',['../d4/d65/tutorial_orbbec_astra.html',1,'tutorial_table_of_content_app']]],
  ['oriented_20fast_20and_20rotated_20brief_99',['ORB (Oriented FAST and Rotated BRIEF)',['../d1/d89/tutorial_py_orb.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['other_20doxygen_20projects_100',['Cross referencing OpenCV from other Doxygen projects',['../d3/dff/tutorial_cross_referencing.html',1,'tutorial_table_of_content_introduction']]],
  ['other_20intel_20realsense_20sdk_20compatible_20depth_20sensors_101',['Using Creative Senz3D and other Intel RealSense SDK compatible depth sensors',['../db/d08/tutorial_intelperc.html',1,'tutorial_table_of_content_app']]],
  ['other_20openni_20compatible_20depth_20sensors_102',['Using Kinect and other OpenNI compatible depth sensors',['../d7/d6f/tutorial_kinect_openni.html',1,'tutorial_table_of_content_app']]],
  ['other_20tutorials_20ml_20objdetect_20photo_20stitching_20video_103',['Other tutorials (ml, objdetect, photo, stitching, video)',['../d3/dd5/tutorial_table_of_content_other.html',1,'tutorial_root']]],
  ['our_20applications_104',['Adding a Trackbar to our applications!',['../da/d6a/tutorial_trackbar.html',1,'tutorial_table_of_content_app']]],
  ['out_20of_20focus_20deblur_20filter_105',['Out-of-focus Deblur Filter',['../de/d3c/tutorial_out_of_focus_deblur_filter.html',1,'tutorial_table_of_content_imgproc']]],
  ['output_106',['output',['../d6/dca/tutorial_dnn_superres_upscale_image_multi.html',1,'Upscaling images: multi-output'],['../d5/d29/tutorial_dnn_superres_upscale_image_single.html',1,'Upscaling images: single-output']]],
  ['output_20imgcodecs_20module_107',['Image Input and Output (imgcodecs module)',['../da/d8f/tutorial_table_of_content_imgcodecs.html',1,'']]],
  ['output_20using_20xml_20and_20yaml_20files_108',['File Input and Output using XML and YAML files',['../dd/d74/tutorial_file_input_output_with_xml_yml.html',1,'tutorial_table_of_content_core']]],
  ['output_20videoio_20module_109',['Video Input and Output (videoio module)',['../df/d2c/tutorial_table_of_content_videoio.html',1,'']]],
  ['overview_110',['overview',['../de/d96/md_gapi_2doc_2slides_2README.html',1,'G-API Overview'],['../de/d4d/gapi_hld.html',1,'High-level design overview'],['../dc/dd6/ml_intro.html',1,'Machine Learning Overview'],['../d0/d3d/tutorial_general_install.html',1,'OpenCV installation overview'],['../d0/da7/videoio_overview.html',1,'Video I/O with OpenCV Overview']]],
  ['own_20corner_20detector_111',['Creating your own corner detector',['../d9/dbc/tutorial_generic_corner_detector.html',1,'tutorial_table_of_content_features2d']]],
  ['own_20linear_20filters_112',['Making your own linear filters!',['../d4/dbd/tutorial_filter_2d.html',1,'tutorial_table_of_content_imgproc']]]
];
