var searchData=
[
  ['f_20transform_0',['f transform',['../d3/d1d/tutorial_fuzzy_filtering.html',1,'Filtering using F-transform'],['../d3/db8/tutorial_fuzzy_inpainting.html',1,'Inpainting using F-transform']]],
  ['f_20transform_20theory_1',['F-transform theory',['../db/daf/tutorial_fuzzy_theory.html',1,'tutorial_fuzzy']]],
  ['face_20analytics_20pipeline_20with_20g_20api_2',['Face analytics pipeline with G-API',['../d8/d24/tutorial_gapi_interactive_face_detection.html',1,'tutorial_table_of_content_gapi']]],
  ['face_20beautification_20algorithm_20with_20g_20api_3',['Implementing a face beautification algorithm with G-API',['../d4/d48/tutorial_gapi_face_beautification.html',1,'tutorial_table_of_content_gapi']]],
  ['face_20detection_20and_20recognition_4',['DNN-based Face Detection And Recognition',['../d0/dd4/tutorial_dnn_face.html',1,'tutorial_table_of_content_dnn']]],
  ['face_20detection_20in_20video_20capture_5',['Face Detection in Video Capture',['../df/d6c/tutorial_js_face_detection_camera.html',1,'tutorial_js_table_of_contents_objdetect']]],
  ['face_20detection_20using_20haar_20cascades_6',['face detection using haar cascades',['../d2/d99/tutorial_js_face_detection.html',1,'Face Detection using Haar Cascades'],['../d7/d8b/tutorial_py_face_detection.html',1,'Face Detection using Haar Cascades']]],
  ['face_20landmark_20detection_20in_20a_20video_7',['Face landmark detection in a video',['../d8/d3c/tutorial_face_landmark_detection_in_video.html',1,'tutorial_table_of_content_face']]],
  ['face_20landmark_20detection_20in_20an_20image_8',['Face landmark detection in an image',['../d2/d42/tutorial_face_landmark_detection_in_an_image.html',1,'tutorial_table_of_content_face']]],
  ['face_20module_9',['Tutorials for face module',['../de/d27/tutorial_table_of_content_face.html',1,'tutorial_contrib_root']]],
  ['face_20module_20changelog_10',['Face module changelog',['../d9/d47/face_changelog.html',1,'']]],
  ['face_20recognition_20with_20opencv_11',['Face Recognition with OpenCV',['../da/d60/tutorial_face_main.html',1,'tutorial_table_of_content_face']]],
  ['face_20swapping_20using_20face_20landmark_20detection_12',['Face swapping using face landmark detection',['../d1/d52/tutorial_face_swapping_face_landmark_detection.html',1,'tutorial_table_of_content_face']]],
  ['face_5flandmark_5ftrainer_13',['face_landmark_trainer',['../d3/d55/md__2build_24__x-contrib__docs-lin64_2opencv__contrib_2modules_2face_2tutorials_2face__landmark_2face__landmark__trainer.html',1,'']]],
  ['facemark_20api_14',['facemark api',['../d4/d3e/tutorial_facemark_add_algorithm.html',1,'Adding a new algorithm to the Facemark API'],['../d7/dec/tutorial_facemark_usage.html',1,'Using the Facemark API']]],
  ['facemarkaam_15',['Using the FacemarkAAM',['../d5/dd8/tutorial_facemark_aam.html',1,'tutorial_table_of_content_facemark']]],
  ['facial_20landmark_20detector_20api_16',['Tutorial on Facial Landmark Detector API',['../d5/d47/tutorial_table_of_content_facemark.html',1,'tutorial_contrib_root']]],
  ['faq_17',['Aruco module FAQ',['../d1/dcb/tutorial_aruco_faq.html',1,'tutorial_table_of_content_objdetect']]],
  ['fast_20algorithm_20for_20corner_20detection_18',['FAST Algorithm for Corner Detection',['../df/d0c/tutorial_py_fast.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['fast_20and_20rotated_20brief_19',['ORB (Oriented FAST and Rotated BRIEF)',['../d1/d89/tutorial_py_orb.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['fast_20edge_20detection_20',['Structured forests for fast edge detection',['../d0/da5/tutorial_ximgproc_prediction.html',1,'tutorial_contrib_root']]],
  ['feature_20description_21',['Feature Description',['../d5/dde/tutorial_feature_description.html',1,'tutorial_table_of_content_features2d']]],
  ['feature_20detection_22',['Feature Detection',['../d7/d66/tutorial_feature_detection.html',1,'tutorial_table_of_content_features2d']]],
  ['feature_20detection_20and_20description_23',['Feature Detection and Description',['../db/d27/tutorial_py_table_of_contents_feature2d.html',1,'tutorial_py_root']]],
  ['feature_20matching_24',['Feature Matching',['../dc/dc3/tutorial_py_matcher.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['feature_20matching_20homography_20to_20find_20objects_25',['Feature Matching + Homography to find Objects',['../d1/de0/tutorial_py_feature_homography.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['feature_20matching_20with_20flann_26',['Feature Matching with FLANN',['../d5/d6f/tutorial_feature_flann_matcher.html',1,'tutorial_table_of_content_features2d']]],
  ['feature_20transform_27',['Introduction to SIFT (Scale-Invariant Feature Transform)',['../da/df5/tutorial_py_sift_intro.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['feature2d_20module_28',['2D Features framework (feature2d module)',['../d9/d97/tutorial_table_of_content_features2d.html',1,'tutorial_root']]],
  ['features_29',['features',['../dc/d7d/tutorial_py_brief.html',1,'BRIEF (Binary Robust Independent Elementary Features)'],['../dc/dcf/tutorial_js_contour_features.html',1,'Contour Features'],['../dd/d49/tutorial_py_contour_features.html',1,'Contour Features'],['../df/d04/tutorial_js_table_of_contents_gui.html',1,'GUI Features'],['../df/dd2/tutorial_py_surf_intro.html',1,'Introduction to SURF (Speeded-Up Robust Features)'],['../df/d54/tutorial_py_features_meaning.html',1,'Understanding Features']]],
  ['features_20framework_20feature2d_20module_30',['2D Features framework (feature2d module)',['../d9/d97/tutorial_table_of_content_features2d.html',1,'tutorial_root']]],
  ['features_20in_20opencv_31',['Gui Features in OpenCV',['../dc/d4d/tutorial_py_table_of_contents_gui.html',1,'tutorial_py_root']]],
  ['features_20matching_32',['AKAZE local features matching',['../db/d70/tutorial_akaze_matching.html',1,'tutorial_table_of_content_features2d']]],
  ['features_20to_20track_33',['Shi-Tomasi Corner Detector &amp; Good Features to Track',['../d4/d8c/tutorial_py_shi_tomasi.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['features_20tutorial_34',['Line Features Tutorial',['../df/dfa/tutorial_line_descriptor_main.html',1,'tutorial_contrib_root']]],
  ['features2d_20homography_20to_20find_20a_20known_20object_35',['Features2D + Homography to find a known object',['../d7/dff/tutorial_feature_homography.html',1,'tutorial_table_of_content_features2d']]],
  ['fedora_36',['Install OpenCV-Python in Fedora',['../dd/dd5/tutorial_py_setup_in_fedora.html',1,'tutorial_py_table_of_contents_setup']]],
  ['file_37',['Exporting a template parameter file',['../df/dc0/tutorial_qds_export_parameters.html',1,'tutorial_table_of_content_quasi_dense_stereo']]],
  ['file_20input_20and_20output_20using_20xml_20and_20yaml_20files_38',['File Input and Output using XML and YAML files',['../dd/d74/tutorial_file_input_output_with_xml_yml.html',1,'tutorial_table_of_content_core']]],
  ['files_39',['File Input and Output using XML and YAML files',['../dd/d74/tutorial_file_input_output_with_xml_yml.html',1,'tutorial_table_of_content_core']]],
  ['files_20with_20gdal_40',['Reading Geospatial Raster files with GDAL',['../d7/d73/tutorial_raster_io_gdal.html',1,'tutorial_table_of_content_app']]],
  ['filter_41',['filter',['../d1/dfd/tutorial_motion_deblur_filter.html',1,'Motion Deblur Filter'],['../de/d3c/tutorial_out_of_focus_deblur_filter.html',1,'Out-of-focus Deblur Filter'],['../d2/d0b/tutorial_periodic_noise_removing_filter.html',1,'Periodic Noise Removing Filter']]],
  ['filtering_42',['Disparity map post-filtering',['../d3/d14/tutorial_ximgproc_disparity_filtering.html',1,'tutorial_contrib_root']]],
  ['filtering_20using_20f_20transform_43',['Filtering using F-transform',['../d3/d1d/tutorial_fuzzy_filtering.html',1,'tutorial_fuzzy']]],
  ['filters_44',['Making your own linear filters!',['../d4/dbd/tutorial_filter_2d.html',1,'tutorial_table_of_content_imgproc']]],
  ['find_20a_20known_20object_45',['Features2D + Homography to find a known object',['../d7/dff/tutorial_feature_homography.html',1,'tutorial_table_of_content_features2d']]],
  ['find_20objects_46',['Feature Matching + Homography to find Objects',['../d1/de0/tutorial_py_feature_homography.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['find_20plot_20analyze_47',['find plot analyze',['../d1/db7/tutorial_py_histogram_begins.html',1,'Histograms - 1 : Find, Plot, Analyze !!!'],['../d7/d32/tutorial_js_histogram_begins.html',1,'Histograms - 1 : Find, Plot, Analyze !!!']]],
  ['finding_20contours_20in_20your_20image_48',['Finding contours in your image',['../df/d0d/tutorial_find_contours.html',1,'tutorial_table_of_content_imgproc']]],
  ['flann_49',['Feature Matching with FLANN',['../d5/d6f/tutorial_feature_flann_matcher.html',1,'tutorial_table_of_content_features2d']]],
  ['flow_50',['flow',['../db/d7f/tutorial_js_lucas_kanade.html',1,'Optical Flow'],['../d7/d8b/tutorial_py_lucas_kanade.html',1,'Optical Flow'],['../d4/dee/tutorial_optical_flow.html',1,'Optical Flow']]],
  ['flow_20alpha_20matting_51',['Information Flow Alpha Matting',['../dd/d0e/tutorial_alphamat.html',1,'tutorial_contrib_root']]],
  ['focus_20deblur_20filter_52',['Out-of-focus Deblur Filter',['../de/d3c/tutorial_out_of_focus_deblur_filter.html',1,'tutorial_table_of_content_imgproc']]],
  ['for_20arm_20based_20linux_20systems_53',['Cross compilation for ARM based Linux systems',['../d0/d76/tutorial_arm_crosscompile_with_cmake.html',1,'tutorial_table_of_content_introduction']]],
  ['for_20bgsegm_20module_54',['Tutorials for bgsegm module',['../d3/d89/tutorial_table_of_content_bgsegm.html',1,'tutorial_contrib_root']]],
  ['for_20contours_55',['for contours',['../da/d0c/tutorial_bounding_rects_circles.html',1,'Creating Bounding boxes and circles for contours'],['../de/d62/tutorial_bounding_rotated_ellipses.html',1,'Creating Bounding rotated boxes and ellipses for contours']]],
  ['for_20contrib_20modules_56',['Tutorials for contrib modules',['../d3/d81/tutorial_contrib_root.html',1,'']]],
  ['for_20corner_20detection_57',['FAST Algorithm for Corner Detection',['../df/d0c/tutorial_py_fast.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['for_20face_20module_58',['Tutorials for face module',['../de/d27/tutorial_table_of_content_face.html',1,'tutorial_contrib_root']]],
  ['for_20fast_20edge_20detection_59',['Structured forests for fast edge detection',['../d0/da5/tutorial_ximgproc_prediction.html',1,'tutorial_contrib_root']]],
  ['for_20halide_20backend_60',['How to schedule your network for Halide backend',['../de/d5d/tutorial_dnn_halide_scheduling.html',1,'tutorial_table_of_content_dnn']]],
  ['for_20image_20processing_61',['Discovering the human retina and its use for image processing',['../df/dee/tutorial_table_of_content_retina.html',1,'tutorial_contrib_root']]],
  ['for_20improve_20efficiency_62',['How to enable Halide backend for improve efficiency',['../de/d37/tutorial_dnn_halide.html',1,'tutorial_table_of_content_dnn']]],
  ['for_20non_20linearly_20separable_20data_63',['Support Vector Machines for Non-Linearly Separable Data',['../d0/dcc/tutorial_non_linear_svms.html',1,'tutorial_table_of_content_other']]],
  ['for_20opencv_64',['Writing documentation for OpenCV',['../d4/db1/tutorial_documentation.html',1,'tutorial_table_of_content_introduction']]],
  ['for_20tegra_20with_20cuda_65',['Building OpenCV for Tegra with CUDA',['../d6/d15/tutorial_building_tegra_cuda.html',1,'tutorial_table_of_content_introduction']]],
  ['for_20video_20capture_66',['Image Processing for Video Capture',['../d8/d54/tutorial_js_imgproc_camera.html',1,'tutorial_js_table_of_contents_imgproc']]],
  ['foreground_20extraction_20using_20grabcut_20algorithm_67',['foreground extraction using grabcut algorithm',['../dd/dfc/tutorial_js_grabcut.html',1,'Foreground Extraction using GrabCut Algorithm'],['../d8/d83/tutorial_py_grabcut.html',1,'Interactive Foreground Extraction using GrabCut Algorithm']]],
  ['forest_20training_68',['Structured forest training',['../d2/d59/tutorial_ximgproc_training.html',1,'tutorial_contrib_root']]],
  ['forests_20for_20fast_20edge_20detection_69',['Structured forests for fast edge detection',['../d0/da5/tutorial_ximgproc_prediction.html',1,'tutorial_contrib_root']]],
  ['format_20hdf_20i_20o_70',['The Hierarchical Data Format (hdf) I/O',['../d3/d00/tutorial_table_of_content_hdf.html',1,'tutorial_contrib_root']]],
  ['fourier_20transform_71',['fourier transform',['../d8/d01/tutorial_discrete_fourier_transform.html',1,'Discrete Fourier Transform'],['../dd/d02/tutorial_js_fourier_transform.html',1,'Fourier Transform'],['../de/dbc/tutorial_py_fourier_transform.html',1,'Fourier Transform']]],
  ['framework_20feature2d_20module_72',['2D Features framework (feature2d module)',['../d9/d97/tutorial_table_of_content_features2d.html',1,'tutorial_root']]],
  ['framework_20models_73',['Load Caffe framework models',['../d5/de7/tutorial_dnn_googlenet.html',1,'tutorial_table_of_content_dnn']]],
  ['frequently_20asked_20questions_74',['Frequently Asked Questions',['../d3/d2d/faq.html',1,'']]],
  ['from_20motion_75',['Structure From Motion',['../de/d7c/tutorial_table_of_content_sfm.html',1,'tutorial_contrib_root']]],
  ['from_20other_20doxygen_20projects_76',['Cross referencing OpenCV from other Doxygen projects',['../d3/dff/tutorial_cross_referencing.html',1,'tutorial_table_of_content_introduction']]],
  ['from_20stereo_20images_77',['Depth Map from Stereo Images',['../dd/d53/tutorial_py_depthmap.html',1,'tutorial_py_table_of_contents_calib3d']]],
  ['functionality_20core_20module_78',['The Core Functionality (core module)',['../de/d7a/tutorial_table_of_content_core.html',1,'tutorial_root']]],
  ['functions_79',['functions',['../d5/d45/tutorial_py_contours_more_functions.html',1,'Contours : More Functions'],['../d8/d1c/tutorial_js_contours_more_functions.html',1,'Contours : More Functions']]],
  ['functions_20in_20opencv_80',['Drawing Functions in OpenCV',['../dc/da5/tutorial_py_drawing_functions.html',1,'tutorial_py_table_of_contents_gui']]],
  ['fuzzy_20image_20processing_20tutorials_81',['Fuzzy image processing tutorials',['../d7/d36/tutorial_fuzzy.html',1,'tutorial_contrib_root']]]
];
