var searchData=
[
  ['tables_20and_20time_20measurement_20with_20opencv_0',['How to scan images, lookup tables and time measurement with OpenCV',['../db/da5/tutorial_how_to_scan_images.html',1,'tutorial_table_of_content_core']]],
  ['techniques_1',['Performance Measurement and Improvement Techniques',['../dc/d71/tutorial_py_optimization.html',1,'tutorial_py_table_of_contents_core']]],
  ['tegra_20with_20cuda_2',['Building OpenCV for Tegra with CUDA',['../d6/d15/tutorial_building_tegra_cuda.html',1,'tutorial_table_of_content_introduction']]],
  ['template_20matching_3',['template matching',['../d4/dc6/tutorial_py_template_matching.html',1,'Template Matching'],['../de/da9/tutorial_template_matching.html',1,'Template Matching'],['../d8/dd1/tutorial_js_template_matching.html',1,'Template Matching']]],
  ['template_20parameter_20file_4',['Exporting a template parameter file',['../df/dc0/tutorial_qds_export_parameters.html',1,'tutorial_table_of_content_quasi_dense_stereo']]],
  ['tensor_5',['Anisotropic image segmentation by a gradient structure tensor',['../d4/d70/tutorial_anisotropic_image_segmentation_by_a_gst.html',1,'tutorial_table_of_content_imgproc']]],
  ['tensorflow_20classification_20models_20and_20launch_20with_20opencv_20python_6',['Conversion of TensorFlow Classification Models and Launch with OpenCV Python',['../d1/d8f/tf_cls_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['tensorflow_20detection_20models_20and_20launch_20with_20opencv_20python_7',['Conversion of TensorFlow Detection Models and Launch with OpenCV Python',['../d4/d2f/tf_det_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['tensorflow_20segmentation_20models_20and_20launch_20with_20opencv_8',['Conversion of TensorFlow Segmentation Models and Launch with OpenCV',['../dc/db4/tf_segm_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['tesseract_20master_20installation_20by_20using_20git_20bash_20version_202_2014_201_20and_20cmake_20version_203_209_201_9',['Tesseract (master) installation by using git-bash (version&gt;=2.14.1) and cmake (version &gt;=3.9.1)',['../db/d4c/tutorial_install_tesseract.html',1,'tutorial_table_of_content_text']]],
  ['test_10',['Point Polygon Test',['../dc/d48/tutorial_point_polygon_test.html',1,'tutorial_table_of_content_imgproc']]],
  ['text_20module_11',['Text module',['../d0/dda/tutorial_table_of_content_text.html',1,'tutorial_contrib_root']]],
  ['text_20with_20opencv_12',['Random generator and text with OpenCV',['../df/d61/tutorial_random_generator_and_text.html',1,'tutorial_table_of_content_imgproc']]],
  ['textdetectionmodel_20and_20textrecognitionmodel_13',['High Level API: TextDetectionModel and TextRecognitionModel',['../d4/d43/tutorial_dnn_text_spotting.html',1,'tutorial_table_of_content_dnn']]],
  ['textrecognitionmodel_14',['High Level API: TextDetectionModel and TextRecognitionModel',['../d4/d43/tutorial_dnn_text_spotting.html',1,'tutorial_table_of_content_dnn']]],
  ['textured_20object_15',['Real Time pose estimation of a textured object',['../dc/d2c/tutorial_real_time_pose.html',1,'tutorial_table_of_content_calib3d']]],
  ['the_20basic_20image_20container_16',['Mat - The Basic Image Container',['../d6/d6d/tutorial_mat_the_basic_image_container.html',1,'tutorial_table_of_content_core']]],
  ['the_20cn_20tracker_17',['Customizing the CN Tracker',['../dc/db8/tutorial_customizing_cn_tracker.html',1,'tutorial_contrib_root']]],
  ['the_20color_20palette_18',['Trackbar as the Color Palette',['../d9/dc8/tutorial_py_trackbar.html',1,'tutorial_py_table_of_contents_gui']]],
  ['the_20contrast_20and_20brightness_20of_20an_20image_19',['Changing the contrast and brightness of an image!',['../d3/dc1/tutorial_basic_linear_transform.html',1,'tutorial_table_of_content_core']]],
  ['the_20core_20functionality_20core_20module_20',['The Core Functionality (core module)',['../de/d7a/tutorial_table_of_content_core.html',1,'tutorial_root']]],
  ['the_20detection_20system_21',['Customising and Debugging the detection system',['../d0/de5/tutorial_mcc_debugging_the_system.html',1,'tutorial_table_of_content_mcc']]],
  ['the_20facemark_20api_22',['the facemark api',['../d4/d3e/tutorial_facemark_add_algorithm.html',1,'Adding a new algorithm to the Facemark API'],['../d7/dec/tutorial_facemark_usage.html',1,'Using the Facemark API']]],
  ['the_20facemarkaam_23',['Using the FacemarkAAM',['../d5/dd8/tutorial_facemark_aam.html',1,'tutorial_table_of_content_facemark']]],
  ['the_20gpu_24',['Similarity check (PNSR and SSIM) on the GPU',['../dd/d3d/tutorial_gpu_basics_similarity.html',1,'tutorial_table_of_content_gpu']]],
  ['the_20hierarchical_20data_20format_20hdf_20i_20o_25',['The Hierarchical Data Format (hdf) I/O',['../d3/d00/tutorial_table_of_content_hdf.html',1,'tutorial_contrib_root']]],
  ['the_20homography_20explained_20with_20code_26',['Basic concepts of the homography explained with code',['../d9/dab/tutorial_homography.html',1,'tutorial_table_of_content_features2d']]],
  ['the_20human_20retina_20and_20its_20use_20for_20image_20processing_27',['Discovering the human retina and its use for image processing',['../df/dee/tutorial_table_of_content_retina.html',1,'tutorial_contrib_root']]],
  ['the_20learning_20based_20white_20balance_20algorithm_28',['Training the learning-based white balance algorithm',['../dc/dcb/tutorial_xphoto_training_white_balance.html',1,'tutorial_contrib_root']]],
  ['the_20microsoft_20visual_20studio_29',['How to build applications with OpenCV inside the &quot;Microsoft Visual Studio&quot;',['../dd/d6e/tutorial_windows_visual_studio_opencv.html',1,'tutorial_table_of_content_introduction']]],
  ['the_20opencv_20parallel_5ffor_5f_20to_20parallelize_20your_20code_30',['the opencv parallel_for_ to parallelize your code',['../dc/ddf/tutorial_how_to_use_OpenCV_parallel_for_new.html',1,'How to use the OpenCV parallel_for_ to parallelize your code'],['../d7/dff/tutorial_how_to_use_OpenCV_parallel_for_.html',1,'How to use the OpenCV parallel_for_ to parallelize your code']]],
  ['the_20visual_20studio_20debugger_31',['Image Watch: viewing in-memory images in the Visual Studio debugger',['../d4/d14/tutorial_windows_visual_studio_image_watch.html',1,'tutorial_table_of_content_introduction']]],
  ['theory_32',['F-transform theory',['../db/daf/tutorial_fuzzy_theory.html',1,'tutorial_fuzzy']]],
  ['thresholding_33',['thresholding',['../d7/dd0/tutorial_js_thresholding.html',1,'Image Thresholding'],['../d7/d4d/tutorial_py_thresholding.html',1,'Image Thresholding']]],
  ['thresholding_20operations_34',['Basic Thresholding Operations',['../db/d8e/tutorial_threshold.html',1,'tutorial_table_of_content_imgproc']]],
  ['thresholding_20operations_20using_20inrange_35',['Thresholding Operations using inRange',['../da/d97/tutorial_threshold_inRange.html',1,'tutorial_table_of_content_imgproc']]],
  ['thrust_36',['Using a cv::cuda::GpuMat with thrust',['../d8/db9/tutorial_gpu_thrust_interop.html',1,'tutorial_table_of_content_gpu']]],
  ['time_20measurement_20with_20opencv_37',['How to scan images, lookup tables and time measurement with OpenCV',['../db/da5/tutorial_how_to_scan_images.html',1,'tutorial_table_of_content_core']]],
  ['time_20pose_20estimation_20of_20a_20textured_20object_38',['Real Time pose estimation of a textured object',['../dc/d2c/tutorial_real_time_pose.html',1,'tutorial_table_of_content_calib3d']]],
  ['to_20build_20applications_20with_20opencv_20inside_20the_20microsoft_20visual_20studio_39',['How to build applications with OpenCV inside the &quot;Microsoft Visual Studio&quot;',['../dd/d6e/tutorial_windows_visual_studio_opencv.html',1,'tutorial_table_of_content_introduction']]],
  ['to_20enable_20halide_20backend_20for_20improve_20efficiency_40',['How to enable Halide backend for improve efficiency',['../de/d37/tutorial_dnn_halide.html',1,'tutorial_table_of_content_dnn']]],
  ['to_20find_20a_20known_20object_41',['Features2D + Homography to find a known object',['../d7/dff/tutorial_feature_homography.html',1,'tutorial_table_of_content_features2d']]],
  ['to_20find_20objects_42',['Feature Matching + Homography to find Objects',['../d1/de0/tutorial_py_feature_homography.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['to_20java_20development_43',['Introduction to Java Development',['../d9/d52/tutorial_java_dev_intro.html',1,'tutorial_table_of_content_introduction']]],
  ['to_20julia_20opencv_20binding_44',['Introduction to Julia OpenCV Binding',['../d8/da4/tutorial_julia.html',1,'tutorial_contrib_root']]],
  ['to_20opencv_45',['to opencv',['../da/df6/tutorial_py_table_of_contents_setup.html',1,'Introduction to OpenCV'],['../df/d65/tutorial_table_of_content_introduction.html',1,'Introduction to OpenCV']]],
  ['to_20opencv_20development_20with_20clojure_46',['Introduction to OpenCV Development with Clojure',['../d7/d1e/tutorial_clojure_dev_intro.html',1,'tutorial_table_of_content_introduction']]],
  ['to_20opencv_20js_47',['Introduction to OpenCV.js',['../df/df7/tutorial_js_table_of_contents_setup.html',1,'tutorial_js_root']]],
  ['to_20opencv_20js_20and_20tutorials_48',['Introduction to OpenCV.js and Tutorials',['../df/d0a/tutorial_js_intro.html',1,'tutorial_js_table_of_contents_setup']]],
  ['to_20opencv_20python_20tutorials_49',['Introduction to OpenCV-Python Tutorials',['../d0/de3/tutorial_py_intro.html',1,'tutorial_py_table_of_contents_setup']]],
  ['to_20opencv_20tracker_50',['Introduction to OpenCV Tracker',['../d2/d0a/tutorial_introduction_to_tracker.html',1,'tutorial_contrib_root']]],
  ['to_20our_20applications_51',['Adding a Trackbar to our applications!',['../da/d6a/tutorial_trackbar.html',1,'tutorial_table_of_content_app']]],
  ['to_20plane_20odometry_20algorithm_52',['ICP point-to-plane odometry algorithm',['../d7/dbe/kinfu_icp.html',1,'']]],
  ['to_20principal_20component_20analysis_20pca_53',['Introduction to Principal Component Analysis (PCA)',['../d1/dee/tutorial_introduction_to_pca.html',1,'tutorial_table_of_content_other']]],
  ['to_20run_20custom_20ocr_20model_54',['How to run custom OCR model',['../d9/d1e/tutorial_dnn_OCR.html',1,'tutorial_table_of_content_dnn']]],
  ['to_20run_20deep_20networks_20in_20browser_55',['How to run deep networks in browser',['../d5/d86/tutorial_dnn_javascript.html',1,'tutorial_table_of_content_dnn']]],
  ['to_20run_20deep_20networks_20on_20android_20device_56',['How to run deep networks on Android device',['../de/dfe/tutorial_android_dnn_intro.html',1,'tutorial_table_of_content_introduction']]],
  ['to_20scan_20images_20lookup_20tables_20and_20time_20measurement_20with_20opencv_57',['How to scan images, lookup tables and time measurement with OpenCV',['../db/da5/tutorial_how_to_scan_images.html',1,'tutorial_table_of_content_core']]],
  ['to_20schedule_20your_20network_20for_20halide_20backend_58',['How to schedule your network for Halide backend',['../de/d5d/tutorial_dnn_halide_scheduling.html',1,'tutorial_table_of_content_dnn']]],
  ['to_20sift_20scale_20invariant_20feature_20transform_59',['Introduction to SIFT (Scale-Invariant Feature Transform)',['../da/df5/tutorial_py_sift_intro.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['to_20support_20vector_20machines_60',['Introduction to Support Vector Machines',['../d1/d73/tutorial_introduction_to_svm.html',1,'tutorial_table_of_content_other']]],
  ['to_20surf_20speeded_20up_20robust_20features_61',['Introduction to SURF (Speeded-Up Robust Features)',['../df/dd2/tutorial_py_surf_intro.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['to_20the_20facemark_20api_62',['Adding a new algorithm to the Facemark API',['../d4/d3e/tutorial_facemark_add_algorithm.html',1,'tutorial_table_of_content_facemark']]],
  ['to_20track_63',['Shi-Tomasi Corner Detector &amp; Good Features to Track',['../d4/d8c/tutorial_py_shi_tomasi.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['to_20use_20background_20subtraction_20methods_64',['How to Use Background Subtraction Methods',['../d1/dc5/tutorial_background_subtraction.html',1,'tutorial_table_of_content_other']]],
  ['to_20use_20the_20opencv_20parallel_5ffor_5f_20to_20parallelize_20your_20code_65',['to use the opencv parallel_for_ to parallelize your code',['../dc/ddf/tutorial_how_to_use_OpenCV_parallel_for_new.html',1,'How to use the OpenCV parallel_for_ to parallelize your code'],['../d7/dff/tutorial_how_to_use_OpenCV_parallel_for_.html',1,'How to use the OpenCV parallel_for_ to parallelize your code']]],
  ['to_20your_20application_66',['Add a Trackbar to Your Application',['../d5/df3/tutorial_js_trackbar.html',1,'tutorial_js_table_of_contents_gui']]],
  ['to_20your_20images_67',['Adding borders to your images',['../dc/da3/tutorial_copyMakeBorder.html',1,'tutorial_table_of_content_imgproc']]],
  ['todo_20list_68',['Todo List',['../dd/da0/todo.html',1,'']]],
  ['tomasi_20corner_20detector_69',['Shi-Tomasi corner detector',['../d8/dd8/tutorial_good_features_to_track.html',1,'tutorial_table_of_content_features2d']]],
  ['tomasi_20corner_20detector_20good_20features_20to_20track_70',['Shi-Tomasi Corner Detector &amp; Good Features to Track',['../d4/d8c/tutorial_py_shi_tomasi.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['track_71',['Shi-Tomasi Corner Detector &amp; Good Features to Track',['../d4/d8c/tutorial_py_shi_tomasi.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['trackbar_20as_20the_20color_20palette_72',['Trackbar as the Color Palette',['../d9/dc8/tutorial_py_trackbar.html',1,'tutorial_py_table_of_contents_gui']]],
  ['trackbar_20to_20our_20applications_73',['Adding a Trackbar to our applications!',['../da/d6a/tutorial_trackbar.html',1,'tutorial_table_of_content_app']]],
  ['trackbar_20to_20your_20application_74',['Add a Trackbar to Your Application',['../d5/df3/tutorial_js_trackbar.html',1,'tutorial_js_table_of_contents_gui']]],
  ['tracker_75',['tracker',['../dc/db8/tutorial_customizing_cn_tracker.html',1,'Customizing the CN Tracker'],['../d2/d0a/tutorial_introduction_to_tracker.html',1,'Introduction to OpenCV Tracker']]],
  ['tracking_76',['AKAZE and ORB planar tracking',['../dc/d16/tutorial_akaze_tracking.html',1,'tutorial_table_of_content_features2d']]],
  ['training_77',['training',['../dc/d88/tutorial_traincascade.html',1,'Cascade Classifier Training'],['../d2/d59/tutorial_ximgproc_training.html',1,'Structured forest training']]],
  ['training_20the_20learning_20based_20white_20balance_20algorithm_78',['Training the learning-based white balance algorithm',['../dc/dcb/tutorial_xphoto_training_white_balance.html',1,'tutorial_contrib_root']]],
  ['transfer_20example_79',['Style Transfer Example',['../d7/d2d/tutorial_js_style_transfer.html',1,'tutorial_js_table_of_contents_dnn']]],
  ['transform_80',['transform',['../d8/d01/tutorial_discrete_fourier_transform.html',1,'Discrete Fourier Transform'],['../d3/d1d/tutorial_fuzzy_filtering.html',1,'Filtering using F-transform'],['../de/dbc/tutorial_py_fourier_transform.html',1,'Fourier Transform'],['../dd/d02/tutorial_js_fourier_transform.html',1,'Fourier Transform'],['../d3/de5/tutorial_js_houghcircles.html',1,'Hough Circle Transform'],['../d4/d70/tutorial_hough_circle.html',1,'Hough Circle Transform'],['../da/d53/tutorial_py_houghcircles.html',1,'Hough Circle Transform'],['../d3/de6/tutorial_js_houghlines.html',1,'Hough Line Transform'],['../d6/d10/tutorial_py_houghlines.html',1,'Hough Line Transform'],['../d9/db0/tutorial_hough_lines.html',1,'Hough Line Transform'],['../d3/db8/tutorial_fuzzy_inpainting.html',1,'Inpainting using F-transform'],['../da/df5/tutorial_py_sift_intro.html',1,'Introduction to SIFT (Scale-Invariant Feature Transform)'],['../da/ddc/tutorial_generalized_hough_ballard_guil.html',1,'Object detection with Generalized Ballard and Guil Hough Transform']]],
  ['transform_20and_20watershed_20algorithm_81',['Image Segmentation with Distance Transform and Watershed Algorithm',['../d2/dbd/tutorial_distance_transform.html',1,'tutorial_table_of_content_imgproc']]],
  ['transform_20theory_82',['F-transform theory',['../db/daf/tutorial_fuzzy_theory.html',1,'tutorial_fuzzy']]],
  ['transformations_83',['transformations',['../d4/d61/tutorial_warp_affine.html',1,'Affine Transformations'],['../d3/dbe/tutorial_opening_closing_hats.html',1,'More Morphology Transformations'],['../d9/d61/tutorial_py_morphological_ops.html',1,'Morphological Transformations'],['../d4/d76/tutorial_js_morphological_ops.html',1,'Morphological Transformations'],['../d7/d72/tutorial_transformations.html',1,'Transformations']]],
  ['transformations_20of_20images_84',['transformations of images',['../dd/d52/tutorial_js_geometric_transformations.html',1,'Geometric Transformations of Images'],['../da/d6e/tutorial_py_geometric_transformations.html',1,'Geometric Transformations of Images']]],
  ['transforms_20in_20opencv_85',['Image Transforms in OpenCV',['../dd/dc4/tutorial_py_table_of_contents_transforms.html',1,'tutorial_py_table_of_contents_imgproc']]],
  ['transforms_20in_20opencv_20js_86',['Image Transforms in OpenCV.js',['../db/db3/tutorial_js_table_of_contents_transforms.html',1,'tutorial_js_table_of_contents_imgproc']]],
  ['transition_20guide_87',['Transition guide',['../db/dfa/tutorial_transition_guide.html',1,'tutorial_table_of_content_introduction']]],
  ['tutorial_88',['tutorial',['../db/d56/tutorial_capture_graycode_pattern.html',1,'Capture Gray code pattern tutorial'],['../d0/de8/tutorial_capture_sinusoidal_pattern.html',1,'Capture Sinusoidal pattern tutorial'],['../dc/da9/tutorial_decode_graycode_pattern.html',1,'Decode Gray code pattern tutorial'],['../df/dfa/tutorial_line_descriptor_main.html',1,'Line Features Tutorial'],['../db/d74/tutorial_unwrap_phase_map.html',1,'Phase Unwrapping tutorial']]],
  ['tutorial_20on_20facial_20landmark_20detector_20api_89',['Tutorial on Facial Landmark Detector API',['../d5/d47/tutorial_table_of_content_facemark.html',1,'tutorial_contrib_root']]],
  ['tutorials_90',['tutorials',['../d7/d36/tutorial_fuzzy.html',1,'Fuzzy image processing tutorials'],['../d0/de3/tutorial_py_intro.html',1,'Introduction to OpenCV-Python Tutorials'],['../df/d0a/tutorial_js_intro.html',1,'Introduction to OpenCV.js and Tutorials'],['../d9/df8/tutorial_root.html',1,'OpenCV Tutorials'],['../d6/d00/tutorial_py_root.html',1,'OpenCV-Python Tutorials'],['../d5/d10/tutorial_js_root.html',1,'OpenCV.js Tutorials'],['../d3/d81/tutorial_structured_light.html',1,'Structured Light tutorials']]],
  ['tutorials_20for_20bgsegm_20module_91',['Tutorials for bgsegm module',['../d3/d89/tutorial_table_of_content_bgsegm.html',1,'tutorial_contrib_root']]],
  ['tutorials_20for_20contrib_20modules_92',['Tutorials for contrib modules',['../d3/d81/tutorial_contrib_root.html',1,'']]],
  ['tutorials_20for_20face_20module_93',['Tutorials for face module',['../de/d27/tutorial_table_of_content_face.html',1,'tutorial_contrib_root']]],
  ['tutorials_20ml_20objdetect_20photo_20stitching_20video_94',['Other tutorials (ml, objdetect, photo, stitching, video)',['../d3/dd5/tutorial_table_of_content_other.html',1,'tutorial_root']]],
  ['two_20dimensional_20phase_20maps_95',['Unwrap two-dimensional phase maps',['../d9/dfb/tutorial_unwrap.html',1,'tutorial_unwrap_phase_map']]],
  ['two_20images_20using_20opencv_96',['Adding (blending) two images using OpenCV',['../d5/dc4/tutorial_adding_images.html',1,'tutorial_table_of_content_core']]]
];
