var searchData=
[
  ['back_20projection_0',['Back Projection',['../da/d7f/tutorial_back_projection.html',1,'tutorial_table_of_content_imgproc']]],
  ['backend_1',['How to schedule your network for Halide backend',['../de/d5d/tutorial_dnn_halide_scheduling.html',1,'tutorial_table_of_content_dnn']]],
  ['backend_20for_20improve_20efficiency_2',['How to enable Halide backend for improve efficiency',['../de/d37/tutorial_dnn_halide.html',1,'tutorial_table_of_content_dnn']]],
  ['backend_20in_20ubuntu_3',['Using Wayland highgui-backend in Ubuntu',['../d9/db6/tutorial_wayland_ubuntu.html',1,'tutorial_table_of_content_app']]],
  ['background_20subtraction_4',['background subtraction',['../db/d5c/tutorial_py_bg_subtraction.html',1,'Background Subtraction'],['../de/df4/tutorial_js_bg_subtraction.html',1,'Background Subtraction'],['../d8/d38/tutorial_bgsegm_bg_subtraction.html',1,'Background Subtraction']]],
  ['background_20subtraction_20methods_5',['How to Use Background Subtraction Methods',['../d1/dc5/tutorial_background_subtraction.html',1,'tutorial_table_of_content_other']]],
  ['backprojection_6',['backprojection',['../dd/d4d/tutorial_js_histogram_backprojection.html',1,'Histogram - 3 : Histogram Backprojection'],['../dc/df6/tutorial_py_histogram_backprojection.html',1,'Histogram - 4 : Histogram Backprojection']]],
  ['balance_20algorithm_7',['Training the learning-based white balance algorithm',['../dc/dcb/tutorial_xphoto_training_white_balance.html',1,'tutorial_contrib_root']]],
  ['ballard_20and_20guil_20hough_20transform_8',['Object detection with Generalized Ballard and Guil Hough Transform',['../da/ddc/tutorial_generalized_hough_ballard_guil.html',1,'tutorial_table_of_content_imgproc']]],
  ['barcode_20recognition_9',['Barcode Recognition',['../d6/d25/tutorial_barcode_detect_and_decode.html',1,'tutorial_table_of_content_other']]],
  ['based_20cv_20application_10',['Use OpenCL in Android camera preview based CV application',['../d7/dbd/tutorial_android_ocl_intro.html',1,'tutorial_table_of_content_introduction']]],
  ['based_20face_20detection_20and_20recognition_11',['DNN-based Face Detection And Recognition',['../d0/dd4/tutorial_dnn_face.html',1,'tutorial_table_of_content_dnn']]],
  ['based_20linux_20systems_12',['Cross compilation for ARM based Linux systems',['../d0/d76/tutorial_arm_crosscompile_with_cmake.html',1,'tutorial_table_of_content_introduction']]],
  ['based_20white_20balance_20algorithm_13',['Training the learning-based white balance algorithm',['../dc/dcb/tutorial_xphoto_training_white_balance.html',1,'tutorial_contrib_root']]],
  ['bash_20version_202_2014_201_20and_20cmake_20version_203_209_201_14',['Tesseract (master) installation by using git-bash (version&gt;=2.14.1) and cmake (version &gt;=3.9.1)',['../db/d4c/tutorial_install_tesseract.html',1,'tutorial_table_of_content_text']]],
  ['basic_20algorithms_15',['Detecting colorcheckers using basic algorithms',['../d9/d7e/tutorial_mcc_basic_chart_detection.html',1,'tutorial_table_of_content_mcc']]],
  ['basic_20concepts_20of_20the_20homography_20explained_20with_20code_16',['Basic concepts of the homography explained with code',['../d9/dab/tutorial_homography.html',1,'tutorial_table_of_content_features2d']]],
  ['basic_20drawing_17',['Basic Drawing',['../d3/d96/tutorial_basic_geometric_drawing.html',1,'tutorial_table_of_content_imgproc']]],
  ['basic_20image_20container_18',['Mat - The Basic Image Container',['../d6/d6d/tutorial_mat_the_basic_image_container.html',1,'tutorial_table_of_content_core']]],
  ['basic_20operations_20on_20images_19',['basic operations on images',['../de/d06/tutorial_js_basic_ops.html',1,'Basic Operations on Images'],['../d3/df2/tutorial_py_basic_ops.html',1,'Basic Operations on Images']]],
  ['basic_20thresholding_20operations_20',['Basic Thresholding Operations',['../db/d8e/tutorial_threshold.html',1,'tutorial_table_of_content_imgproc']]],
  ['beautification_20algorithm_20with_20g_20api_21',['Implementing a face beautification algorithm with G-API',['../d4/d48/tutorial_gapi_face_beautification.html',1,'tutorial_table_of_content_gapi']]],
  ['benchmarking_22',['Super-resolution benchmarking',['../dc/d69/tutorial_dnn_superres_benchmark.html',1,'tutorial_table_of_content_dnn_superres']]],
  ['bgsegm_20module_23',['Tutorials for bgsegm module',['../d3/d89/tutorial_table_of_content_bgsegm.html',1,'tutorial_contrib_root']]],
  ['bibliography_24',['Bibliography',['../d0/de3/citelist.html',1,'']]],
  ['binary_20robust_20independent_20elementary_20features_25',['BRIEF (Binary Robust Independent Elementary Features)',['../dc/d7d/tutorial_py_brief.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['binding_26',['Introduction to Julia OpenCV Binding',['../d8/da4/tutorial_julia.html',1,'tutorial_contrib_root']]],
  ['bindings_27',['OpenCV-Python Bindings',['../df/da2/tutorial_py_table_of_contents_bindings.html',1,'tutorial_py_root']]],
  ['bindings_20works_28',['How OpenCV-Python Bindings Works?',['../da/d49/tutorial_py_bindings_basics.html',1,'tutorial_py_table_of_contents_bindings']]],
  ['bioinspired_20module_20retina_20introduction_29',['Bioinspired Module Retina Introduction',['../d2/d94/bioinspired_retina.html',1,'']]],
  ['blending_20two_20images_20using_20opencv_30',['Adding (blending) two images using OpenCV',['../d5/dc4/tutorial_adding_images.html',1,'tutorial_table_of_content_core']]],
  ['boards_31',['boards',['../db/da9/tutorial_aruco_board_detection.html',1,'Detection of ArUco boards'],['../df/d4a/tutorial_charuco_detection.html',1,'Detection of ChArUco Boards']]],
  ['borders_20to_20your_20images_32',['Adding borders to your images',['../dc/da3/tutorial_copyMakeBorder.html',1,'tutorial_table_of_content_imgproc']]],
  ['bounding_20boxes_20and_20circles_20for_20contours_33',['Creating Bounding boxes and circles for contours',['../da/d0c/tutorial_bounding_rects_circles.html',1,'tutorial_table_of_content_imgproc']]],
  ['bounding_20rotated_20boxes_20and_20ellipses_20for_20contours_34',['Creating Bounding rotated boxes and ellipses for contours',['../de/d62/tutorial_bounding_rotated_ellipses.html',1,'tutorial_table_of_content_imgproc']]],
  ['boxes_20and_20circles_20for_20contours_35',['Creating Bounding boxes and circles for contours',['../da/d0c/tutorial_bounding_rects_circles.html',1,'tutorial_table_of_content_imgproc']]],
  ['boxes_20and_20ellipses_20for_20contours_36',['Creating Bounding rotated boxes and ellipses for contours',['../de/d62/tutorial_bounding_rotated_ellipses.html',1,'tutorial_table_of_content_imgproc']]],
  ['brief_37',['ORB (Oriented FAST and Rotated BRIEF)',['../d1/d89/tutorial_py_orb.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['brief_20binary_20robust_20independent_20elementary_20features_38',['BRIEF (Binary Robust Independent Elementary Features)',['../dc/d7d/tutorial_py_brief.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['brightness_20of_20an_20image_39',['Changing the contrast and brightness of an image!',['../d3/dc1/tutorial_basic_linear_transform.html',1,'tutorial_table_of_content_core']]],
  ['browser_40',['How to run deep networks in browser',['../d5/d86/tutorial_dnn_javascript.html',1,'tutorial_table_of_content_dnn']]],
  ['brush_41',['Mouse as a Paint-Brush',['../db/d5b/tutorial_py_mouse_handling.html',1,'tutorial_py_table_of_contents_gui']]],
  ['build_20applications_20with_20opencv_20inside_20the_20microsoft_20visual_20studio_42',['How to build applications with OpenCV inside the &quot;Microsoft Visual Studio&quot;',['../dd/d6e/tutorial_windows_visual_studio_opencv.html',1,'tutorial_table_of_content_introduction']]],
  ['build_20opencv_20js_43',['Build OpenCV.js',['../d4/da1/tutorial_js_setup.html',1,'tutorial_js_table_of_contents_setup']]],
  ['building_20opencv_20for_20tegra_20with_20cuda_44',['Building OpenCV for Tegra with CUDA',['../d6/d15/tutorial_building_tegra_cuda.html',1,'tutorial_table_of_content_introduction']]],
  ['by_20a_20gradient_20structure_20tensor_45',['Anisotropic image segmentation by a gradient structure tensor',['../d4/d70/tutorial_anisotropic_image_segmentation_by_a_gst.html',1,'tutorial_table_of_content_imgproc']]],
  ['by_20using_20git_20bash_20version_202_2014_201_20and_20cmake_20version_203_209_201_46',['Tesseract (master) installation by using git-bash (version&gt;=2.14.1) and cmake (version &gt;=3.9.1)',['../db/d4c/tutorial_install_tesseract.html',1,'tutorial_table_of_content_text']]],
  ['by_20using_20morphological_20operations_47',['Extract horizontal and vertical lines by using morphological operations',['../dd/dd7/tutorial_morph_lines_detection.html',1,'tutorial_table_of_content_imgproc']]]
];
