var searchData=
[
  ['ubuntu_0',['ubuntu',['../d2/de6/tutorial_py_setup_in_ubuntu.html',1,'Install OpenCV-Python in Ubuntu'],['../d9/db6/tutorial_wayland_ubuntu.html',1,'Using Wayland highgui-backend in Ubuntu']]],
  ['ubuntu_20debian_1',['MultiArch cross-compilation with Ubuntu/Debian',['../d3/dd9/tutorial_crosscompile_with_multiarch.html',1,'tutorial_table_of_content_introduction']]],
  ['understanding_20features_2',['Understanding Features',['../df/d54/tutorial_py_features_meaning.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['understanding_20k_20means_20clustering_3',['Understanding K-Means Clustering',['../de/d4d/tutorial_py_kmeans_understanding.html',1,'tutorial_py_kmeans_index']]],
  ['understanding_20k_20nearest_20neighbour_4',['Understanding k-Nearest Neighbour',['../d5/d26/tutorial_py_knn_understanding.html',1,'tutorial_py_knn_index']]],
  ['understanding_20svm_5',['Understanding SVM',['../d4/db1/tutorial_py_svm_basics.html',1,'tutorial_py_svm_index']]],
  ['universal_20intrinsics_6',['Vectorizing your code using Universal Intrinsics',['../d6/dd1/tutorial_univ_intrin.html',1,'tutorial_table_of_content_core']]],
  ['unwrap_20two_20dimensional_20phase_20maps_7',['Unwrap two-dimensional phase maps',['../d9/dfb/tutorial_unwrap.html',1,'tutorial_unwrap_phase_map']]],
  ['unwrapping_20tutorial_8',['Phase Unwrapping tutorial',['../db/d74/tutorial_unwrap_phase_map.html',1,'tutorial_contrib_root']]],
  ['up_20robust_20features_9',['Introduction to SURF (Speeded-Up Robust Features)',['../df/dd2/tutorial_py_surf_intro.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['upscaling_20images_3a_20multi_20output_10',['Upscaling images: multi-output',['../d6/dca/tutorial_dnn_superres_upscale_image_multi.html',1,'tutorial_table_of_content_dnn_superres']]],
  ['upscaling_20images_3a_20single_20output_11',['Upscaling images: single-output',['../d5/d29/tutorial_dnn_superres_upscale_image_single.html',1,'tutorial_table_of_content_dnn_superres']]],
  ['upscaling_20video_12',['Upscaling video',['../de/d7f/tutorial_dnn_superres_upscale_video.html',1,'tutorial_table_of_content_dnn_superres']]],
  ['usac_3a_20improvement_20of_20random_20sample_20consensus_20in_20opencv_13',['USAC: Improvement of Random Sample Consensus in OpenCV',['../de/d3e/tutorial_usac.html',1,'tutorial_table_of_content_calib3d']]],
  ['usage_20with_20openvino_14',['OpenCV usage with OpenVINO',['../dc/dfe/tutorial_dnn_openvino.html',1,'tutorial_table_of_content_dnn']]],
  ['use_20background_20subtraction_20methods_15',['How to Use Background Subtraction Methods',['../d1/dc5/tutorial_background_subtraction.html',1,'tutorial_table_of_content_other']]],
  ['use_20for_20image_20processing_16',['Discovering the human retina and its use for image processing',['../df/dee/tutorial_table_of_content_retina.html',1,'tutorial_contrib_root']]],
  ['use_20opencl_20in_20android_20camera_20preview_20based_20cv_20application_17',['Use OpenCL in Android camera preview based CV application',['../d7/dbd/tutorial_android_ocl_intro.html',1,'tutorial_table_of_content_introduction']]],
  ['use_20the_20opencv_20parallel_5ffor_5f_20to_20parallelize_20your_20code_18',['use the opencv parallel_for_ to parallelize your code',['../dc/ddf/tutorial_how_to_use_OpenCV_parallel_for_new.html',1,'How to use the OpenCV parallel_for_ to parallelize your code'],['../d7/dff/tutorial_how_to_use_OpenCV_parallel_for_.html',1,'How to use the OpenCV parallel_for_ to parallelize your code']]],
  ['using_20a_20cv_3a_3acuda_3a_3agpumat_20with_20thrust_19',['Using a cv::cuda::GpuMat with thrust',['../d8/db9/tutorial_gpu_thrust_interop.html',1,'tutorial_table_of_content_gpu']]],
  ['using_20basic_20algorithms_20',['Detecting colorcheckers using basic algorithms',['../d9/d7e/tutorial_mcc_basic_chart_detection.html',1,'tutorial_table_of_content_mcc']]],
  ['using_20cnns_21',['using cnns',['../d2/da2/tutorial_dnn_objdetect.html',1,'Object Detection using CNNs'],['../d8/df8/tutorial_table_of_content_dnn_superres.html',1,'Super Resolution using CNNs']]],
  ['using_20creative_20senz3d_20and_20other_20intel_20realsense_20sdk_20compatible_20depth_20sensors_22',['Using Creative Senz3D and other Intel RealSense SDK compatible depth sensors',['../db/d08/tutorial_intelperc.html',1,'tutorial_table_of_content_app']]],
  ['using_20depthai_20hardware_20oak_20depth_20sensors_23',['Using DepthAI Hardware / OAK depth sensors',['../df/d88/tutorial_gapi_oak_devices.html',1,'tutorial_table_of_content_gapi']]],
  ['using_20f_20transform_24',['using f transform',['../d3/d1d/tutorial_fuzzy_filtering.html',1,'Filtering using F-transform'],['../d3/db8/tutorial_fuzzy_inpainting.html',1,'Inpainting using F-transform']]],
  ['using_20face_20landmark_20detection_25',['Face swapping using face landmark detection',['../d1/d52/tutorial_face_swapping_face_landmark_detection.html',1,'tutorial_table_of_content_face']]],
  ['using_20git_20bash_20version_202_2014_201_20and_20cmake_20version_203_209_201_26',['Tesseract (master) installation by using git-bash (version&gt;=2.14.1) and cmake (version &gt;=3.9.1)',['../db/d4c/tutorial_install_tesseract.html',1,'tutorial_table_of_content_text']]],
  ['using_20grabcut_20algorithm_27',['using grabcut algorithm',['../dd/dfc/tutorial_js_grabcut.html',1,'Foreground Extraction using GrabCut Algorithm'],['../d8/d83/tutorial_py_grabcut.html',1,'Interactive Foreground Extraction using GrabCut Algorithm']]],
  ['using_20haar_20cascades_28',['using haar cascades',['../d7/d8b/tutorial_py_face_detection.html',1,'Face Detection using Haar Cascades'],['../d2/d99/tutorial_js_face_detection.html',1,'Face Detection using Haar Cascades']]],
  ['using_20inrange_29',['Thresholding Operations using inRange',['../da/d97/tutorial_threshold_inRange.html',1,'tutorial_table_of_content_imgproc']]],
  ['using_20kinect_20and_20other_20openni_20compatible_20depth_20sensors_30',['Using Kinect and other OpenNI compatible depth sensors',['../d7/d6f/tutorial_kinect_openni.html',1,'tutorial_table_of_content_app']]],
  ['using_20knn_31',['OCR of Hand-written Data using kNN',['../d8/d4b/tutorial_py_knn_opencv.html',1,'tutorial_py_knn_index']]],
  ['using_20morphological_20operations_32',['Extract horizontal and vertical lines by using morphological operations',['../dd/dd7/tutorial_morph_lines_detection.html',1,'tutorial_table_of_content_imgproc']]],
  ['using_20multitracker_33',['Using MultiTracker',['../d5/d07/tutorial_multitracker.html',1,'tutorial_contrib_root']]],
  ['using_20neural_20network_34',['Detecting colorcheckers using neural network',['../d4/dc0/tutorial_mcc_chart_detection_enhanced_by_neural_network.html',1,'tutorial_table_of_content_mcc']]],
  ['using_20opencv_35',['Adding (blending) two images using OpenCV',['../d5/dc4/tutorial_adding_images.html',1,'tutorial_table_of_content_core']]],
  ['using_20opencv_20java_20with_20eclipse_36',['Using OpenCV Java with Eclipse',['../d1/d0a/tutorial_java_eclipse.html',1,'tutorial_table_of_content_introduction']]],
  ['using_20opencv_20js_37',['Using OpenCV.js',['../d0/d84/tutorial_js_usage.html',1,'tutorial_js_table_of_contents_setup']]],
  ['using_20opencv_20js_20in_20node_20js_38',['Using OpenCV.js In Node.js',['../dc/de6/tutorial_js_nodejs.html',1,'tutorial_js_table_of_contents_setup']]],
  ['using_20opencv_20with_20eclipse_20plugin_20cdt_39',['Using OpenCV with Eclipse (plugin CDT)',['../d7/d16/tutorial_linux_eclipse.html',1,'tutorial_table_of_content_introduction']]],
  ['using_20opencv_20with_20gcc_20and_20cmake_40',['Using OpenCV with gcc and CMake',['../db/df5/tutorial_linux_gcc_cmake.html',1,'tutorial_table_of_content_introduction']]],
  ['using_20opencv_20with_20gdb_20powered_20ides_41',['Using OpenCV with gdb-powered IDEs',['../d6/d25/tutorial_linux_gdb_pretty_printer.html',1,'tutorial_table_of_content_introduction']]],
  ['using_20orbbec_20astra_203d_20cameras_42',['Using Orbbec Astra 3D cameras',['../d4/d65/tutorial_orbbec_astra.html',1,'tutorial_table_of_content_app']]],
  ['using_20svm_43',['OCR of Hand-written Data using SVM',['../dd/d3b/tutorial_py_svm_opencv.html',1,'tutorial_py_svm_index']]],
  ['using_20the_20facemark_20api_44',['Using the Facemark API',['../d7/dec/tutorial_facemark_usage.html',1,'tutorial_table_of_content_facemark']]],
  ['using_20the_20facemarkaam_45',['Using the FacemarkAAM',['../d5/dd8/tutorial_facemark_aam.html',1,'tutorial_table_of_content_facemark']]],
  ['using_20universal_20intrinsics_46',['Vectorizing your code using Universal Intrinsics',['../d6/dd1/tutorial_univ_intrin.html',1,'tutorial_table_of_content_core']]],
  ['using_20wayland_20highgui_20backend_20in_20ubuntu_47',['Using Wayland highgui-backend in Ubuntu',['../d9/db6/tutorial_wayland_ubuntu.html',1,'tutorial_table_of_content_app']]],
  ['using_20xml_20and_20yaml_20files_48',['File Input and Output using XML and YAML files',['../dd/d74/tutorial_file_input_output_with_xml_yml.html',1,'tutorial_table_of_content_core']]],
  ['utils_20highgui_20imgcodecs_20videoio_20modules_49',['Application utils (highgui, imgcodecs, videoio modules)',['../de/d3d/tutorial_table_of_content_app.html',1,'tutorial_root']]]
];
