var searchData=
[
  ['variables_20reference_0',['OpenCV environment variables reference',['../d6/dea/tutorial_env_reference.html',1,'tutorial_table_of_content_introduction']]],
  ['vector_20machines_1',['Introduction to Support Vector Machines',['../d1/d73/tutorial_introduction_to_svm.html',1,'tutorial_table_of_content_other']]],
  ['vector_20machines_20for_20non_20linearly_20separable_20data_2',['Support Vector Machines for Non-Linearly Separable Data',['../d0/dcc/tutorial_non_linear_svms.html',1,'tutorial_table_of_content_other']]],
  ['vector_20machines_20svm_3',['Support Vector Machines (SVM)',['../d3/d02/tutorial_py_svm_index.html',1,'tutorial_py_table_of_contents_ml']]],
  ['vectorizing_20your_20code_20using_20universal_20intrinsics_4',['Vectorizing your code using Universal Intrinsics',['../d6/dd1/tutorial_univ_intrin.html',1,'tutorial_table_of_content_core']]],
  ['version_202_2014_201_20and_20cmake_20version_203_209_201_5',['Tesseract (master) installation by using git-bash (version&gt;=2.14.1) and cmake (version &gt;=3.9.1)',['../db/d4c/tutorial_install_tesseract.html',1,'tutorial_table_of_content_text']]],
  ['vertical_20lines_20by_20using_20morphological_20operations_6',['Extract horizontal and vertical lines by using morphological operations',['../dd/dd7/tutorial_morph_lines_detection.html',1,'tutorial_table_of_content_imgproc']]],
  ['video_7',['video',['../d8/d3c/tutorial_face_landmark_detection_in_video.html',1,'Face landmark detection in a video'],['../d3/dd5/tutorial_table_of_content_other.html',1,'Other tutorials (ml, objdetect, photo, stitching, video)'],['../de/d7f/tutorial_dnn_superres_upscale_video.html',1,'Upscaling video']]],
  ['video_20analysis_8',['video analysis',['../de/db6/tutorial_js_table_of_contents_video.html',1,'Video Analysis'],['../d3/db0/tutorial_py_table_of_contents_video.html',1,'Video Analysis']]],
  ['video_20analysis_20video_20module_9',['Video analysis (video module)',['../da/dd0/tutorial_table_of_content_video.html',1,'']]],
  ['video_20capture_10',['video capture',['../df/d6c/tutorial_js_face_detection_camera.html',1,'Face Detection in Video Capture'],['../d8/d54/tutorial_js_imgproc_camera.html',1,'Image Processing for Video Capture']]],
  ['video_20i_20o_20with_20opencv_20overview_11',['Video I/O with OpenCV Overview',['../d0/da7/videoio_overview.html',1,'']]],
  ['video_20input_20and_20output_20videoio_20module_12',['Video Input and Output (videoio module)',['../df/d2c/tutorial_table_of_content_videoio.html',1,'']]],
  ['video_20input_20with_20opencv_20and_20similarity_20measurement_13',['Video Input with OpenCV and similarity measurement',['../d5/dc4/tutorial_video_input_psnr_ssim.html',1,'tutorial_table_of_content_app']]],
  ['video_20processing_14',['OpenCV iOS - Video Processing',['../db/dc8/tutorial_video_processing.html',1,'tutorial_table_of_content_ios']]],
  ['video_20with_20opencv_15',['Creating a video with OpenCV',['../d7/d9e/tutorial_video_write.html',1,'tutorial_table_of_content_app']]],
  ['videoio_20module_16',['Video Input and Output (videoio module)',['../df/d2c/tutorial_table_of_content_videoio.html',1,'']]],
  ['videoio_20modules_17',['Application utils (highgui, imgcodecs, videoio modules)',['../de/d3d/tutorial_table_of_content_app.html',1,'tutorial_root']]],
  ['videos_18',['videos',['../dd/d43/tutorial_py_video_display.html',1,'Getting Started with Videos'],['../dd/d00/tutorial_js_video_display.html',1,'Getting Started with Videos']]],
  ['viewing_20in_20memory_20images_20in_20the_20visual_20studio_20debugger_19',['Image Watch: viewing in-memory images in the Visual Studio debugger',['../d4/d14/tutorial_windows_visual_studio_image_watch.html',1,'tutorial_table_of_content_introduction']]],
  ['vision_20',['Retina and real-world vision',['../d3/d86/tutorial_bioinspired_retina_model.html',1,'tutorial_table_of_content_retina']]],
  ['vision_20applications_21',['Interactive Visual Debugging of Computer Vision applications',['../d7/dcf/tutorial_cvv_introduction.html',1,'tutorial_contrib_root']]],
  ['vision_20cuda_20module_22',['GPU-Accelerated Computer Vision (cuda module)',['../da/d2c/tutorial_table_of_content_gpu.html',1,'tutorial_root']]],
  ['visual_20debugging_20of_20computer_20vision_20applications_23',['Interactive Visual Debugging of Computer Vision applications',['../d7/dcf/tutorial_cvv_introduction.html',1,'tutorial_contrib_root']]],
  ['visual_20studio_24',['How to build applications with OpenCV inside the &quot;Microsoft Visual Studio&quot;',['../dd/d6e/tutorial_windows_visual_studio_opencv.html',1,'tutorial_table_of_content_introduction']]],
  ['visual_20studio_20debugger_25',['Image Watch: viewing in-memory images in the Visual Studio debugger',['../d4/d14/tutorial_windows_visual_studio_image_watch.html',1,'tutorial_table_of_content_introduction']]],
  ['viz_26',['viz',['../d5/d7d/tutorial_launching_viz.html',1,'Launching Viz'],['../d7/df9/tutorial_table_of_content_viz.html',1,'OpenCV Viz']]]
];
