var searchData=
[
  ['c_0',['Conversion of PyTorch Classification Models and Launch with OpenCV C++',['../dd/d55/pytorch_cls_c_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['caffe_20framework_20models_1',['Load Caffe framework models',['../d5/de7/tutorial_dnn_googlenet.html',1,'tutorial_table_of_content_dnn']]],
  ['calculation_2',['Histogram Calculation',['../d8/dbc/tutorial_histogram_calculation.html',1,'tutorial_table_of_content_imgproc']]],
  ['calib3d_20module_3',['Camera calibration and 3D reconstruction (calib3d module)',['../d6/d55/tutorial_table_of_content_calib3d.html',1,'tutorial_root']]],
  ['calibration_4',['calibration',['../dc/dbb/tutorial_py_calibration.html',1,'Camera Calibration'],['../d2/d1c/tutorial_multi_camera_main.html',1,'Multi-camera Calibration'],['../dd/d12/tutorial_omnidir_calib_main.html',1,'Omnidirectional Camera Calibration']]],
  ['calibration_20and_203d_20reconstruction_5',['Camera Calibration and 3D Reconstruction',['../d9/db7/tutorial_py_table_of_contents_calib3d.html',1,'tutorial_py_root']]],
  ['calibration_20and_203d_20reconstruction_20calib3d_20module_6',['Camera calibration and 3D reconstruction (calib3d module)',['../d6/d55/tutorial_table_of_content_calib3d.html',1,'tutorial_root']]],
  ['calibration_20application_7',['Interactive camera calibration application',['../d7/d21/tutorial_interactive_calibration.html',1,'tutorial_table_of_content_calib3d']]],
  ['calibration_20pattern_8',['Create calibration pattern',['../da/d0d/tutorial_camera_calibration_pattern.html',1,'tutorial_charuco_detection']]],
  ['calibration_20with_20aruco_20and_20charuco_9',['Calibration with ArUco and ChArUco',['../da/d13/tutorial_aruco_calibration.html',1,'tutorial_table_of_content_objdetect']]],
  ['calibration_20with_20opencv_10',['Camera calibration With OpenCV',['../d4/d94/tutorial_camera_calibration.html',1,'tutorial_table_of_content_calib3d']]],
  ['calibration_20with_20square_20chessboard_11',['Camera calibration with square chessboard',['../dc/d43/tutorial_camera_calibration_square_chess.html',1,'tutorial_table_of_content_calib3d']]],
  ['camera_12',['camera',['../db/d08/tutorial_js_image_classification_with_camera.html',1,'Image Classification Example with Camera'],['../d2/d14/tutorial_js_object_detection_with_camera.html',1,'Object Detection Example with Camera']]],
  ['camera_20calibration_13',['camera calibration',['../dc/dbb/tutorial_py_calibration.html',1,'Camera Calibration'],['../d2/d1c/tutorial_multi_camera_main.html',1,'Multi-camera Calibration'],['../dd/d12/tutorial_omnidir_calib_main.html',1,'Omnidirectional Camera Calibration']]],
  ['camera_20calibration_20and_203d_20reconstruction_14',['Camera Calibration and 3D Reconstruction',['../d9/db7/tutorial_py_table_of_contents_calib3d.html',1,'tutorial_py_root']]],
  ['camera_20calibration_20and_203d_20reconstruction_20calib3d_20module_15',['Camera calibration and 3D reconstruction (calib3d module)',['../d6/d55/tutorial_table_of_content_calib3d.html',1,'tutorial_root']]],
  ['camera_20calibration_20application_16',['Interactive camera calibration application',['../d7/d21/tutorial_interactive_calibration.html',1,'tutorial_table_of_content_calib3d']]],
  ['camera_20calibration_20with_20opencv_17',['Camera calibration With OpenCV',['../d4/d94/tutorial_camera_calibration.html',1,'tutorial_table_of_content_calib3d']]],
  ['camera_20calibration_20with_20square_20chessboard_18',['Camera calibration with square chessboard',['../dc/d43/tutorial_camera_calibration_square_chess.html',1,'tutorial_table_of_content_calib3d']]],
  ['camera_20motion_20estimation_19',['Camera Motion Estimation',['../d5/dab/tutorial_sfm_trajectory_estimation.html',1,'tutorial_table_of_content_sfm']]],
  ['camera_20preview_20based_20cv_20application_20',['Use OpenCL in Android camera preview based CV application',['../d7/dbd/tutorial_android_ocl_intro.html',1,'tutorial_table_of_content_introduction']]],
  ['cameras_21',['Using Orbbec Astra 3D cameras',['../d4/d65/tutorial_orbbec_astra.html',1,'tutorial_table_of_content_app']]],
  ['camshift_22',['camshift',['../df/def/tutorial_js_meanshift.html',1,'Meanshift and Camshift'],['../db/df8/tutorial_py_meanshift.html',1,'Meanshift and Camshift'],['../d7/d00/tutorial_meanshift.html',1,'Meanshift and Camshift']]],
  ['canny_20edge_20detection_23',['canny edge detection',['../d7/de1/tutorial_js_canny.html',1,'Canny Edge Detection'],['../da/d22/tutorial_py_canny.html',1,'Canny Edge Detection']]],
  ['canny_20edge_20detector_24',['Canny Edge Detector',['../da/d5c/tutorial_canny_detector.html',1,'tutorial_table_of_content_imgproc']]],
  ['capture_25',['capture',['../df/d6c/tutorial_js_face_detection_camera.html',1,'Face Detection in Video Capture'],['../d8/d54/tutorial_js_imgproc_camera.html',1,'Image Processing for Video Capture']]],
  ['capture_20gray_20code_20pattern_20tutorial_26',['Capture Gray code pattern tutorial',['../db/d56/tutorial_capture_graycode_pattern.html',1,'tutorial_structured_light']]],
  ['capture_20sinusoidal_20pattern_20tutorial_27',['Capture Sinusoidal pattern tutorial',['../d0/de8/tutorial_capture_sinusoidal_pattern.html',1,'tutorial_structured_light']]],
  ['cascade_20classifier_28',['Cascade Classifier',['../db/d28/tutorial_cascade_classifier.html',1,'tutorial_table_of_content_other']]],
  ['cascade_20classifier_20training_29',['Cascade Classifier Training',['../dc/d88/tutorial_traincascade.html',1,'tutorial_table_of_content_other']]],
  ['cascades_30',['cascades',['../d2/d99/tutorial_js_face_detection.html',1,'Face Detection using Haar Cascades'],['../d7/d8b/tutorial_py_face_detection.html',1,'Face Detection using Haar Cascades']]],
  ['causing_20optical_20illusions_31',['Processing images causing optical illusions',['../d7/d8f/tutorial_bioinspired_retina_illusion.html',1,'tutorial_table_of_content_retina']]],
  ['cdt_32',['Using OpenCV with Eclipse (plugin CDT)',['../d7/d16/tutorial_linux_eclipse.html',1,'tutorial_table_of_content_introduction']]],
  ['changelog_33',['Face module changelog',['../d9/d47/face_changelog.html',1,'']]],
  ['changing_20colorspaces_34',['changing colorspaces',['../db/d64/tutorial_js_colorspaces.html',1,'Changing Colorspaces'],['../df/d9d/tutorial_py_colorspaces.html',1,'Changing Colorspaces']]],
  ['changing_20the_20contrast_20and_20brightness_20of_20an_20image_35',['Changing the contrast and brightness of an image!',['../d3/dc1/tutorial_basic_linear_transform.html',1,'tutorial_table_of_content_core']]],
  ['charuco_36',['Calibration with ArUco and ChArUco',['../da/d13/tutorial_aruco_calibration.html',1,'tutorial_table_of_content_objdetect']]],
  ['charuco_20boards_37',['Detection of ChArUco Boards',['../df/d4a/tutorial_charuco_detection.html',1,'tutorial_table_of_content_objdetect']]],
  ['check_20pnsr_20and_20ssim_20on_20the_20gpu_38',['Similarity check (PNSR and SSIM) on the GPU',['../dd/d3d/tutorial_gpu_basics_similarity.html',1,'tutorial_table_of_content_gpu']]],
  ['chessboard_39',['Camera calibration with square chessboard',['../dc/d43/tutorial_camera_calibration_square_chess.html',1,'tutorial_table_of_content_calib3d']]],
  ['circle_20transform_40',['circle transform',['../d3/de5/tutorial_js_houghcircles.html',1,'Hough Circle Transform'],['../d4/d70/tutorial_hough_circle.html',1,'Hough Circle Transform'],['../da/d53/tutorial_py_houghcircles.html',1,'Hough Circle Transform']]],
  ['circles_20for_20contours_41',['Creating Bounding boxes and circles for contours',['../da/d0c/tutorial_bounding_rects_circles.html',1,'tutorial_table_of_content_imgproc']]],
  ['class_42',['High level stitching API (Stitcher class)',['../d8/d19/tutorial_stitcher.html',1,'tutorial_table_of_content_other']]],
  ['classification_20example_43',['Image Classification Example',['../d3/d6b/tutorial_js_image_classification.html',1,'tutorial_js_table_of_contents_dnn']]],
  ['classification_20example_20with_20camera_44',['Image Classification Example with Camera',['../db/d08/tutorial_js_image_classification_with_camera.html',1,'tutorial_js_table_of_contents_dnn']]],
  ['classification_20models_20and_20launch_20with_20opencv_20c_45',['Conversion of PyTorch Classification Models and Launch with OpenCV C++',['../dd/d55/pytorch_cls_c_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['classification_20models_20and_20launch_20with_20opencv_20python_46',['classification models and launch with opencv python',['../dc/d70/pytorch_cls_tutorial_dnn_conversion.html',1,'Conversion of PyTorch Classification Models and Launch with OpenCV Python'],['../d1/d8f/tf_cls_tutorial_dnn_conversion.html',1,'Conversion of TensorFlow Classification Models and Launch with OpenCV Python']]],
  ['classifier_47',['Cascade Classifier',['../db/d28/tutorial_cascade_classifier.html',1,'tutorial_table_of_content_other']]],
  ['classifier_20training_48',['Cascade Classifier Training',['../dc/d88/tutorial_traincascade.html',1,'tutorial_table_of_content_other']]],
  ['clojure_49',['Introduction to OpenCV Development with Clojure',['../d7/d1e/tutorial_clojure_dev_intro.html',1,'tutorial_table_of_content_introduction']]],
  ['clustering_50',['clustering',['../d9/d70/tutorial_py_kmeans_index.html',1,'K-Means Clustering'],['../de/d4d/tutorial_py_kmeans_understanding.html',1,'Understanding K-Means Clustering']]],
  ['clustering_20in_20opencv_51',['K-Means Clustering in OpenCV',['../d1/d5c/tutorial_py_kmeans_opencv.html',1,'tutorial_py_kmeans_index']]],
  ['cmake_52',['Using OpenCV with gcc and CMake',['../db/df5/tutorial_linux_gcc_cmake.html',1,'tutorial_table_of_content_introduction']]],
  ['cmake_20version_203_209_201_53',['Tesseract (master) installation by using git-bash (version&gt;=2.14.1) and cmake (version &gt;=3.9.1)',['../db/d4c/tutorial_install_tesseract.html',1,'tutorial_table_of_content_text']]],
  ['cn_20tracker_54',['Customizing the CN Tracker',['../dc/db8/tutorial_customizing_cn_tracker.html',1,'tutorial_contrib_root']]],
  ['cnns_55',['cnns',['../d2/da2/tutorial_dnn_objdetect.html',1,'Object Detection using CNNs'],['../d8/df8/tutorial_table_of_content_dnn_superres.html',1,'Super Resolution using CNNs']]],
  ['code_56',['code',['../d9/dab/tutorial_homography.html',1,'Basic concepts of the homography explained with code'],['../d7/dff/tutorial_how_to_use_OpenCV_parallel_for_.html',1,'How to use the OpenCV parallel_for_ to parallelize your code'],['../dc/ddf/tutorial_how_to_use_OpenCV_parallel_for_new.html',1,'How to use the OpenCV parallel_for_ to parallelize your code']]],
  ['code_20pattern_20tutorial_57',['code pattern tutorial',['../db/d56/tutorial_capture_graycode_pattern.html',1,'Capture Gray code pattern tutorial'],['../dc/da9/tutorial_decode_graycode_pattern.html',1,'Decode Gray code pattern tutorial']]],
  ['code_20using_20universal_20intrinsics_58',['Vectorizing your code using Universal Intrinsics',['../d6/dd1/tutorial_univ_intrin.html',1,'tutorial_table_of_content_core']]],
  ['color_20conversions_59',['Color conversions',['../de/d25/imgproc_color_conversions.html',1,'']]],
  ['color_20correction_20model_60',['color correction model',['../db/db3/tutorial_table_of_content_ccm.html',1,'Color Correction Model'],['../d1/dc1/tutorial_ccm_color_correction_model.html',1,'Color Correction Model']]],
  ['color_20palette_61',['Trackbar as the Color Palette',['../d9/dc8/tutorial_py_trackbar.html',1,'tutorial_py_table_of_contents_gui']]],
  ['colorchecker_20detection_62',['ColorChecker Detection',['../d0/d81/tutorial_table_of_content_mcc.html',1,'tutorial_contrib_root']]],
  ['colorcheckers_20using_20basic_20algorithms_63',['Detecting colorcheckers using basic algorithms',['../d9/d7e/tutorial_mcc_basic_chart_detection.html',1,'tutorial_table_of_content_mcc']]],
  ['colorcheckers_20using_20neural_20network_64',['Detecting colorcheckers using neural network',['../d4/dc0/tutorial_mcc_chart_detection_enhanced_by_neural_network.html',1,'tutorial_table_of_content_mcc']]],
  ['colorspaces_65',['colorspaces',['../db/d64/tutorial_js_colorspaces.html',1,'Changing Colorspaces'],['../df/d9d/tutorial_py_colorspaces.html',1,'Changing Colorspaces']]],
  ['comparison_66',['Histogram Comparison',['../d8/dc8/tutorial_histogram_comparison.html',1,'tutorial_table_of_content_imgproc']]],
  ['compatible_20depth_20sensors_67',['compatible depth sensors',['../db/d08/tutorial_intelperc.html',1,'Using Creative Senz3D and other Intel RealSense SDK compatible depth sensors'],['../d7/d6f/tutorial_kinect_openni.html',1,'Using Kinect and other OpenNI compatible depth sensors']]],
  ['compilation_20for_20arm_20based_20linux_20systems_68',['Cross compilation for ARM based Linux systems',['../d0/d76/tutorial_arm_crosscompile_with_cmake.html',1,'tutorial_table_of_content_introduction']]],
  ['compilation_20with_20ubuntu_20debian_69',['MultiArch cross-compilation with Ubuntu/Debian',['../d3/dd9/tutorial_crosscompile_with_multiarch.html',1,'tutorial_table_of_content_introduction']]],
  ['component_20analysis_20pca_70',['Introduction to Principal Component Analysis (PCA)',['../d1/dee/tutorial_introduction_to_pca.html',1,'tutorial_table_of_content_other']]],
  ['computation_71',['Perspective-n-Point (PnP) pose computation',['../d5/d1f/calib3d_solvePnP.html',1,'']]],
  ['computational_20photography_72',['Computational Photography',['../d0/d07/tutorial_py_table_of_contents_photo.html',1,'tutorial_py_root']]],
  ['computational_20photography_20photo_20module_73',['Computational photography (photo module)',['../da/de7/tutorial_table_of_content_photo.html',1,'']]],
  ['computer_20vision_20applications_74',['Interactive Visual Debugging of Computer Vision applications',['../d7/dcf/tutorial_cvv_introduction.html',1,'tutorial_contrib_root']]],
  ['computer_20vision_20cuda_20module_75',['GPU-Accelerated Computer Vision (cuda module)',['../da/d2c/tutorial_table_of_content_gpu.html',1,'tutorial_root']]],
  ['concepts_20of_20the_20homography_20explained_20with_20code_76',['Basic concepts of the homography explained with code',['../d9/dab/tutorial_homography.html',1,'tutorial_table_of_content_features2d']]],
  ['configuration_20options_20reference_77',['OpenCV configuration options reference',['../db/d05/tutorial_config_reference.html',1,'tutorial_table_of_content_introduction']]],
  ['consensus_20in_20opencv_78',['USAC: Improvement of Random Sample Consensus in OpenCV',['../de/d3e/tutorial_usac.html',1,'tutorial_table_of_content_calib3d']]],
  ['container_79',['Mat - The Basic Image Container',['../d6/d6d/tutorial_mat_the_basic_image_container.html',1,'tutorial_table_of_content_core']]],
  ['contour_20features_80',['contour features',['../dc/dcf/tutorial_js_contour_features.html',1,'Contour Features'],['../dd/d49/tutorial_py_contour_features.html',1,'Contour Features']]],
  ['contour_20properties_81',['contour properties',['../d1/d32/tutorial_py_contour_properties.html',1,'Contour Properties'],['../da/dc1/tutorial_js_contour_properties.html',1,'Contour Properties']]],
  ['contours_82',['contours',['../da/d0c/tutorial_bounding_rects_circles.html',1,'Creating Bounding boxes and circles for contours'],['../de/d62/tutorial_bounding_rotated_ellipses.html',1,'Creating Bounding rotated boxes and ellipses for contours']]],
  ['contours_20_3a_20getting_20started_83',['contours : getting started',['../d5/daa/tutorial_js_contours_begin.html',1,'Contours : Getting Started'],['../d4/d73/tutorial_py_contours_begin.html',1,'Contours : Getting Started']]],
  ['contours_20_3a_20more_20functions_84',['contours : more functions',['../d5/d45/tutorial_py_contours_more_functions.html',1,'Contours : More Functions'],['../d8/d1c/tutorial_js_contours_more_functions.html',1,'Contours : More Functions']]],
  ['contours_20hierarchy_85',['contours hierarchy',['../d9/d8b/tutorial_py_contours_hierarchy.html',1,'Contours Hierarchy'],['../da/d0a/tutorial_js_contours_hierarchy.html',1,'Contours Hierarchy']]],
  ['contours_20in_20opencv_86',['contours in opencv',['../d3/d05/tutorial_py_table_of_contents_contours.html',1,'Contours in OpenCV'],['../de/d09/tutorial_table_of_contents_contours.html',1,'Contours in OpenCV']]],
  ['contours_20in_20opencv_20js_87',['Contours in OpenCV.js',['../d0/d43/tutorial_js_table_of_contents_contours.html',1,'tutorial_js_table_of_contents_imgproc']]],
  ['contours_20in_20your_20image_88',['Finding contours in your image',['../df/d0d/tutorial_find_contours.html',1,'tutorial_table_of_content_imgproc']]],
  ['contrast_20and_20brightness_20of_20an_20image_89',['Changing the contrast and brightness of an image!',['../d3/dc1/tutorial_basic_linear_transform.html',1,'tutorial_table_of_content_core']]],
  ['contrib_20modules_90',['Tutorials for contrib modules',['../d3/d81/tutorial_contrib_root.html',1,'']]],
  ['conversion_20of_20pytorch_20classification_20models_20and_20launch_20with_20opencv_20c_91',['Conversion of PyTorch Classification Models and Launch with OpenCV C++',['../dd/d55/pytorch_cls_c_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['conversion_20of_20pytorch_20classification_20models_20and_20launch_20with_20opencv_20python_92',['Conversion of PyTorch Classification Models and Launch with OpenCV Python',['../dc/d70/pytorch_cls_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['conversion_20of_20pytorch_20segmentation_20models_20and_20launch_20with_20opencv_93',['Conversion of PyTorch Segmentation Models and Launch with OpenCV',['../d7/d9a/pytorch_segm_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['conversion_20of_20tensorflow_20classification_20models_20and_20launch_20with_20opencv_20python_94',['Conversion of TensorFlow Classification Models and Launch with OpenCV Python',['../d1/d8f/tf_cls_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['conversion_20of_20tensorflow_20detection_20models_20and_20launch_20with_20opencv_20python_95',['Conversion of TensorFlow Detection Models and Launch with OpenCV Python',['../d4/d2f/tf_det_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['conversion_20of_20tensorflow_20segmentation_20models_20and_20launch_20with_20opencv_96',['Conversion of TensorFlow Segmentation Models and Launch with OpenCV',['../dc/db4/tf_segm_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['conversions_97',['Color conversions',['../de/d25/imgproc_color_conversions.html',1,'']]],
  ['convex_20hull_98',['Convex Hull',['../d7/d1d/tutorial_hull.html',1,'tutorial_table_of_content_imgproc']]],
  ['core_20functionality_20core_20module_99',['The Core Functionality (core module)',['../de/d7a/tutorial_table_of_content_core.html',1,'tutorial_root']]],
  ['core_20operations_100',['core operations',['../d1/d78/tutorial_js_table_of_contents_core.html',1,'Core Operations'],['../d7/d16/tutorial_py_table_of_contents_core.html',1,'Core Operations']]],
  ['corner_20detection_101',['corner detection',['../df/d0c/tutorial_py_fast.html',1,'FAST Algorithm for Corner Detection'],['../dc/d0d/tutorial_py_features_harris.html',1,'Harris Corner Detection']]],
  ['corner_20detector_102',['corner detector',['../d9/dbc/tutorial_generic_corner_detector.html',1,'Creating your own corner detector'],['../d4/d7d/tutorial_harris_detector.html',1,'Harris corner detector'],['../d8/dd8/tutorial_good_features_to_track.html',1,'Shi-Tomasi corner detector']]],
  ['corner_20detector_20good_20features_20to_20track_103',['Shi-Tomasi Corner Detector &amp; Good Features to Track',['../d4/d8c/tutorial_py_shi_tomasi.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['corners_20location_20in_20subpixels_104',['Detecting corners location in subpixels',['../dd/d92/tutorial_corner_subpixels.html',1,'tutorial_table_of_content_features2d']]],
  ['correction_20model_105',['correction model',['../d1/dc1/tutorial_ccm_color_correction_model.html',1,'Color Correction Model'],['../db/db3/tutorial_table_of_content_ccm.html',1,'Color Correction Model']]],
  ['create_20calibration_20pattern_106',['Create calibration pattern',['../da/d0d/tutorial_camera_calibration_pattern.html',1,'tutorial_charuco_detection']]],
  ['creating_20a_203d_20histogram_107',['Creating a 3D histogram',['../d1/d1d/tutorial_histo3D.html',1,'tutorial_table_of_content_viz']]],
  ['creating_20a_20video_20with_20opencv_108',['Creating a video with OpenCV',['../d7/d9e/tutorial_video_write.html',1,'tutorial_table_of_content_app']]],
  ['creating_20bounding_20boxes_20and_20circles_20for_20contours_109',['Creating Bounding boxes and circles for contours',['../da/d0c/tutorial_bounding_rects_circles.html',1,'tutorial_table_of_content_imgproc']]],
  ['creating_20bounding_20rotated_20boxes_20and_20ellipses_20for_20contours_110',['Creating Bounding rotated boxes and ellipses for contours',['../de/d62/tutorial_bounding_rotated_ellipses.html',1,'tutorial_table_of_content_imgproc']]],
  ['creating_20groups_111',['Creating Groups',['../d1/d8b/tutorial_hdf_create_groups.html',1,'tutorial_table_of_content_hdf']]],
  ['creating_20widgets_112',['Creating Widgets',['../d2/d64/tutorial_creating_widgets.html',1,'tutorial_table_of_content_viz']]],
  ['creating_20writing_20and_20reading_20datasets_113',['Creating, Writing and Reading Datasets',['../d4/d93/tutorial_hdf_create_read_write_datasets.html',1,'tutorial_table_of_content_hdf']]],
  ['creating_20your_20own_20corner_20detector_114',['Creating your own corner detector',['../d9/dbc/tutorial_generic_corner_detector.html',1,'tutorial_table_of_content_features2d']]],
  ['creative_20senz3d_20and_20other_20intel_20realsense_20sdk_20compatible_20depth_20sensors_115',['Using Creative Senz3D and other Intel RealSense SDK compatible depth sensors',['../db/d08/tutorial_intelperc.html',1,'tutorial_table_of_content_app']]],
  ['cross_20compilation_20for_20arm_20based_20linux_20systems_116',['Cross compilation for ARM based Linux systems',['../d0/d76/tutorial_arm_crosscompile_with_cmake.html',1,'tutorial_table_of_content_introduction']]],
  ['cross_20compilation_20with_20ubuntu_20debian_117',['MultiArch cross-compilation with Ubuntu/Debian',['../d3/dd9/tutorial_crosscompile_with_multiarch.html',1,'tutorial_table_of_content_introduction']]],
  ['cross_20referencing_20opencv_20from_20other_20doxygen_20projects_118',['Cross referencing OpenCV from other Doxygen projects',['../d3/dff/tutorial_cross_referencing.html',1,'tutorial_table_of_content_introduction']]],
  ['cuda_119',['Building OpenCV for Tegra with CUDA',['../d6/d15/tutorial_building_tegra_cuda.html',1,'tutorial_table_of_content_introduction']]],
  ['cuda_20module_120',['GPU-Accelerated Computer Vision (cuda module)',['../da/d2c/tutorial_table_of_content_gpu.html',1,'tutorial_root']]],
  ['cuda_20module_20introduction_121',['CUDA Module Introduction',['../d2/dbc/cuda_intro.html',1,'']]],
  ['custom_20deep_20learning_20layers_20support_122',['Custom deep learning layers support',['../dc/db1/tutorial_dnn_custom_layers.html',1,'tutorial_table_of_content_dnn']]],
  ['custom_20ocr_20model_123',['How to run custom OCR model',['../d9/d1e/tutorial_dnn_OCR.html',1,'tutorial_table_of_content_dnn']]],
  ['customising_20and_20debugging_20the_20detection_20system_124',['Customising and Debugging the detection system',['../d0/de5/tutorial_mcc_debugging_the_system.html',1,'tutorial_table_of_content_mcc']]],
  ['customizing_20the_20cn_20tracker_125',['Customizing the CN Tracker',['../dc/db8/tutorial_customizing_cn_tracker.html',1,'tutorial_contrib_root']]],
  ['cv_20application_126',['Use OpenCL in Android camera preview based CV application',['../d7/dbd/tutorial_android_ocl_intro.html',1,'tutorial_table_of_content_introduction']]],
  ['cv_3a_3acuda_3a_3agpumat_20with_20thrust_127',['Using a cv::cuda::GpuMat with thrust',['../d8/db9/tutorial_gpu_thrust_interop.html',1,'tutorial_table_of_content_gpu']]]
];
