var searchData=
[
  ['landmark_20detection_0',['Face swapping using face landmark detection',['../d1/d52/tutorial_face_swapping_face_landmark_detection.html',1,'tutorial_table_of_content_face']]],
  ['landmark_20detection_20in_20a_20video_1',['Face landmark detection in a video',['../d8/d3c/tutorial_face_landmark_detection_in_video.html',1,'tutorial_table_of_content_face']]],
  ['landmark_20detection_20in_20an_20image_2',['Face landmark detection in an image',['../d2/d42/tutorial_face_landmark_detection_in_an_image.html',1,'tutorial_table_of_content_face']]],
  ['landmark_20detector_20api_3',['Tutorial on Facial Landmark Detector API',['../d5/d47/tutorial_table_of_content_facemark.html',1,'tutorial_contrib_root']]],
  ['laplace_20operator_4',['Laplace Operator',['../d5/db5/tutorial_laplace_operator.html',1,'tutorial_table_of_content_imgproc']]],
  ['launch_20with_20opencv_5',['launch with opencv',['../d7/d9a/pytorch_segm_tutorial_dnn_conversion.html',1,'Conversion of PyTorch Segmentation Models and Launch with OpenCV'],['../dc/db4/tf_segm_tutorial_dnn_conversion.html',1,'Conversion of TensorFlow Segmentation Models and Launch with OpenCV']]],
  ['launch_20with_20opencv_20c_6',['Conversion of PyTorch Classification Models and Launch with OpenCV C++',['../dd/d55/pytorch_cls_c_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['launch_20with_20opencv_20python_7',['launch with opencv python',['../dc/d70/pytorch_cls_tutorial_dnn_conversion.html',1,'Conversion of PyTorch Classification Models and Launch with OpenCV Python'],['../d1/d8f/tf_cls_tutorial_dnn_conversion.html',1,'Conversion of TensorFlow Classification Models and Launch with OpenCV Python'],['../d4/d2f/tf_det_tutorial_dnn_conversion.html',1,'Conversion of TensorFlow Detection Models and Launch with OpenCV Python']]],
  ['launching_20viz_8',['Launching Viz',['../d5/d7d/tutorial_launching_viz.html',1,'tutorial_table_of_content_viz']]],
  ['layers_20support_9',['Custom deep learning layers support',['../dc/db1/tutorial_dnn_custom_layers.html',1,'tutorial_table_of_content_dnn']]],
  ['learning_10',['Machine Learning',['../d6/de2/tutorial_py_table_of_contents_ml.html',1,'tutorial_py_root']]],
  ['learning_20based_20white_20balance_20algorithm_11',['Training the learning-based white balance algorithm',['../dc/dcb/tutorial_xphoto_training_white_balance.html',1,'tutorial_contrib_root']]],
  ['learning_20layers_20support_12',['Custom deep learning layers support',['../dc/db1/tutorial_dnn_custom_layers.html',1,'tutorial_table_of_content_dnn']]],
  ['learning_20ml_20module_13',['Machine Learning (ml module)',['../d1/d69/tutorial_table_of_content_ml.html',1,'']]],
  ['learning_20overview_14',['Machine Learning Overview',['../dc/dd6/ml_intro.html',1,'']]],
  ['level_20api_3a_20textdetectionmodel_20and_20textrecognitionmodel_15',['High Level API: TextDetectionModel and TextRecognitionModel',['../d4/d43/tutorial_dnn_text_spotting.html',1,'tutorial_table_of_content_dnn']]],
  ['level_20design_20overview_16',['High-level design overview',['../de/d4d/gapi_hld.html',1,'gapi']]],
  ['level_20gui_20and_20media_20highgui_20module_17',['High Level GUI and Media (highgui module)',['../d0/de2/tutorial_table_of_content_highgui.html',1,'']]],
  ['level_20stitching_20api_20stitcher_20class_18',['High level stitching API (Stitcher class)',['../d8/d19/tutorial_stitcher.html',1,'tutorial_table_of_content_other']]],
  ['light_20tutorials_19',['Structured Light tutorials',['../d3/d81/tutorial_structured_light.html',1,'tutorial_contrib_root']]],
  ['line_20features_20tutorial_20',['Line Features Tutorial',['../df/dfa/tutorial_line_descriptor_main.html',1,'tutorial_contrib_root']]],
  ['line_20transform_21',['line transform',['../d9/db0/tutorial_hough_lines.html',1,'Hough Line Transform'],['../d6/d10/tutorial_py_houghlines.html',1,'Hough Line Transform'],['../d3/de6/tutorial_js_houghlines.html',1,'Hough Line Transform']]],
  ['linear_20filters_22',['Making your own linear filters!',['../d4/dbd/tutorial_filter_2d.html',1,'tutorial_table_of_content_imgproc']]],
  ['linearly_20separable_20data_23',['Support Vector Machines for Non-Linearly Separable Data',['../d0/dcc/tutorial_non_linear_svms.html',1,'tutorial_table_of_content_other']]],
  ['lines_20by_20using_20morphological_20operations_24',['Extract horizontal and vertical lines by using morphological operations',['../dd/dd7/tutorial_morph_lines_detection.html',1,'tutorial_table_of_content_imgproc']]],
  ['linux_25',['Installation in Linux',['../d7/d9f/tutorial_linux_install.html',1,'tutorial_table_of_content_introduction']]],
  ['linux_20systems_26',['Cross compilation for ARM based Linux systems',['../d0/d76/tutorial_arm_crosscompile_with_cmake.html',1,'tutorial_table_of_content_introduction']]],
  ['list_27',['list',['../da/d58/deprecated.html',1,'Deprecated List'],['../dd/da0/todo.html',1,'Todo List']]],
  ['load_20caffe_20framework_20models_28',['Load Caffe framework models',['../d5/de7/tutorial_dnn_googlenet.html',1,'tutorial_table_of_content_dnn']]],
  ['load_20modify_20and_20save_20an_20image_29',['Load, Modify, and Save an Image',['../db/d64/tutorial_load_save_image.html',1,'']]],
  ['local_20features_20matching_30',['AKAZE local features matching',['../db/d70/tutorial_akaze_matching.html',1,'tutorial_table_of_content_features2d']]],
  ['location_20in_20subpixels_31',['Detecting corners location in subpixels',['../dd/d92/tutorial_corner_subpixels.html',1,'tutorial_table_of_content_features2d']]],
  ['lookup_20tables_20and_20time_20measurement_20with_20opencv_32',['How to scan images, lookup tables and time measurement with OpenCV',['../db/da5/tutorial_how_to_scan_images.html',1,'tutorial_table_of_content_core']]]
];
