var searchData=
[
  ['paint_20brush_0',['Mouse as a Paint-Brush',['../db/d5b/tutorial_py_mouse_handling.html',1,'tutorial_py_table_of_contents_gui']]],
  ['painting_20effect_1',['Oil painting effect',['../dd/d8c/tutorial_xphoto_oil_painting_effect.html',1,'tutorial_contrib_root']]],
  ['palette_2',['Trackbar as the Color Palette',['../d9/dc8/tutorial_py_trackbar.html',1,'tutorial_py_table_of_contents_gui']]],
  ['parallel_5ffor_5f_20to_20parallelize_20your_20code_3',['parallel_for_ to parallelize your code',['../d7/dff/tutorial_how_to_use_OpenCV_parallel_for_.html',1,'How to use the OpenCV parallel_for_ to parallelize your code'],['../dc/ddf/tutorial_how_to_use_OpenCV_parallel_for_new.html',1,'How to use the OpenCV parallel_for_ to parallelize your code']]],
  ['parallelize_20your_20code_4',['parallelize your code',['../d7/dff/tutorial_how_to_use_OpenCV_parallel_for_.html',1,'How to use the OpenCV parallel_for_ to parallelize your code'],['../dc/ddf/tutorial_how_to_use_OpenCV_parallel_for_new.html',1,'How to use the OpenCV parallel_for_ to parallelize your code']]],
  ['parameter_20file_5',['Exporting a template parameter file',['../df/dc0/tutorial_qds_export_parameters.html',1,'tutorial_table_of_content_quasi_dense_stereo']]],
  ['pattern_6',['Create calibration pattern',['../da/d0d/tutorial_camera_calibration_pattern.html',1,'tutorial_charuco_detection']]],
  ['pattern_20tutorial_7',['pattern tutorial',['../db/d56/tutorial_capture_graycode_pattern.html',1,'Capture Gray code pattern tutorial'],['../d0/de8/tutorial_capture_sinusoidal_pattern.html',1,'Capture Sinusoidal pattern tutorial'],['../dc/da9/tutorial_decode_graycode_pattern.html',1,'Decode Gray code pattern tutorial']]],
  ['pca_8',['Introduction to Principal Component Analysis (PCA)',['../d1/dee/tutorial_introduction_to_pca.html',1,'tutorial_table_of_content_other']]],
  ['performance_20measurement_20and_20improvement_20techniques_9',['Performance Measurement and Improvement Techniques',['../dc/d71/tutorial_py_optimization.html',1,'tutorial_py_table_of_contents_core']]],
  ['periodic_20noise_20removing_20filter_10',['Periodic Noise Removing Filter',['../d2/d0b/tutorial_periodic_noise_removing_filter.html',1,'tutorial_table_of_content_imgproc']]],
  ['perspective_20n_20point_20pnp_20pose_20computation_11',['Perspective-n-Point (PnP) pose computation',['../d5/d1f/calib3d_solvePnP.html',1,'']]],
  ['phase_20maps_12',['Unwrap two-dimensional phase maps',['../d9/dfb/tutorial_unwrap.html',1,'tutorial_unwrap_phase_map']]],
  ['phase_20unwrapping_20tutorial_13',['Phase Unwrapping tutorial',['../db/d74/tutorial_unwrap_phase_map.html',1,'tutorial_contrib_root']]],
  ['photo_20module_14',['Computational photography (photo module)',['../da/de7/tutorial_table_of_content_photo.html',1,'']]],
  ['photo_20stitching_20video_15',['Other tutorials (ml, objdetect, photo, stitching, video)',['../d3/dd5/tutorial_table_of_content_other.html',1,'tutorial_root']]],
  ['photography_16',['Computational Photography',['../d0/d07/tutorial_py_table_of_contents_photo.html',1,'tutorial_py_root']]],
  ['photography_20photo_20module_17',['Computational photography (photo module)',['../da/de7/tutorial_table_of_content_photo.html',1,'']]],
  ['pipeline_20with_20g_20api_18',['Face analytics pipeline with G-API',['../d8/d24/tutorial_gapi_interactive_face_detection.html',1,'tutorial_table_of_content_gapi']]],
  ['planar_20objects_19',['Detection of planar objects',['../dd/dd4/tutorial_detection_of_planar_objects.html',1,'tutorial_table_of_content_features2d']]],
  ['planar_20tracking_20',['AKAZE and ORB planar tracking',['../dc/d16/tutorial_akaze_tracking.html',1,'tutorial_table_of_content_features2d']]],
  ['plane_20odometry_20algorithm_21',['ICP point-to-plane odometry algorithm',['../d7/dbe/kinfu_icp.html',1,'']]],
  ['plot_20analyze_22',['plot analyze',['../d7/d32/tutorial_js_histogram_begins.html',1,'Histograms - 1 : Find, Plot, Analyze !!!'],['../d1/db7/tutorial_py_histogram_begins.html',1,'Histograms - 1 : Find, Plot, Analyze !!!']]],
  ['plugin_20cdt_23',['Using OpenCV with Eclipse (plugin CDT)',['../d7/d16/tutorial_linux_eclipse.html',1,'tutorial_table_of_content_introduction']]],
  ['pnp_20pose_20computation_24',['Perspective-n-Point (PnP) pose computation',['../d5/d1f/calib3d_solvePnP.html',1,'']]],
  ['pnsr_20and_20ssim_20on_20the_20gpu_25',['Similarity check (PNSR and SSIM) on the GPU',['../dd/d3d/tutorial_gpu_basics_similarity.html',1,'tutorial_table_of_content_gpu']]],
  ['point_20pnp_20pose_20computation_26',['Perspective-n-Point (PnP) pose computation',['../d5/d1f/calib3d_solvePnP.html',1,'']]],
  ['point_20polygon_20test_27',['Point Polygon Test',['../dc/d48/tutorial_point_polygon_test.html',1,'tutorial_table_of_content_imgproc']]],
  ['point_20to_20plane_20odometry_20algorithm_28',['ICP point-to-plane odometry algorithm',['../d7/dbe/kinfu_icp.html',1,'']]],
  ['polygon_20test_29',['Point Polygon Test',['../dc/d48/tutorial_point_polygon_test.html',1,'tutorial_table_of_content_imgproc']]],
  ['porting_20anisotropic_20image_20segmentation_20on_20g_20api_30',['Porting anisotropic image segmentation on G-API',['../d3/d7a/tutorial_gapi_anisotropic_segmentation.html',1,'tutorial_table_of_content_gapi']]],
  ['pose_20computation_31',['Perspective-n-Point (PnP) pose computation',['../d5/d1f/calib3d_solvePnP.html',1,'']]],
  ['pose_20estimation_32',['Pose Estimation',['../d7/d53/tutorial_py_pose.html',1,'tutorial_py_table_of_contents_calib3d']]],
  ['pose_20estimation_20example_33',['Pose Estimation Example',['../d1/d0d/tutorial_js_pose_estimation.html',1,'tutorial_js_table_of_contents_dnn']]],
  ['pose_20estimation_20of_20a_20textured_20object_34',['Real Time pose estimation of a textured object',['../dc/d2c/tutorial_real_time_pose.html',1,'tutorial_table_of_content_calib3d']]],
  ['pose_20of_20a_20widget_35',['Pose of a widget',['../d8/df0/tutorial_widget_pose.html',1,'tutorial_table_of_content_viz']]],
  ['post_20filtering_36',['Disparity map post-filtering',['../d3/d14/tutorial_ximgproc_disparity_filtering.html',1,'tutorial_contrib_root']]],
  ['powered_20ides_37',['Using OpenCV with gdb-powered IDEs',['../d6/d25/tutorial_linux_gdb_pretty_printer.html',1,'tutorial_table_of_content_introduction']]],
  ['preview_20based_20cv_20application_38',['Use OpenCL in Android camera preview based CV application',['../d7/dbd/tutorial_android_ocl_intro.html',1,'tutorial_table_of_content_introduction']]],
  ['principal_20component_20analysis_20pca_39',['Introduction to Principal Component Analysis (PCA)',['../d1/dee/tutorial_introduction_to_pca.html',1,'tutorial_table_of_content_other']]],
  ['processing_40',['processing',['../d9/d56/tutorial_ascend_npu_image_processing.html',1,'Ascend NPU Image Processing'],['../df/dee/tutorial_table_of_content_retina.html',1,'Discovering the human retina and its use for image processing'],['../d2/df0/tutorial_js_table_of_contents_imgproc.html',1,'Image Processing'],['../d3/def/tutorial_image_manipulation.html',1,'OpenCV iOS - Image Processing'],['../db/dc8/tutorial_video_processing.html',1,'OpenCV iOS - Video Processing']]],
  ['processing_20for_20video_20capture_41',['Image Processing for Video Capture',['../d8/d54/tutorial_js_imgproc_camera.html',1,'tutorial_js_table_of_contents_imgproc']]],
  ['processing_20images_20causing_20optical_20illusions_42',['Processing images causing optical illusions',['../d7/d8f/tutorial_bioinspired_retina_illusion.html',1,'tutorial_table_of_content_retina']]],
  ['processing_20imgproc_20module_43',['Image Processing (imgproc module)',['../d7/da8/tutorial_table_of_content_imgproc.html',1,'tutorial_root']]],
  ['processing_20in_20opencv_44',['Image Processing in OpenCV',['../d2/d96/tutorial_py_table_of_contents_imgproc.html',1,'tutorial_py_root']]],
  ['processing_20tutorials_45',['Fuzzy image processing tutorials',['../d7/d36/tutorial_fuzzy.html',1,'tutorial_contrib_root']]],
  ['projection_46',['Back Projection',['../da/d7f/tutorial_back_projection.html',1,'tutorial_table_of_content_imgproc']]],
  ['projects_47',['Cross referencing OpenCV from other Doxygen projects',['../d3/dff/tutorial_cross_referencing.html',1,'tutorial_table_of_content_introduction']]],
  ['properties_48',['properties',['../da/dc1/tutorial_js_contour_properties.html',1,'Contour Properties'],['../d1/d32/tutorial_py_contour_properties.html',1,'Contour Properties']]],
  ['pyramids_49',['pyramids',['../dc/dff/tutorial_py_pyramids.html',1,'Image Pyramids'],['../d5/d0f/tutorial_js_pyramids.html',1,'Image Pyramids'],['../d4/d1f/tutorial_pyramids.html',1,'Image Pyramids']]],
  ['python_50',['python',['../dc/d70/pytorch_cls_tutorial_dnn_conversion.html',1,'Conversion of PyTorch Classification Models and Launch with OpenCV Python'],['../d1/d8f/tf_cls_tutorial_dnn_conversion.html',1,'Conversion of TensorFlow Classification Models and Launch with OpenCV Python'],['../d4/d2f/tf_det_tutorial_dnn_conversion.html',1,'Conversion of TensorFlow Detection Models and Launch with OpenCV Python']]],
  ['python_20bindings_51',['OpenCV-Python Bindings',['../df/da2/tutorial_py_table_of_contents_bindings.html',1,'tutorial_py_root']]],
  ['python_20bindings_20works_52',['How OpenCV-Python Bindings Works?',['../da/d49/tutorial_py_bindings_basics.html',1,'tutorial_py_table_of_contents_bindings']]],
  ['python_20in_20fedora_53',['Install OpenCV-Python in Fedora',['../dd/dd5/tutorial_py_setup_in_fedora.html',1,'tutorial_py_table_of_contents_setup']]],
  ['python_20in_20ubuntu_54',['Install OpenCV-Python in Ubuntu',['../d2/de6/tutorial_py_setup_in_ubuntu.html',1,'tutorial_py_table_of_contents_setup']]],
  ['python_20in_20windows_55',['Install OpenCV-Python in Windows',['../d5/de5/tutorial_py_setup_in_windows.html',1,'tutorial_py_table_of_contents_setup']]],
  ['python_20tutorials_56',['python tutorials',['../d0/de3/tutorial_py_intro.html',1,'Introduction to OpenCV-Python Tutorials'],['../d6/d00/tutorial_py_root.html',1,'OpenCV-Python Tutorials']]],
  ['pytorch_20classification_20models_20and_20launch_20with_20opencv_20c_57',['Conversion of PyTorch Classification Models and Launch with OpenCV C++',['../dd/d55/pytorch_cls_c_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['pytorch_20classification_20models_20and_20launch_20with_20opencv_20python_58',['Conversion of PyTorch Classification Models and Launch with OpenCV Python',['../dc/d70/pytorch_cls_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['pytorch_20segmentation_20models_20and_20launch_20with_20opencv_59',['Conversion of PyTorch Segmentation Models and Launch with OpenCV',['../d7/d9a/pytorch_segm_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]]
];
