var searchData=
[
  ['data_0',['Support Vector Machines for Non-Linearly Separable Data',['../d0/dcc/tutorial_non_linear_svms.html',1,'tutorial_table_of_content_other']]],
  ['data_20format_20hdf_20i_20o_1',['The Hierarchical Data Format (hdf) I/O',['../d3/d00/tutorial_table_of_content_hdf.html',1,'tutorial_contrib_root']]],
  ['data_20structures_2',['Some Data Structures',['../d5/df1/tutorial_js_some_data_structures.html',1,'tutorial_js_table_of_contents_core']]],
  ['data_20using_20knn_3',['OCR of Hand-written Data using kNN',['../d8/d4b/tutorial_py_knn_opencv.html',1,'tutorial_py_knn_index']]],
  ['data_20using_20svm_4',['OCR of Hand-written Data using SVM',['../dd/d3b/tutorial_py_svm_opencv.html',1,'tutorial_py_svm_index']]],
  ['datasets_5',['Creating, Writing and Reading Datasets',['../d4/d93/tutorial_hdf_create_read_write_datasets.html',1,'tutorial_table_of_content_hdf']]],
  ['debian_6',['MultiArch cross-compilation with Ubuntu/Debian',['../d3/dd9/tutorial_crosscompile_with_multiarch.html',1,'tutorial_table_of_content_introduction']]],
  ['deblur_20filter_7',['deblur filter',['../d1/dfd/tutorial_motion_deblur_filter.html',1,'Motion Deblur Filter'],['../de/d3c/tutorial_out_of_focus_deblur_filter.html',1,'Out-of-focus Deblur Filter']]],
  ['debugger_8',['Image Watch: viewing in-memory images in the Visual Studio debugger',['../d4/d14/tutorial_windows_visual_studio_image_watch.html',1,'tutorial_table_of_content_introduction']]],
  ['debugging_20of_20computer_20vision_20applications_9',['Interactive Visual Debugging of Computer Vision applications',['../d7/dcf/tutorial_cvv_introduction.html',1,'tutorial_contrib_root']]],
  ['debugging_20the_20detection_20system_10',['Customising and Debugging the detection system',['../d0/de5/tutorial_mcc_debugging_the_system.html',1,'tutorial_table_of_content_mcc']]],
  ['decode_20gray_20code_20pattern_20tutorial_11',['Decode Gray code pattern tutorial',['../dc/da9/tutorial_decode_graycode_pattern.html',1,'tutorial_structured_light']]],
  ['deep_20learning_20layers_20support_12',['Custom deep learning layers support',['../dc/db1/tutorial_dnn_custom_layers.html',1,'tutorial_table_of_content_dnn']]],
  ['deep_20networks_20in_20browser_13',['How to run deep networks in browser',['../d5/d86/tutorial_dnn_javascript.html',1,'tutorial_table_of_content_dnn']]],
  ['deep_20networks_20on_20android_20device_14',['How to run deep networks on Android device',['../de/dfe/tutorial_android_dnn_intro.html',1,'tutorial_table_of_content_introduction']]],
  ['deep_20neural_20networks_20dnn_20module_15',['deep neural networks dnn module',['../d2/d58/tutorial_table_of_content_dnn.html',1,'Deep Neural Networks (dnn module)'],['../d0/db7/tutorial_js_table_of_contents_dnn.html',1,'Deep Neural Networks (dnn module)']]],
  ['demo_16',['Intelligent Scissors Demo',['../d9/df5/tutorial_js_intelligent_scissors.html',1,'tutorial_js_table_of_contents_imgproc']]],
  ['denoising_17',['Image Denoising',['../d5/d69/tutorial_py_non_local_means.html',1,'tutorial_py_table_of_contents_photo']]],
  ['dense_20stereo_18',['Quasi dense Stereo',['../d7/d5a/tutorial_qds_quasi_dense_stereo.html',1,'tutorial_table_of_content_quasi_dense_stereo']]],
  ['dense_20stereo_20stereo_20module_19',['Quasi Dense Stereo (stereo module)',['../d9/d58/tutorial_table_of_content_quasi_dense_stereo.html',1,'tutorial_contrib_root']]],
  ['deprecated_20list_20',['Deprecated List',['../da/d58/deprecated.html',1,'']]],
  ['depth_20map_20from_20stereo_20images_21',['Depth Map from Stereo Images',['../dd/d53/tutorial_py_depthmap.html',1,'tutorial_py_table_of_contents_calib3d']]],
  ['depth_20sensors_22',['depth sensors',['../db/d08/tutorial_intelperc.html',1,'Using Creative Senz3D and other Intel RealSense SDK compatible depth sensors'],['../df/d88/tutorial_gapi_oak_devices.html',1,'Using DepthAI Hardware / OAK depth sensors'],['../d7/d6f/tutorial_kinect_openni.html',1,'Using Kinect and other OpenNI compatible depth sensors']]],
  ['depthai_20hardware_20oak_20depth_20sensors_23',['Using DepthAI Hardware / OAK depth sensors',['../df/d88/tutorial_gapi_oak_devices.html',1,'tutorial_table_of_content_gapi']]],
  ['derivatives_24',['Sobel Derivatives',['../d2/d2c/tutorial_sobel_derivatives.html',1,'tutorial_table_of_content_imgproc']]],
  ['description_25',['description',['../d5/dde/tutorial_feature_description.html',1,'Feature Description'],['../db/d27/tutorial_py_table_of_contents_feature2d.html',1,'Feature Detection and Description']]],
  ['design_20overview_26',['High-level design overview',['../de/d4d/gapi_hld.html',1,'gapi']]],
  ['details_27',['Implementation details',['../d4/ddd/gapi_impl.html',1,'gapi']]],
  ['detecting_20colorcheckers_20using_20basic_20algorithms_28',['Detecting colorcheckers using basic algorithms',['../d9/d7e/tutorial_mcc_basic_chart_detection.html',1,'tutorial_table_of_content_mcc']]],
  ['detecting_20colorcheckers_20using_20neural_20network_29',['Detecting colorcheckers using neural network',['../d4/dc0/tutorial_mcc_chart_detection_enhanced_by_neural_network.html',1,'tutorial_table_of_content_mcc']]],
  ['detecting_20corners_20location_20in_20subpixels_30',['Detecting corners location in subpixels',['../dd/d92/tutorial_corner_subpixels.html',1,'tutorial_table_of_content_features2d']]],
  ['detection_31',['detection',['../d7/de1/tutorial_js_canny.html',1,'Canny Edge Detection'],['../da/d22/tutorial_py_canny.html',1,'Canny Edge Detection'],['../d0/d81/tutorial_table_of_content_mcc.html',1,'ColorChecker Detection'],['../d1/d52/tutorial_face_swapping_face_landmark_detection.html',1,'Face swapping using face landmark detection'],['../df/d0c/tutorial_py_fast.html',1,'FAST Algorithm for Corner Detection'],['../d7/d66/tutorial_feature_detection.html',1,'Feature Detection'],['../dc/d0d/tutorial_py_features_harris.html',1,'Harris Corner Detection'],['../dc/d73/tutorial_js_table_of_contents_objdetect.html',1,'Object Detection'],['../d9/de5/tutorial_py_table_of_contents_objdetect.html',1,'Object Detection'],['../d0/da5/tutorial_ximgproc_prediction.html',1,'Structured forests for fast edge detection']]],
  ['detection_20and_20description_32',['Feature Detection and Description',['../db/d27/tutorial_py_table_of_contents_feature2d.html',1,'tutorial_py_root']]],
  ['detection_20and_20recognition_33',['DNN-based Face Detection And Recognition',['../d0/dd4/tutorial_dnn_face.html',1,'tutorial_table_of_content_dnn']]],
  ['detection_20example_34',['Object Detection Example',['../d0/d0f/tutorial_js_object_detection.html',1,'tutorial_js_table_of_contents_dnn']]],
  ['detection_20example_20with_20camera_35',['Object Detection Example with Camera',['../d2/d14/tutorial_js_object_detection_with_camera.html',1,'tutorial_js_table_of_contents_dnn']]],
  ['detection_20in_20a_20video_36',['Face landmark detection in a video',['../d8/d3c/tutorial_face_landmark_detection_in_video.html',1,'tutorial_table_of_content_face']]],
  ['detection_20in_20an_20image_37',['Face landmark detection in an image',['../d2/d42/tutorial_face_landmark_detection_in_an_image.html',1,'tutorial_table_of_content_face']]],
  ['detection_20in_20video_20capture_38',['Face Detection in Video Capture',['../df/d6c/tutorial_js_face_detection_camera.html',1,'tutorial_js_table_of_contents_objdetect']]],
  ['detection_20models_20and_20launch_20with_20opencv_20python_39',['Conversion of TensorFlow Detection Models and Launch with OpenCV Python',['../d4/d2f/tf_det_tutorial_dnn_conversion.html',1,'tutorial_table_of_content_dnn']]],
  ['detection_20objdetect_20module_40',['Object Detection (objdetect module)',['../d2/d64/tutorial_table_of_content_objdetect.html',1,'tutorial_root']]],
  ['detection_20of_20aruco_20boards_41',['Detection of ArUco boards',['../db/da9/tutorial_aruco_board_detection.html',1,'tutorial_table_of_content_objdetect']]],
  ['detection_20of_20aruco_20markers_42',['Detection of ArUco Markers',['../d5/dae/tutorial_aruco_detection.html',1,'tutorial_table_of_content_objdetect']]],
  ['detection_20of_20charuco_20boards_43',['Detection of ChArUco Boards',['../df/d4a/tutorial_charuco_detection.html',1,'tutorial_table_of_content_objdetect']]],
  ['detection_20of_20diamond_20markers_44',['Detection of Diamond Markers',['../d5/d07/tutorial_charuco_diamond_detection.html',1,'tutorial_table_of_content_objdetect']]],
  ['detection_20of_20planar_20objects_45',['Detection of planar objects',['../dd/dd4/tutorial_detection_of_planar_objects.html',1,'tutorial_table_of_content_features2d']]],
  ['detection_20system_46',['Customising and Debugging the detection system',['../d0/de5/tutorial_mcc_debugging_the_system.html',1,'tutorial_table_of_content_mcc']]],
  ['detection_20using_20cnns_47',['Object Detection using CNNs',['../d2/da2/tutorial_dnn_objdetect.html',1,'tutorial_contrib_root']]],
  ['detection_20using_20haar_20cascades_48',['detection using haar cascades',['../d7/d8b/tutorial_py_face_detection.html',1,'Face Detection using Haar Cascades'],['../d2/d99/tutorial_js_face_detection.html',1,'Face Detection using Haar Cascades']]],
  ['detection_20with_20generalized_20ballard_20and_20guil_20hough_20transform_49',['Object detection with Generalized Ballard and Guil Hough Transform',['../da/ddc/tutorial_generalized_hough_ballard_guil.html',1,'tutorial_table_of_content_imgproc']]],
  ['detector_50',['detector',['../da/d5c/tutorial_canny_detector.html',1,'Canny Edge Detector'],['../d9/dbc/tutorial_generic_corner_detector.html',1,'Creating your own corner detector'],['../d4/d7d/tutorial_harris_detector.html',1,'Harris corner detector'],['../d8/dd8/tutorial_good_features_to_track.html',1,'Shi-Tomasi corner detector']]],
  ['detector_20api_51',['Tutorial on Facial Landmark Detector API',['../d5/d47/tutorial_table_of_content_facemark.html',1,'tutorial_contrib_root']]],
  ['detector_20good_20features_20to_20track_52',['Shi-Tomasi Corner Detector &amp; Good Features to Track',['../d4/d8c/tutorial_py_shi_tomasi.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['development_53',['development',['../d9/d3f/tutorial_android_dev_intro.html',1,'Introduction into Android Development'],['../d9/d52/tutorial_java_dev_intro.html',1,'Introduction to Java Development']]],
  ['development_20with_20clojure_54',['Introduction to OpenCV Development with Clojure',['../d7/d1e/tutorial_clojure_dev_intro.html',1,'tutorial_table_of_content_introduction']]],
  ['development_20with_20opencv_55',['Android Development with OpenCV',['../d5/df8/tutorial_dev_with_OCV_on_Android.html',1,'tutorial_table_of_content_introduction']]],
  ['device_56',['How to run deep networks on Android device',['../de/dfe/tutorial_android_dnn_intro.html',1,'tutorial_table_of_content_introduction']]],
  ['diamond_20markers_57',['Detection of Diamond Markers',['../d5/d07/tutorial_charuco_diamond_detection.html',1,'tutorial_table_of_content_objdetect']]],
  ['dilating_58',['Eroding and Dilating',['../db/df6/tutorial_erosion_dilatation.html',1,'tutorial_table_of_content_imgproc']]],
  ['dimensional_20phase_20maps_59',['Unwrap two-dimensional phase maps',['../d9/dfb/tutorial_unwrap.html',1,'tutorial_unwrap_phase_map']]],
  ['discovering_20the_20human_20retina_20and_20its_20use_20for_20image_20processing_60',['Discovering the human retina and its use for image processing',['../df/dee/tutorial_table_of_content_retina.html',1,'tutorial_contrib_root']]],
  ['discrete_20fourier_20transform_61',['Discrete Fourier Transform',['../d8/d01/tutorial_discrete_fourier_transform.html',1,'tutorial_table_of_content_core']]],
  ['disparity_20map_20post_20filtering_62',['Disparity map post-filtering',['../d3/d14/tutorial_ximgproc_disparity_filtering.html',1,'tutorial_contrib_root']]],
  ['distance_20transform_20and_20watershed_20algorithm_63',['Image Segmentation with Distance Transform and Watershed Algorithm',['../d2/dbd/tutorial_distance_transform.html',1,'tutorial_table_of_content_imgproc']]],
  ['dnn_20based_20face_20detection_20and_20recognition_64',['DNN-based Face Detection And Recognition',['../d0/dd4/tutorial_dnn_face.html',1,'tutorial_table_of_content_dnn']]],
  ['dnn_20module_65',['dnn module',['../d2/d58/tutorial_table_of_content_dnn.html',1,'Deep Neural Networks (dnn module)'],['../d0/db7/tutorial_js_table_of_contents_dnn.html',1,'Deep Neural Networks (dnn module)']]],
  ['dnn_5fandroid_66',['dnn_android',['../d1/d04/md__2build_24__x-contrib__docs-lin64_2opencv_2doc_2tutorials_2dnn_2dnn__android_2dnn__android.html',1,'']]],
  ['dnns_67',['YOLO DNNs',['../da/d9d/tutorial_dnn_yolo.html',1,'tutorial_table_of_content_dnn']]],
  ['documentation_20for_20opencv_68',['Writing documentation for OpenCV',['../d4/db1/tutorial_documentation.html',1,'tutorial_table_of_content_introduction']]],
  ['doxygen_20projects_69',['Cross referencing OpenCV from other Doxygen projects',['../d3/dff/tutorial_cross_referencing.html',1,'tutorial_table_of_content_introduction']]],
  ['drawing_70',['Basic Drawing',['../d3/d96/tutorial_basic_geometric_drawing.html',1,'tutorial_table_of_content_imgproc']]],
  ['drawing_20functions_20in_20opencv_71',['Drawing Functions in OpenCV',['../dc/da5/tutorial_py_drawing_functions.html',1,'tutorial_py_table_of_contents_gui']]],
  ['dynamic_20range_20hdr_72',['High Dynamic Range (HDR)',['../d2/df0/tutorial_py_hdr.html',1,'tutorial_py_table_of_contents_photo']]],
  ['dynamic_20range_20imaging_73',['High Dynamic Range Imaging',['../d3/db7/tutorial_hdr_imaging.html',1,'tutorial_table_of_content_other']]]
];
