var searchData=
[
  ['g_20api_0',['g api',['../d8/d24/tutorial_gapi_interactive_face_detection.html',1,'Face analytics pipeline with G-API'],['../d4/d48/tutorial_gapi_face_beautification.html',1,'Implementing a face beautification algorithm with G-API'],['../d3/d7a/tutorial_gapi_anisotropic_segmentation.html',1,'Porting anisotropic image segmentation on G-API']]],
  ['g_20api_20overview_1',['G-API Overview',['../de/d96/md_gapi_2doc_2slides_2README.html',1,'']]],
  ['gapi_20module_2',['Graph API (gapi module)',['../df/d7e/tutorial_table_of_content_gapi.html',1,'tutorial_root']]],
  ['gcc_20and_20cmake_3',['Using OpenCV with gcc and CMake',['../db/df5/tutorial_linux_gcc_cmake.html',1,'tutorial_table_of_content_introduction']]],
  ['gdal_4',['Reading Geospatial Raster files with GDAL',['../d7/d73/tutorial_raster_io_gdal.html',1,'tutorial_table_of_content_app']]],
  ['gdb_20powered_20ides_5',['Using OpenCV with gdb-powered IDEs',['../d6/d25/tutorial_linux_gdb_pretty_printer.html',1,'tutorial_table_of_content_introduction']]],
  ['generalized_20ballard_20and_20guil_20hough_20transform_6',['Object detection with Generalized Ballard and Guil Hough Transform',['../da/ddc/tutorial_generalized_hough_ballard_guil.html',1,'tutorial_table_of_content_imgproc']]],
  ['generator_20and_20text_20with_20opencv_7',['Random generator and text with OpenCV',['../df/d61/tutorial_random_generator_and_text.html',1,'tutorial_table_of_content_imgproc']]],
  ['geometric_20transformations_20of_20images_8',['geometric transformations of images',['../dd/d52/tutorial_js_geometric_transformations.html',1,'Geometric Transformations of Images'],['../da/d6e/tutorial_py_geometric_transformations.html',1,'Geometric Transformations of Images']]],
  ['geometry_9',['Epipolar Geometry',['../da/de9/tutorial_py_epipolar_geometry.html',1,'tutorial_py_table_of_contents_calib3d']]],
  ['geospatial_20raster_20files_20with_20gdal_10',['Reading Geospatial Raster files with GDAL',['../d7/d73/tutorial_raster_io_gdal.html',1,'tutorial_table_of_content_app']]],
  ['getting_20started_11',['getting started',['../d5/daa/tutorial_js_contours_begin.html',1,'Contours : Getting Started'],['../d4/d73/tutorial_py_contours_begin.html',1,'Contours : Getting Started']]],
  ['getting_20started_20with_20images_12',['getting started with images',['../dc/d2e/tutorial_py_image_display.html',1,'Getting Started with Images'],['../db/deb/tutorial_display_image.html',1,'Getting Started with Images'],['../df/d24/tutorial_js_image_display.html',1,'Getting Started with Images']]],
  ['getting_20started_20with_20videos_13',['getting started with videos',['../dd/d43/tutorial_py_video_display.html',1,'Getting Started with Videos'],['../dd/d00/tutorial_js_video_display.html',1,'Getting Started with Videos']]],
  ['git_20bash_20version_202_2014_201_20and_20cmake_20version_203_209_201_14',['Tesseract (master) installation by using git-bash (version&gt;=2.14.1) and cmake (version &gt;=3.9.1)',['../db/d4c/tutorial_install_tesseract.html',1,'tutorial_table_of_content_text']]],
  ['good_20features_20to_20track_15',['Shi-Tomasi Corner Detector &amp; Good Features to Track',['../d4/d8c/tutorial_py_shi_tomasi.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['gpu_16',['Similarity check (PNSR and SSIM) on the GPU',['../dd/d3d/tutorial_gpu_basics_similarity.html',1,'tutorial_table_of_content_gpu']]],
  ['gpu_20accelerated_20computer_20vision_20cuda_20module_17',['GPU-Accelerated Computer Vision (cuda module)',['../da/d2c/tutorial_table_of_content_gpu.html',1,'tutorial_root']]],
  ['grabcut_20algorithm_18',['grabcut algorithm',['../dd/dfc/tutorial_js_grabcut.html',1,'Foreground Extraction using GrabCut Algorithm'],['../d8/d83/tutorial_py_grabcut.html',1,'Interactive Foreground Extraction using GrabCut Algorithm']]],
  ['gradient_20structure_20tensor_19',['Anisotropic image segmentation by a gradient structure tensor',['../d4/d70/tutorial_anisotropic_image_segmentation_by_a_gst.html',1,'tutorial_table_of_content_imgproc']]],
  ['gradients_20',['gradients',['../da/d85/tutorial_js_gradients.html',1,'Image Gradients'],['../d5/d0f/tutorial_py_gradients.html',1,'Image Gradients']]],
  ['graph_20api_21',['graph api',['../d0/d1e/gapi.html',1,'Graph API'],['../d6/dc9/gapi_purposes.html',1,'Why Graph API?']]],
  ['graph_20api_20gapi_20module_22',['Graph API (gapi module)',['../df/d7e/tutorial_table_of_content_gapi.html',1,'tutorial_root']]],
  ['gray_20code_20pattern_20tutorial_23',['gray code pattern tutorial',['../db/d56/tutorial_capture_graycode_pattern.html',1,'Capture Gray code pattern tutorial'],['../dc/da9/tutorial_decode_graycode_pattern.html',1,'Decode Gray code pattern tutorial']]],
  ['groups_24',['Creating Groups',['../d1/d8b/tutorial_hdf_create_groups.html',1,'tutorial_table_of_content_hdf']]],
  ['gui_20and_20media_20highgui_20module_25',['High Level GUI and Media (highgui module)',['../d0/de2/tutorial_table_of_content_highgui.html',1,'']]],
  ['gui_20features_26',['GUI Features',['../df/d04/tutorial_js_table_of_contents_gui.html',1,'tutorial_js_root']]],
  ['gui_20features_20in_20opencv_27',['Gui Features in OpenCV',['../dc/d4d/tutorial_py_table_of_contents_gui.html',1,'tutorial_py_root']]],
  ['guide_28',['Transition guide',['../db/dfa/tutorial_transition_guide.html',1,'tutorial_table_of_content_introduction']]],
  ['guil_20hough_20transform_29',['Object detection with Generalized Ballard and Guil Hough Transform',['../da/ddc/tutorial_generalized_hough_ballard_guil.html',1,'tutorial_table_of_content_imgproc']]]
];
